semanticwfs: DCATFormatter Class Reference
DCATFormatter Class Reference
Formats metadata according to the GeoDCAT format.
Public Member Functions
String formatter (String collectionid, String collectioncall, String collectionurl, JSONObject workingobj, String format) throws XMLStreamException
String formatHeader ()
String formatFooter ()
Static Public Member Functions
static ResultMetadataFormatter getFormatter (String formatString)
Public Attributes
Integer lastQueriedElemCount =0
String mimeType ="text/plain"
String exposedType ="application/vnd.geo+json"
XMLStreamWriter xmlwriter
Static Public Attributes
static Map< String, ResultMetadataFormatter > resultMap =new TreeMap<String, ResultMetadataFormatter>()
Static Package Functions
[static initializer]
Package Attributes
GMDFormatter formatter =new GMDFormatter()
GMDFormatter to produce the initial GMD XML.
Detailed Description
Formats metadata according to the GeoDCAT format.
This class takes metadata formatted in the GMD standard and uses a XSLT stylesheet to convert the results to GeoDCAT.
Member Function Documentation
[static initializer]()
[static initializer] () static package inherited
formatFooter()
String formatFooter () inherited
{
                 return "";
         }
formatHeader()
String formatHeader () inherited
{
                 return "";
         }
formatter()
String formatter (String collectionid, String collectioncall, String collectionurl, JSONObject workingobj, String format) throws XMLStreamException
References GMDFormatter.formatter(), XSLTTransformer.GeoDCATToHTML(), XSLTTransformer.gmdToGeoDCAT(), and ResultMetadataFormatter.mimeType.
{
                 String gmd=formatter.formatter(collectionid, collectioncall, collectionurl, workingobj,format);
                 String gmdrdf;
                 try {
                         gmdrdf = XSLTTransformer.gmdToGeoDCAT(gmd);
                 if(format.contains("html")) {
                         this.mimeType=MediaType.TEXT_HTML;
                         return XSLTTransformer.GeoDCATToHTML(gmdrdf);
                 }
                 OntModel model = ModelFactory.createOntologyModel();
                 model.read(IOUtils.toInputStream(gmdrdf, "UTF-8"), null, "RDF/XML");
                 OutputStream output = new OutputStream() {
                     private StringBuilder string = new StringBuilder();
                     @Override
                     public void write(int b) throws IOException {
                         this.string.append((char) b );
                     }
                     //Netbeans IDE automatically overrides this toString()
                     public String toString() {
                         return this.string.toString();
                     }
                 };
                 if(format.contains("n3")) {
                         this.mimeType="text/n3";
                         model.write(output,"N3");
                         return output.toString();
                 }
                 if(format.contains("jsonld")) {
                         this.mimeType="application/ld+json";
                         model.write(output,"JSON-LD");
                         return output.toString();
                 }
                 if(format.contains("ttl")) {
                         this.mimeType="text/ttl";
                         model.write(output,"TTL");
                         return output.toString();
                 }
                 if(format.contains("ntriples")) {
                         this.mimeType="application/n-triples";
                         model.write(output,"NTRIPLES");
                         return output.toString();
                 }
                 this.mimeType=MediaType.APPLICATION_XML;
                 return gmdrdf;
                 } catch (TransformerException | IOException e) {
                         // TODO Auto-generated catch block
                         e.printStackTrace();
                         return "";
                 }
         }
getFormatter()
static ResultMetadataFormatter getFormatter (String formatString) static inherited
References ResultMetadataFormatter.formatter().
Referenced by WebService.getCollectionMetadata().
{
                 formatString=formatString.toLowerCase();
                 if(resultMap.containsKey(formatString)) {
                         return resultMap.get(formatString);
                 }
                 formatString=formatString.replace("+","");
                 if(formatString.contains("dcat")) {
                         return resultMap.get("geodcat");
                 }
                 return resultMap.get("gmd");
         }
Member Data Documentation
exposedType
String exposedType ="application/vnd.geo+json" inherited
formatter
GMDFormatter formatter =new GMDFormatter() package
GMDFormatter to produce the initial GMD XML.
lastQueriedElemCount
Integer lastQueriedElemCount =0 inherited
mimeType
String mimeType ="text/plain" inherited
Referenced by DCATFormatter.formatter(), WebService.getCollectionMetadata(), and GMDFormatter.GMDFormatter().
resultMap
Map<String,ResultMetadataFormatter> resultMap =new TreeMap<String, ResultMetadataFormatter>() static inherited
xmlwriter
XMLStreamWriter xmlwriter inherited
Referenced by GMDFormatter.formatter().