semanticwfs: User Class Reference
User Class Reference
Public Member Functions
User ()
User (String name, String password, UserType level)
String getName ()
String getUuid ()
void setUuid (String uuid)
void setName (String name)
String getPasswordHash ()
void setPasswordHash (String passwordHash)
UserType getUserlevel ()
void setUserlevel (UserType userlevel)
String toString ()
Public Attributes
String authToken
Private Attributes
String name
String passwordHash
UserType userlevel
String uuid
Constructor & Destructor Documentation
User() [1/2]
User ()
                      {
         }
User() [2/2]
User (String name, String password, UserType level)
References User.name, and UserType.toString().
{
                 this.name=name;
                 this.passwordHash=password;
                 this.userlevel=level;
                 this.uuid=UUID.randomUUID().toString();
                 this.authToken=UUID.randomUUID().toString();
         }
Member Function Documentation
getName()
String getName ()
References User.name.
Referenced by UserManagementConnection.UserHandler.startElement(), and UserManagementConnection.usersToHTML().
{
                 return name;
         }
getPasswordHash()
String getPasswordHash ()
References User.passwordHash.
{
                 return passwordHash;
         }
getUserlevel()
UserType getUserlevel ()
References User.userlevel.
Referenced by WebService.addEndpoint(), WebService.addFeatureType(), WebService.saveFeatureTypes(), and UserManagementConnection.usersToHTML().
{
                 return userlevel;
         }
getUuid()
String getUuid ()
References User.uuid.
{
                 return uuid;
         }
setName()
void setName (String name)
References User.name.
Referenced by UserManagementConnection.addUser(), UserManagementConnection.UserHandler.startElement(), and UserManagementConnection.updateUser().
{
                 this.name = name;
         }
setPasswordHash()
void setPasswordHash (String passwordHash)
References User.passwordHash.
Referenced by UserManagementConnection.addUser(), UserManagementConnection.UserHandler.startElement(), and UserManagementConnection.updateUser().
{
                 this.passwordHash = passwordHash;
         }
setUserlevel()
void setUserlevel (UserType userlevel)
References User.userlevel.
Referenced by UserManagementConnection.addUser(), UserManagementConnection.UserHandler.startElement(), and UserManagementConnection.updateUser().
{
                 this.userlevel = userlevel;
         }
setUuid()
void setUuid (String uuid)
References User.uuid.
Referenced by UserManagementConnection.login(), and UserManagementConnection.UserHandler.startElement().
{
                 this.uuid = uuid;
         }
toString()
String toString ()
References User.userlevel.
Referenced by WebService.getFeatureTypes().
{
                 return "Name: "+this.name+" - Level: "+userlevel;
         }
Member Data Documentation
authToken
String authToken
Referenced by WebService.login().
name
String name private
Referenced by User.getName(), User.setName(), and User.User().
passwordHash
String passwordHash private
Referenced by User.getPasswordHash(), and User.setPasswordHash().
userlevel
UserType userlevel private
Referenced by User.getUserlevel(), User.setUserlevel(), and User.toString().
uuid
String uuid private
Referenced by User.getUuid(), and User.setUuid().