semanticwfs: WFSResultFormatter Class Reference
WFSResultFormatter Class Reference abstract
Public Member Functions
abstract String formatter (ResultSet results, String startingElement, String featuretype, String propertytype, String typeColumn, Boolean onlyproperty, Boolean onlyhits, String srsName, String indvar, String epsg, List< String > eligiblenamespaces, List< String > noteligiblenamespaces, StyleObject mapstyle, Boolean alternativeFormat, Boolean invertXY) throws XMLStreamException
String formatHeader ()
String formatFooter ()
Static Public Member Functions
static ResultFormatter getFormatter (String formatString)
Public Attributes
Integer lastQueriedElemCount =0
String mimeType ="text/plain"
String exposedType ="application/vnd.geojson"
Map< String, String > contextMapper =new TreeMap<>()
ResultStyleFormatter styleformatter
Static Public Attributes
static Map< String, ResultFormatter > resultMap =new TreeMap<String, ResultFormatter>()
Static Package Functions
[static initializer]
Package Attributes
String featureType =""
Member Function Documentation
[static initializer]()
[static initializer] () static package
formatFooter()
String formatFooter () inherited
{
                 return "";
         }
formatHeader()
String formatHeader () inherited
{
                 return "";
         }
formatter()
abstract String formatter (ResultSet results, String startingElement, String featuretype, String propertytype, String typeColumn, Boolean onlyproperty, Boolean onlyhits, String srsName, String indvar, String epsg, List< String > eligiblenamespaces, List< String > noteligiblenamespaces, StyleObject mapstyle, Boolean alternativeFormat, Boolean invertXY) throws XMLStreamException abstract inherited
Referenced by TripleStoreConnector.executePropertyValueQuery(), TripleStoreConnector.executeQuery(), GeoJSONLDFormatter.formatter(), RDFFormatter.formatter(), TrigFormatter.formatter(), N3Formatter.formatter(), TrixFormatter.formatter(), NTFormatter.formatter(), RDFJSONFormatter.formatter(), KMLFormatter.formatter(), GPXFormatter.formatter(), GMLFormatter.formatter(), HTMLFormatter.formatter(), and ResultFormatter.getFormatter().
getFormatter()
static ResultFormatter getFormatter (String formatString) static inherited
References ResultFormatter.formatter().
Referenced by WebService.collectionItems(), WebService.collections(), WebService.conformance(), TripleStoreConnector.executePropertyValueQuery(), TripleStoreConnector.executeQuery(), and WebService.queryables().
{
                 formatString=formatString.toLowerCase();
                 if(resultMap.containsKey(formatString)) {
                         return resultMap.get(formatString);
                 }
                 if(formatString.equals("application/vnd.geo+json+ld") || formatString.contains("geojsonld") || formatString.contains("geo+json+ld")) {
                         return resultMap.get("geojsonld");
                 }
                 if(formatString.equals("application/geojson") || formatString.contains("geojson") || formatString.contains("geo+json")) {
                         return resultMap.get("geojson");
                 }
                 if(formatString.contains("gml")) {
                         return resultMap.get("gml");
                 }
                 if(formatString.contains("html")) {
                         return resultMap.get("html");
                 }
                 if(formatString.contains("csv")) {
                         return resultMap.get("csv");
                 }
                 if(formatString.contains("gpx")) {
                         return resultMap.get("gpx");
                 }
                 if(formatString.contains("ttl")) {
                         return resultMap.get("ttl");
                 }
                 if(formatString.contains("rdfjson")) {
                         return resultMap.get("rdfjson");
                 }
                 if(formatString.contains("rdf")) {
                         return resultMap.get("rdf");
                 }
                 if(formatString.contains("n3")) {
                         return resultMap.get("n3");
                 }
                 if(formatString.contains("nt")) {
                         return resultMap.get("nt");
                 }
                 if(formatString.contains("trig")) {
                         return resultMap.get("trig");
                 }
                 if(formatString.contains("trix")) {
                         return resultMap.get("trix");
                 }
                 if(formatString.contains("geohash")) {
                         return resultMap.get("geohash");
                 }
                 if(formatString.contains("topojson")) {
                         return resultMap.get("topojson");
                 }
                 if(formatString.contains("covjson")) {
                         return resultMap.get("covjson");
                 }
                 if(formatString.contains("jsonld")) {
                         return resultMap.get("jsonld");
                 }
                 if(formatString.contains("json")) {
                         return resultMap.get("geojson");
                 }
                 if(formatString.contains("kml")) {
                         return resultMap.get("kml");
                 }
                 if(formatString.contains("geouri")) {
                         return resultMap.get("geouri");
                 }
                 if(formatString.contains("geotiff")) {
                         return resultMap.get("geotiff");
                 }
                 if(formatString.contains("polyshape")) {
                         return resultMap.get("polyshape");
                 }
                 return resultMap.get("html");
         }
Member Data Documentation
contextMapper
Map<String,String> contextMapper =new TreeMap<>() inherited
Referenced by GeoJSONFormatter.addKeyVal(), GeoJSONFormatter.addKeyValList(), GeoJSONLDFormatter.formatter(), GeoJSONFormatter.formatter(), and GeoJSONFormatter.relToMap().
exposedType
String exposedType ="application/vnd.geojson" inherited
Referenced by CovJSONFormatter.CovJSONFormatter(), CSVFormatter.CSVFormatter(), GeoHashFormatter.GeoHashFormatter(), GeoJSONFormatter.GeoJSONFormatter(), GeoJSONLDFormatter.GeoJSONLDFormatter(), GeoTIFFFormatter.GeoTIFFFormatter(), GeoURIFormatter.GeoURIFormatter(), GMLCOVFormatter.GMLCOVFormatter(), GMLFormatter.GMLFormatter(), GPXFormatter.GPXFormatter(), HTMLFormatter.HTMLFormatter(), JSONFormatter.JSONFormatter(), JSONLDFormatter.JSONLDFormatter(), KMLFormatter.KMLFormatter(), N3Formatter.N3Formatter(), NTFormatter.NTFormatter(), PolyshapeFormatter.PolyshapeFormatter(), RDFFormatter.RDFFormatter(), RDFJSONFormatter.RDFJSONFormatter(), TopoJSONFormatter.TopoJSONFormatter(), TrigFormatter.TrigFormatter(), TrixFormatter.TrixFormatter(), and TTLFormatter.TTLFormatter().
featureType
String featureType ="" package
lastQueriedElemCount
Integer lastQueriedElemCount =0 inherited
Referenced by TripleStoreConnector.executePropertyValueQuery(), TripleStoreConnector.executeQuery(), CSVFormatter.formatter(), GeoHashFormatter.formatter(), GeoURIFormatter.formatter(), TTLFormatter.formatter(), JSONFormatter.formatter(), GeoJSONLDFormatter.formatter(), JSONLDFormatter.formatter(), N3Formatter.formatter(), NTFormatter.formatter(), RDFFormatter.formatter(), RDFJSONFormatter.formatter(), TrixFormatter.formatter(), TrigFormatter.formatter(), GeoJSONFormatter.formatter(), KMLFormatter.formatter(), GPXFormatter.formatter(), GMLFormatter.formatter(), and HTMLFormatter.formatter().
mimeType
String mimeType ="text/plain" inherited
Referenced by WebService.collectionItems(), WebService.collections(), WebService.conformance(), CovJSONFormatter.CovJSONFormatter(), CSVFormatter.CSVFormatter(), GeoHashFormatter.GeoHashFormatter(), GeoJSONFormatter.GeoJSONFormatter(), GeoJSONLDFormatter.GeoJSONLDFormatter(), GeoTIFFFormatter.GeoTIFFFormatter(), GeoURIFormatter.GeoURIFormatter(), GMLCOVFormatter.GMLCOVFormatter(), GMLFormatter.GMLFormatter(), GPXFormatter.GPXFormatter(), HTMLFormatter.HTMLFormatter(), JSONFormatter.JSONFormatter(), JSONLDFormatter.JSONLDFormatter(), KMLFormatter.KMLFormatter(), N3Formatter.N3Formatter(), NTFormatter.NTFormatter(), PolyshapeFormatter.PolyshapeFormatter(), RDFFormatter.RDFFormatter(), RDFJSONFormatter.RDFJSONFormatter(), TopoJSONFormatter.TopoJSONFormatter(), TrigFormatter.TrigFormatter(), TrixFormatter.TrixFormatter(), and TTLFormatter.TTLFormatter().
resultMap
Map<String,ResultFormatter> resultMap =new TreeMap<String, ResultFormatter>() static inherited
Referenced by WebService.collectionInformation(), WebService.collectionItems(), WebService.collections(), WebService.constructCapabilitiesWFS10(), WebService.describeFeatureType(), WebService.describeFeatureTypeWFS10(), GeoJSONLDFormatter.formatter(), NTFormatter.formatter(), TrixFormatter.formatter(), RDFFormatter.formatter(), TrigFormatter.formatter(), RDFJSONFormatter.formatter(), N3Formatter.formatter(), KMLFormatter.formatter(), GPXFormatter.formatter(), GMLFormatter.formatter(), HTMLFormatter.formatter(), and WebService.getFeatureById().
styleformatter
ResultStyleFormatter styleformatter inherited
Referenced by GeoJSONFormatter.formatter(), KMLFormatter.formatter(), GeoJSONFormatter.GeoJSONFormatter(), and KMLFormatter.KMLFormatter().