semanticwfs: ResultStyleFormatter Class Reference
ResultStyleFormatter Class Reference abstract
Public Member Functions
abstract String formatter (ResultSet results, String featuretype) throws XMLStreamException
String formatHeader ()
String formatFooter ()
abstract String formatGeometry (String geometrytype, StyleObject styleobj)
Static Public Member Functions
static ResultStyleFormatter getFormatter (String formatString)
Public Attributes
Integer lastQueriedElemCount =0
String mimeType ="text/plain"
String exposedType ="application/vnd.geo+json"
String styleAttribute =""
Static Public Attributes
static Map< String, ResultStyleFormatter > resultMap =new TreeMap<String, ResultStyleFormatter>()
Static Package Functions
[static initializer]
Member Function Documentation
[static initializer]()
[static initializer] () static package
formatFooter()
String formatFooter ()
References ResultStyleFormatter.formatGeometry().
{
                 return "";
         }
formatGeometry()
abstract String formatGeometry (String geometrytype, StyleObject styleobj) abstract
Referenced by ResultStyleFormatter.formatFooter(), GeoJSONFormatter.formatter(), and KMLFormatter.formatter().
formatHeader()
String formatHeader ()
{
                 return "";
         }
formatter()
abstract String formatter (ResultSet results, String featuretype) throws XMLStreamException abstract
Referenced by ResultStyleFormatter.getFormatter().
getFormatter()
static ResultStyleFormatter getFormatter (String formatString) static
References ResultStyleFormatter.formatter().
{
                 formatString=formatString.toLowerCase();
                 if(resultMap.containsKey(formatString)) {
                         return resultMap.get(formatString);
                 }
                 formatString=formatString.replace("+","");
                 if(formatString.contains("mapcss")) {
                         return resultMap.get("mapcss");
                 }
                 if(formatString.contains("geojsoncss")) {
                         return resultMap.get("geojsoncss");
                 }
                 if(formatString.contains("sld")) {
                         return resultMap.get("sld");
                 }
                 return null;
         }
Member Data Documentation
exposedType
String exposedType ="application/vnd.geo+json"
Referenced by SLDFormatter.formatter().
lastQueriedElemCount
Integer lastQueriedElemCount =0
mimeType
String mimeType ="text/plain"
resultMap
Map<String,ResultStyleFormatter> resultMap =new TreeMap<String, ResultStyleFormatter>() static
styleAttribute
String styleAttribute =""
Referenced by GeoJSONFormatter.formatter(), GeoJSONCSSFormatter.GeoJSONCSSFormatter(), and SimpleStyleFormatter.SimpleStyleFormatter().