semanticwfs: UserManagementConnection.UserHandler Class Reference
UserManagementConnection.UserHandler Class Reference
SAXParser DefaultHandler für das Parsen von einem XML File mit den Benutzerdaten.
Public Member Functions
UserHandler (Map< String, User > usermap, Map< String, User > uuidToUser)
void startElement (String arg0, String arg1, String arg2, Attributes arg3) throws SAXException
Private Attributes
Map< String, User > usermap
Map< String, User > uuidToUser
Detailed Description
SAXParser DefaultHandler für das Parsen von einem XML File mit den Benutzerdaten.
Constructor & Destructor Documentation
UserHandler()
UserHandler (Map< String, User > usermap, Map< String, User > uuidToUser)
References UserManagementConnection.UserHandler.usermap, and UserManagementConnection.UserHandler.uuidToUser.
{
                         this.usermap=usermap;
                         this.uuidToUser=uuidToUser;
                 }
Member Function Documentation
startElement()
void startElement (String arg0, String arg1, String arg2, Attributes arg3) throws SAXException
References User.getName(), User.setName(), User.setPasswordHash(), User.setUserlevel(), and User.setUuid().
{
                         super.startElement(arg0, arg1, arg2, arg3);
                         if(arg2.equals("user")){
                                 User user=new User();
                                 user.setName(arg3.getValue("name"));
                                 user.setPasswordHash(arg3.getValue("password"));
                                 user.setUserlevel(UserType.valueOf(arg3.getValue("level")));
                                 user.setUuid(arg3.getValue("uuid"));
                                 this.usermap.put(user.getName(),user);
                                 this.uuidToUser.put(arg3.getValue("uuid"),user);
                         }
                 }
Member Data Documentation
usermap
Map<String,User> usermap private
Referenced by UserManagementConnection.UserHandler.UserHandler().
uuidToUser
Map<String,User> uuidToUser private
Referenced by UserManagementConnection.UserHandler.UserHandler().