semanticwfs: User Class Reference
User Class Reference
Represents a user who may log in to the system.
Public Member Functions
User ()
Empty constructor to gradually fill the user object.
User (String name, String password, UserType level)
Constructor for this class.
String getName ()
Gets the name of the user.
String getUuid ()
Gets the uuid of the user.
void setUuid (String uuid)
Sets the UUID of the user.
void setName (String name)
Sets the name of the user.
String getPasswordHash ()
Gets the password hash of the user.
void setPasswordHash (String passwordHash)
Sets the password hash of the user.
UserType getUserlevel ()
Gets the user level of the user.
void setUserlevel (UserType userlevel)
Sets the user level of the user.
String toString ()
Public Attributes
String authToken
An auth token which has been given to this user to authenticate for web services.
Private Attributes
String name
The name of the user.
String passwordHash
The password hash used for authentification.
UserType userlevel
The authorization level given to this user.
String uuid
The current UUID assigned to this user.
Detailed Description
Represents a user who may log in to the system.
Constructor & Destructor Documentation
User() [1/2]
User ()
Empty constructor to gradually fill the user object.
                      {
         }
User() [2/2]
User (String name, String password, UserType level)
Constructor for this class.
Parameters
name The user name
password The password assigned to the user
level the user level
References User.name, and UserType.toString().
{
                 this.name=name;
                 this.passwordHash=password;
                 this.userlevel=level;
                 this.uuid=UUID.randomUUID().toString();
                 this.authToken=UUID.randomUUID().toString();
         }
Member Function Documentation
getName()
String getName ()
Gets the name of the user.
Returns
The name as String
References User.name.
Referenced by UserManagementConnection.UserHandler.startElement(), and UserManagementConnection.usersToHTML().
{
                 return name;
         }
getPasswordHash()
String getPasswordHash ()
Gets the password hash of the user.
Returns
The password hash as String
References User.passwordHash.
{
                 return passwordHash;
         }
getUserlevel()
UserType getUserlevel ()
Gets the user level of the user.
Returns
The userlevel as a Usertype
References User.userlevel.
Referenced by WebService.addEndpoint(), WebService.addFeatureType(), WebService.saveFeatureTypes(), and UserManagementConnection.usersToHTML().
{
                 return userlevel;
         }
getUuid()
String getUuid ()
Gets the uuid of the user.
Returns
The uuid as String
References User.uuid.
{
                 return uuid;
         }
setName()
void setName (String name)
Sets the name of the user.
Parameters
name The name as String
References User.name.
Referenced by UserManagementConnection.addUser(), UserManagementConnection.UserHandler.startElement(), and UserManagementConnection.updateUser().
{
                 this.name = name;
         }
setPasswordHash()
void setPasswordHash (String passwordHash)
Sets the password hash of the user.
Parameters
passwordHash The passwordHash as String
References User.passwordHash.
Referenced by UserManagementConnection.addUser(), UserManagementConnection.UserHandler.startElement(), and UserManagementConnection.updateUser().
{
                 this.passwordHash = passwordHash;
         }
setUserlevel()
void setUserlevel (UserType userlevel)
Sets the user level of the user.
Parameters
userlevel The userlevel as UserType
References User.userlevel.
Referenced by UserManagementConnection.addUser(), UserManagementConnection.UserHandler.startElement(), and UserManagementConnection.updateUser().
{
                 this.userlevel = userlevel;
         }
setUuid()
void setUuid (String uuid)
Sets the UUID of the user.
Parameters
uuid The uuid as String
References User.uuid.
Referenced by UserManagementConnection.login(), and UserManagementConnection.UserHandler.startElement().
{
                 this.uuid = uuid;
         }
toString()
String toString ()
References User.userlevel.
Referenced by WebService.getFeatureTypes().
{
                 return "Name: "+this.name+" - Level: "+userlevel;
         }
Member Data Documentation
authToken
String authToken
An auth token which has been given to this user to authenticate for web services.
Referenced by WebService.login().
name
String name private
The name of the user.
Referenced by User.getName(), User.setName(), and User.User().
passwordHash
String passwordHash private
The password hash used for authentification.
Referenced by User.getPasswordHash(), and User.setPasswordHash().
userlevel
UserType userlevel private
The authorization level given to this user.
Referenced by User.getUserlevel(), User.setUserlevel(), and User.toString().
uuid
String uuid private
The current UUID assigned to this user.
Referenced by User.getUuid(), and User.setUuid().