semanticwfs: ReprojectionUtils Class Reference
ReprojectionUtils Class Reference
Static Public Member Functions
static String crsURIToEPSG (String uri)
static Geometry reproject (Geometry geom, String sourceCRS, String targetCRS)
static Geometry toGeometry (final org.opengis.geometry.Envelope envelope)
static Geometry toGeometry (final Envelope envelope)
static Geometry toGeometry (final Envelope2D envelope)
static Geometry toGeometry (final OctagonalEnvelope envelope)
static Geometry toGeometry (final Rectangle envelope)
static Geometry createGeometry (Coordinate[] coordinates, String geomtype, Integer srid)
static Geometry createGeometryCollection (List< Geometry > geometries, String geomtype, Integer srid)
static Geometry createGeometryCollection (Geometry[] geometries, String geomtype, Integer srid)
static Geometry createGeometry (List< Coordinate > coordarray, String geomtype, Integer srid)
Static Package Attributes
static CRSFactory csFactory = new CRSFactory()
static CoordinateTransformFactory ctFactory = new CoordinateTransformFactory()
static GeometryFactory fac =new GeometryFactory()
Member Function Documentation
createGeometry() [1/2]
static Geometry createGeometry (Coordinate [] coordinates, String geomtype, Integer srid) static
Referenced by ReprojectionUtils.createGeometry(), and ReprojectionUtils.reproject().
{
                         GeometryFactory fac=new GeometryFactory();
                         Geometry geom;
                         switch(geomtype) {
                         case "Point":
                                 geom= fac.createPoint(coordinates[0]);
                                 geom.setSRID(srid);
                                 return geom;
                         case "MultiPoint":
                                 geom=fac.createMultiPointFromCoords(coordinates);
                                 geom.setSRID(srid);
                                 return geom;
                         case "LineString":
                                 geom= fac.createLineString(coordinates);
                                 geom.setSRID(srid);
                                 return geom;
                         case "Polygon":
                                 geom= fac.createPolygon(coordinates);
                                 geom.setSRID(srid);
                                 return geom;
                         case "MultiLineString":
                                 List<LineString> list=new LinkedList<LineString>();
                                 list.add(fac.createLineString(coordinates));
                                 geom= fac.createMultiLineString(list.toArray(new LineString[0]));
                                 geom.setSRID(srid);
                                 return geom;
                         case "MultiPolygon":
                                 List<Polygon> plist=new LinkedList<Polygon>();
                                 plist.add(fac.createPolygon(coordinates));
                                 geom= fac.createMultiPolygon(plist.toArray(new Polygon[0]));
                                 geom.setSRID(srid);
                                 return geom;
                         default:
                                 return null;
                         }
                 }
createGeometry() [2/2]
static Geometry createGeometry (List< Coordinate > coordarray, String geomtype, Integer srid) static
References ReprojectionUtils.createGeometry().
{
                         return createGeometry(coordarray.toArray(new Coordinate[0]), geomtype,srid);
                 }
createGeometryCollection() [1/2]
static Geometry createGeometryCollection (List< Geometry > geometries, String geomtype, Integer srid) static
{
                         return createGeometryCollection(geometries.toArray(new Geometry[0]), geomtype, srid);
                 }
createGeometryCollection() [2/2]
static Geometry createGeometryCollection (Geometry [] geometries, String geomtype, Integer srid) static
{
                         GeometryFactory fac=new GeometryFactory();
                         return fac.createGeometryCollection(geometries);
                 }
crsURIToEPSG()
static String crsURIToEPSG (String uri) static
Referenced by ReprojectionUtils.reproject().
{
                 if(uri.startsWith("http")) {
                         uri=uri.replace(">","");
                         return "EPSG:"+uri.substring(uri.lastIndexOf('/')+1);
                 }else if(uri.startsWith("EPSG")) {
                         return uri;
                 }
                 return "";
         }
reproject()
static Geometry reproject (Geometry geom, String sourceCRS, String targetCRS) static
References ReprojectionUtils.createGeometry(), and ReprojectionUtils.crsURIToEPSG().
Referenced by WKTFormatter.formatter(), WKBFormatter.formatter(), OSMLinkFormatter.formatter(), and LatLonTextFormatter.formatter().
{
                 if(sourceCRS==null || sourceCRS.isEmpty() || targetCRS==null || targetCRS.isEmpty())
                         return geom;
                 String src=crsURIToEPSG(sourceCRS);
                 String target=crsURIToEPSG(targetCRS);
                 if(src.isEmpty() || target.isEmpty() || src.equals(target)) {
                         return geom;
                 }
                 CoordinateReferenceSystem crs1 = csFactory.createFromName(src);
         CoordinateReferenceSystem crs2 = csFactory.createFromName(target);
         CoordinateTransform trans = ctFactory.createTransform(crs1, crs2);
         Coordinate[] oldcoords=geom.getCoordinates();
         Coordinate[] newcoords=new Coordinate[oldcoords.length];
         int i=0;
                 for(Coordinate cur:oldcoords) {
                          ProjCoordinate p1 = new ProjCoordinate();
                      ProjCoordinate p2 = new ProjCoordinate();
                      p1.x = cur.x;
                      p1.y = cur.y;
                      trans.transform(p1, p2);
                      newcoords[i]=new Coordinate(p2.x,p2.y);
                 }
                 return ReprojectionUtils.createGeometry(newcoords, geom.getGeometryType(), geom.getSRID());
         }
toGeometry() [1/5]
static Geometry toGeometry (final org.opengis.geometry.Envelope envelope) static
{
         GeometryFactory gf = new GeometryFactory();
         return gf.createPolygon(gf.createLinearRing(
                 new Coordinate[]{
                     new Coordinate(envelope.getLowerCorner().getDirectPosition().getCoordinate()[0], envelope.getLowerCorner().getDirectPosition().getCoordinate()[1]),
                     new Coordinate(envelope.getUpperCorner().getDirectPosition().getCoordinate()[0], envelope.getLowerCorner().getDirectPosition().getCoordinate()[1]),
                     new Coordinate(envelope.getUpperCorner().getDirectPosition().getCoordinate()[0], envelope.getUpperCorner().getDirectPosition().getCoordinate()[1]),
                     new Coordinate(envelope.getLowerCorner().getDirectPosition().getCoordinate()[0], envelope.getLowerCorner().getDirectPosition().getCoordinate()[1]),
                     new Coordinate(envelope.getLowerCorner().getDirectPosition().getCoordinate()[0], envelope.getLowerCorner().getDirectPosition().getCoordinate()[1])
                 }), null);
     }
toGeometry() [2/5]
static Geometry toGeometry (final Envelope envelope) static
{
         GeometryFactory gf = new GeometryFactory();
         return gf.createPolygon(gf.createLinearRing(
                 new Coordinate[]{
                     new Coordinate(envelope.getMinX(), envelope.getMinY()),
                     new Coordinate(envelope.getMaxX(), envelope.getMinY()),
                     new Coordinate(envelope.getMaxX(), envelope.getMaxY()),
                     new Coordinate(envelope.getMinX(), envelope.getMaxY()),
                     new Coordinate(envelope.getMinX(), envelope.getMinY())
                 }), null);
     }
toGeometry() [3/5]
static Geometry toGeometry (final Envelope2D envelope) static
{
         GeometryFactory gf = new GeometryFactory();
         return gf.createPolygon(gf.createLinearRing(
                 new Coordinate[]{
                     new Coordinate(envelope.getMinX(), envelope.getMinY()),
                     new Coordinate(envelope.getMaxX(), envelope.getMinY()),
                     new Coordinate(envelope.getMaxX(), envelope.getMaxY()),
                     new Coordinate(envelope.getMinX(), envelope.getMaxY()),
                     new Coordinate(envelope.getMinX(), envelope.getMinY())
                 }), null);
     }
toGeometry() [4/5]
static Geometry toGeometry (final OctagonalEnvelope envelope) static
{
         GeometryFactory gf = new GeometryFactory();
         return gf.createPolygon(gf.createLinearRing(
                 new Coordinate[]{
                     new Coordinate(envelope.getMinX(), envelope.getMinY()),
                     new Coordinate(envelope.getMaxX(), envelope.getMinY()),
                     new Coordinate(envelope.getMaxX(), envelope.getMaxY()),
                     new Coordinate(envelope.getMinX(), envelope.getMaxY()),
                     new Coordinate(envelope.getMinX(), envelope.getMinY())
                 }), null);
     }
toGeometry() [5/5]
static Geometry toGeometry (final Rectangle envelope) static
{
                 GeometryFactory gf = new GeometryFactory();
                 return gf.createPolygon(gf.createLinearRing(
                         new Coordinate[]{
                             new Coordinate(envelope.getMinX(), envelope.getMinY()),
                             new Coordinate(envelope.getMaxX(), envelope.getMinY()),
                             new Coordinate(envelope.getMaxX(), envelope.getMaxY()),
                             new Coordinate(envelope.getMinX(), envelope.getMaxY()),
                             new Coordinate(envelope.getMinX(), envelope.getMinY())
                         }), null);
             }
Member Data Documentation
csFactory
CRSFactory csFactory = new CRSFactory() static package
ctFactory
CoordinateTransformFactory ctFactory = new CoordinateTransformFactory() static package
fac
GeometryFactory fac =new GeometryFactory() static package