semanticwfs: SimpleStyleFormatter Class Reference
SimpleStyleFormatter Class Reference
Reads an ontological style description and formats it according to the mapbox simple style specification.
Public Member Functions
SimpleStyleFormatter ()
Constructor for this class.
JSONObject cssLiteralToJSON (String cssString)
Converts a CSS literal given in the ontology to a JSON representation.
String formatter (ResultSet results, String featuretype) throws XMLStreamException
String formatGeometry (String geometrytype, StyleObject styleobj)
String formatHeader ()
String formatFooter ()
Static Public Member Functions
static ResultStyleFormatter getFormatter (String formatString)
Gets a style formatter for a chosen style type.
Public Attributes
Integer lastQueriedElemCount =0
String mimeType ="text/plain"
String exposedType ="application/vnd.geo+json"
String styleAttribute =""
Static Public Attributes
static Map< String, ResultStyleFormatter > resultMap =new TreeMap<String, ResultStyleFormatter>()
Static Package Functions
[static initializer]
Detailed Description
Reads an ontological style description and formats it according to the mapbox simple style specification.
Constructor & Destructor Documentation
SimpleStyleFormatter()
SimpleStyleFormatter ()
Constructor for this class.
References ResultStyleFormatter.styleAttribute.
{
                 this.styleAttribute="properties";
         }
Member Function Documentation
[static initializer]()
[static initializer] () static package inherited
cssLiteralToJSON()
JSONObject cssLiteralToJSON (String cssString)
Converts a CSS literal given in the ontology to a JSON representation.
Parameters
cssString the literal value
Returns
the JSON object to contain the style information
Referenced by SimpleStyleFormatter.formatGeometry().
{
                 JSONObject styleproperties=new JSONObject();
                 if(cssString==null)
                         return styleproperties;
                 cssString=cssString.substring(0,cssString.indexOf("^^"));
                 if(cssString.contains(";")) {
                         for(String statement:cssString.split(";")) {
                                 String[] split=statement.split(":");
                                 styleproperties.put(split[0].replace("\\","").replace("\"","").replace("{","").replace("}","").trim(),
                                                 split[1].replace("\\","").replace("\"","").replace("{","").replace("}","").trim());
                         }
                 }else if(cssString.contains(",")) {
                         for(String statement:cssString.split(",")) {
                                 String[] split=statement.split(":");
                                 styleproperties.put(split[0].replace("\\","").replace("\"","").replace("{","").replace("}","").trim(),
                                                 split[1].replace("\\","").replace("\"","").replace("{","").replace("}","").trim());
                         }
                 }else {
                         String[] split=cssString.split(":");
                         styleproperties.put(split[0].replace("\\","").replace("\"","").replace("{","").replace("}","").trim(),
                                         split[1].replace("\\","").replace("\"","").replace("{","").replace("}","").trim());
                 }
                 return styleproperties;
         }
formatFooter()
String formatFooter () inherited
References ResultStyleFormatter.formatGeometry().
{
                 return "";
         }
formatGeometry()
String formatGeometry (String geometrytype, StyleObject styleobj)
References SimpleStyleFormatter.cssLiteralToJSON(), StyleObject.hatch, StyleObject.lineStringImage, StyleObject.lineStringStyle, StyleObject.pointImage, StyleObject.pointStyle, StyleObject.polygonImage, and StyleObject.polygonStyle.
{
                 if(geometrytype.contains("Point")) {
                     JSONObject props=cssLiteralToJSON(styleobj.pointStyle);
                     if(styleobj.pointImage!=null) {
                         JSONObject iconobj=new JSONObject();
                         if(styleobj.pointImage.contains("svg")) {
                                 iconobj.put("iconUrl", "url('data:image/svg+xml;utf8,"+styleobj.pointImage+"')");
                         }else if(styleobj.pointImage.contains("http")) {
                                 iconobj.put("iconUrl", styleobj.pointImage);
                         }else {
                                 iconobj.put("iconUrl", styleobj.pointImage);
                         }
                         JSONArray size=new JSONArray();
                         size.put(32);
                         size.put(32);
                         JSONArray anchor=new JSONArray();
                         size.put(16);
                         size.put(16);
                         iconobj.put("iconSize",size);
                         iconobj.put("iconAnchor", anchor);
                                 props.put("icon", iconobj);
                     }
                         System.out.println(props.toString());
                     return props.toString();
                 }
                 if(geometrytype.contains("LineString")) {
                         JSONObject props=cssLiteralToJSON(styleobj.lineStringStyle);
                          if(styleobj.lineStringImage!=null) {
                                 JSONObject iconobj=new JSONObject();
                                 if(styleobj.lineStringImage.contains("svg")) {
                                         iconobj.put("iconUrl", "url('data:image/svg+xml;utf8,"+styleobj.lineStringImage+"')");
                                 }else if(styleobj.lineStringImage.contains("http")) {
                                         iconobj.put("iconUrl", styleobj.lineStringImage);
                                 }else {
                                         iconobj.put("iconUrl", styleobj.lineStringImage);
                                 }
                                 JSONArray size=new JSONArray();
                                 size.put(32);
                                 size.put(32);
                                 JSONArray anchor=new JSONArray();
                                 size.put(16);
                                 size.put(16);
                                 iconobj.put("iconSize",size);
                                 iconobj.put("iconAnchor", anchor);
                                         props.put("icon", iconobj);
                             }
                         if(styleobj.hatch!=null) {
                                 JSONObject hatch=cssLiteralToJSON(styleobj.hatch);
                                 props.put("hatch",hatch);
                         }
                         System.out.println(props);
                         return props.toString();
                 }
                 if(geometrytype.contains("Polygon")) {
                         JSONObject props=cssLiteralToJSON(styleobj.polygonStyle);
                         if(styleobj.polygonImage!=null) {
                         JSONObject iconobj=new JSONObject();
                         if(styleobj.polygonImage.contains("svg")) {
                                 iconobj.put("iconUrl", "url('data:image/svg+xml;utf8,"+styleobj.polygonImage+"')");
                         }else if(styleobj.polygonImage.contains("http")) {
                                 iconobj.put("iconUrl", styleobj.polygonImage);
                         }else {
                                 iconobj.put("iconUrl", styleobj.polygonImage);
                         }
                         JSONArray size=new JSONArray();
                         size.put(32);
                         size.put(32);
                         JSONArray anchor=new JSONArray();
                         size.put(16);
                         size.put(16);
                         iconobj.put("iconSize",size);
                         iconobj.put("iconAnchor", anchor);
                                 props.put("icon", iconobj);
                     }
                         if(styleobj.hatch!=null) {
                                 JSONObject hatch=cssLiteralToJSON(styleobj.hatch);
                                 props.put("hatch",hatch);
                         }
                         System.out.println(props);
                         return props.toString();
                 }
                 return "{}";
         }
formatHeader()
String formatHeader () inherited
{
                 return "";
         }
formatter()
String formatter (ResultSet results, String featuretype) throws XMLStreamException
{
                 // TODO Auto-generated method stub
                 return null;
         }
getFormatter()
static ResultStyleFormatter getFormatter (String formatString) static inherited
Gets a style formatter for a chosen style type.
Parameters
formatString the formatString indicating a given style type
Returns
a ResultStyleFormatter generating the chosen style type
References ResultStyleFormatter.formatter().
{
                 formatString=formatString.toLowerCase();
                 if(resultMap.containsKey(formatString)) {
                         return resultMap.get(formatString);
                 }
                 formatString=formatString.replace("+","");
                 if(formatString.contains("mapcss")) {
                         return resultMap.get("mapcss");
                 }
                 if(formatString.contains("geojsoncss")) {
                         return resultMap.get("geojsoncss");
                 }
                 if(formatString.contains("sld")) {
                         return resultMap.get("sld");
                 }
                 return null;
         }
Member Data Documentation
exposedType
String exposedType ="application/vnd.geo+json" inherited
Referenced by SLDFormatter.formatter().
lastQueriedElemCount
Integer lastQueriedElemCount =0 inherited
mimeType
String mimeType ="text/plain" inherited
resultMap
Map<String,ResultStyleFormatter> resultMap =new TreeMap<String, ResultStyleFormatter>() static inherited
styleAttribute
String styleAttribute ="" inherited
Referenced by GeoJSONFormatter.formatJSONObject(), GeoJSONFormatter.formatJSONStreaming(), GeoJSONCSSFormatter.GeoJSONCSSFormatter(), and SimpleStyleFormatter.SimpleStyleFormatter().