semanticwfs: UserManagementConnection Class Reference
UserManagementConnection Class Reference
Management class for user connections.
Classes
class UserHandler
SAXParser DefaultHandler für das Parsen von einem XML File mit den Benutzerdaten.
Public Member Functions
String addUser (String userToAdd, String userToAddPasswordHash, String userlevel) throws XMLStreamException, IOException
Adds a user to the set of users.
String updateUser (String userToAdd, String userToAddPasswordHash, String userlevel) throws XMLStreamException, IOException
String deleteUser (String userToAdd, String userToAddPasswordHash, Integer userlevel) throws XMLStreamException, IOException
User login (String username, String password)
User loginAuthToken (String authToken)
Performs a loging using an authentification token.
String usersToHTML ()
void toXML () throws XMLStreamException, IOException
Exports a user description to XML.
Static Public Member Functions
static UserManagementConnection getInstance ()
Gets the current instance of the UserManagementConnection.
Private Member Functions
UserManagementConnection ()
Constructor for this Singleton class.
String getHashedPassword (String password)
Generates a hashed password from a String for comparison.
void readUsers () throws ParserConfigurationException, SAXException
Private Attributes
Map< String, User > userNameToPasswordHash
Map< String, User > uuidToUser
Static Private Attributes
static UserManagementConnection instance
static String USERS ="users.xml"
Detailed Description
Management class for user connections.
Constructor & Destructor Documentation
UserManagementConnection()
UserManagementConnection () private
Constructor for this Singleton class.
References UserManagementConnection.readUsers().
Referenced by UserManagementConnection.getInstance().
{
                 this.userNameToPasswordHash=new TreeMap<String,User>();
                 this.uuidToUser=new TreeMap<String,User>();
                 try {
                         this.readUsers();
                 } catch (ParserConfigurationException | SAXException e) {
                         // TODO Auto-generated catch block
                         e.printStackTrace();
                 }
         }
Member Function Documentation
addUser()
String addUser (String userToAdd, String userToAddPasswordHash, String userlevel) throws XMLStreamException, IOException
Adds a user to the set of users.
Parameters
userToAdd The username of the new user
userToAddPasswordHash The password hash of the new user
userlevel The user level assigned to this user
Returns
A String confirming the user creation
Exceptions
XMLStreamException on error
IOException on error
References UserManagementConnection.getHashedPassword(), User.setName(), User.setPasswordHash(), User.setUserlevel(), and UserManagementConnection.toXML().
{
                 if(this.userNameToPasswordHash.containsKey(userToAdd)){
                         return "User already exists";
                 }
                 User user=new User();
                 user.setName(userToAdd);
                 user.setPasswordHash(this.getHashedPassword(userToAddPasswordHash));
                 user.setUserlevel(UserType.valueOf(userlevel));
                 this.userNameToPasswordHash.put(userToAdd, user);
                 this.toXML();
                 return "User successfully added";
         }
deleteUser()
String deleteUser (String userToAdd, String userToAddPasswordHash, Integer userlevel) throws XMLStreamException, IOException
References UserManagementConnection.toXML().
{
                 this.userNameToPasswordHash.remove(userToAdd);
                 this.toXML();
                 return "User successfully deleted";
         }
getHashedPassword()
String getHashedPassword (String password) private
Generates a hashed password from a String for comparison.
Parameters
password the password as plaintext
Returns
The hashed password as String
Referenced by UserManagementConnection.addUser(), UserManagementConnection.login(), and UserManagementConnection.updateUser().
{
                 try {
                 MessageDigest md = MessageDigest.getInstance("SHA-512");
                 byte[] messageDigest = md.digest(password.getBytes());
                 BigInteger number = new BigInteger(1, messageDigest);
                 String hashtext = number.toString(16);
                 // Now we need to zero pad it if you actually want the full 32 chars.
                 while (hashtext.length() < 32) {
                     hashtext = "0" + hashtext;
                 }
                 return hashtext;
             }catch (NoSuchAlgorithmException e) {
                 throw new RuntimeException(e);
             }
         }
getInstance()
static UserManagementConnection getInstance () static
Gets the current instance of the UserManagementConnection.
Returns
The instance
References UserManagementConnection.instance, and UserManagementConnection.UserManagementConnection().
Referenced by WebService.addEndpoint(), WebService.addFeatureType(), WebService.login(), and WebService.saveFeatureTypes().
{
                 if(instance==null){
                         instance=new UserManagementConnection();
                 }
                 return instance;
         }
login()
User login (String username, String password)
References UserManagementConnection.getHashedPassword(), and User.setUuid().
Referenced by WebService.login().
{
                 System.out.println("UserNameToPasswordHash: "+userNameToPasswordHash.toString());
                 if(!this.userNameToPasswordHash.containsKey(username)){
                         System.out.println("Not logged in: Username "+username+" does not exist! ");
                         return null;//"usernamenotex_false";
                 }
                 if(this.getHashedPassword(password).equals(this.userNameToPasswordHash.get(username).getPasswordHash())){
                         System.out.println("Logged in: "+this.userNameToPasswordHash.get(username).toString());
                         User user=this.userNameToPasswordHash.get(username);
                         user.setUuid(UUID.randomUUID().toString());
                         return this.userNameToPasswordHash.get(username);//"loginsuccessful_true";
                 }
                 System.out.println("Not logged in: Login failed! ");
                 return null;//"loginfailed_false";
         }
loginAuthToken()
User loginAuthToken (String authToken)
Performs a loging using an authentification token.
Parameters
authToken The authentification token
Returns
Referenced by WebService.addEndpoint(), WebService.addFeatureType(), and WebService.saveFeatureTypes().
{
                 System.out.println("UserNameToPasswordHash: "+userNameToPasswordHash.toString());
                 if(!this.uuidToUser.containsKey(authToken)){
                         System.out.println("Not logged in: Auth Token is invalid! ");
                         return this.uuidToUser.get(authToken);//"usernamenotex_false";
                 }
                 return null;
         }
readUsers()
void readUsers () throws ParserConfigurationException, SAXException private
Referenced by UserManagementConnection.UserManagementConnection().
{
                 SAXParser parser=SAXParserFactory.newInstance().newSAXParser();
                 try {
                         parser.parse(USERS, new UserHandler(this.userNameToPasswordHash,this.uuidToUser));
                 } catch (IOException e) {
                         // TODO Auto-generated catch block
                         e.printStackTrace();
                 }
         }
toXML()
void toXML () throws XMLStreamException, IOException
Exports a user description to XML.
Exceptions
XMLStreamException on streaming errors
IOException on writing errors
Referenced by UserManagementConnection.addUser(), UserManagementConnection.deleteUser(), and UserManagementConnection.updateUser().
{
                 StringWriter sw = new StringWriter();
             XMLOutputFactory xmlOutputFactory = XMLOutputFactory.newInstance();
             XMLStreamWriter xmlStreamWriter = xmlOutputFactory.createXMLStreamWriter(sw);
             xmlStreamWriter.writeStartDocument();
             xmlStreamWriter.writeStartElement("data");
             for(String name:userNameToPasswordHash.keySet()){
                 xmlStreamWriter.writeStartElement("user");
                 xmlStreamWriter.writeAttribute("name", name);
                 xmlStreamWriter.writeAttribute("password", userNameToPasswordHash.get(name).getPasswordHash());
                 xmlStreamWriter.writeAttribute("level", userNameToPasswordHash.get(name).getUserlevel().toString());
                 xmlStreamWriter.writeEndElement();
             }
             xmlStreamWriter.writeEndElement();
             xmlStreamWriter.writeEndDocument();
             xmlStreamWriter.flush();
             xmlStreamWriter.close();
             FileWriter writer=new FileWriter(new File(USERS));
             writer.write(sw.toString());
             writer.close();
         }
updateUser()
String updateUser (String userToAdd, String userToAddPasswordHash, String userlevel) throws XMLStreamException, IOException
References UserManagementConnection.getHashedPassword(), User.setName(), User.setPasswordHash(), User.setUserlevel(), and UserManagementConnection.toXML().
{
                 if(!this.userNameToPasswordHash.containsKey(userToAdd)){
                         return "User does not exist";
                 }
                 User user=new User();
                 user.setName(userToAdd);
                 user.setPasswordHash(this.getHashedPassword(userToAddPasswordHash));
                 user.setUserlevel(UserType.valueOf(userlevel));
                 this.userNameToPasswordHash.put(userToAdd, user);
                 this.toXML();
                 return "User successfully edited";
         }
usersToHTML()
String usersToHTML ()
References User.getName(), and User.getUserlevel().
{
                 StringBuilder result=new StringBuilder();
                 if(userNameToPasswordHash.isEmpty()){
                         return "<tr><td>No user available!</td></tr>";
                 }
                 for(String user:this.userNameToPasswordHash.keySet()){
                         User usr=this.userNameToPasswordHash.get(user);
                         result.append(usr.getName());
                         result.append(",");
                         result.append(usr.getUserlevel()+";");
                 }
                 return result.substring(0,result.length()-1).toString();
         }
Member Data Documentation
instance
UserManagementConnection instance static private
Referenced by UserManagementConnection.getInstance().
userNameToPasswordHash
Map<String,User> userNameToPasswordHash private
USERS
String USERS ="users.xml" static private
uuidToUser
Map<String,User> uuidToUser private