semanticwfs: KMLStyleFormatter Class Reference
KMLStyleFormatter Class Reference
Reads an ontological style description and formats it to KML Styles.
Public Member Functions
KMLStyleFormatter ()
Constructor for this class.
String formatter (ResultSet results, String featuretype) throws XMLStreamException
Map< String, String > cssLiteralToMap (String cssString)
Converts a CSS literal to a KML representation to include in a KML document.
void cssLiteralToKML (Map< String, String > cssMap, String geomtype, XMLStreamWriter writer) throws XMLStreamException
Converts a CSS literal which has been converted to a map to KML and appends it to the XML produced by the writer.
String formatGeometry (String geometrytype, StyleObject styleobj)
Formats a geometry according to a given geometrytype using information from a given styleobj.
String formatHeader ()
String formatFooter ()
Static Public Member Functions
static ResultStyleFormatter getFormatter (String formatString)
Gets a style formatter for a chosen style type.
Public Attributes
Map< String, Map< String, String > > tagMap
A map which includes tags which are relevant for specific geometry types.
Integer lastQueriedElemCount =0
String mimeType ="text/plain"
String exposedType ="application/vnd.geo+json"
String styleAttribute =""
Static Public Attributes
static Map< String, ResultStyleFormatter > resultMap =new TreeMap<String, ResultStyleFormatter>()
Static Package Functions
[static initializer]
Detailed Description
Reads an ontological style description and formats it to KML Styles.
Constructor & Destructor Documentation
KMLStyleFormatter()
KMLStyleFormatter ()
Constructor for this class.
{
                 this.tagMap=new TreeMap<>();
                 this.tagMap.put("Point",new TreeMap<String,String>());
                 this.tagMap.put("LineString",new TreeMap<String,String>());
                 this.tagMap.get("LineString").put("stroke","");
                 this.tagMap.get("LineString").put("stroke-width","width");
                 this.tagMap.put("Polygon",new TreeMap<String,String>());
                 this.tagMap.get("Polygon").put("stroke","");
                 this.tagMap.get("Polygon").put("stroke-width","width");
         }
Member Function Documentation
[static initializer]()
[static initializer] static package inherited
References ResultStyleFormatter.resultMap.
cssLiteralToKML()
void cssLiteralToKML (Map< String, String > cssMap, String geomtype, XMLStreamWriter writer) throws XMLStreamException
Converts a CSS literal which has been converted to a map to KML and appends it to the XML produced by the writer.
Parameters
cssMap the map of css statements
geomtype the geometry type to which the CSS style is applied
writer the XMLStreamWriter to write the results with
Exceptions
XMLStreamException when a XML writing error occurs
{
                 if(geomtype.equals("Polygon")) {
                         writer.writeStartElement("PolyStyle");
                         if(cssMap.containsKey("color")) {
                                 writer.writeStartElement("color");
                                 writer.writeCharacters(cssMap.get("color"));
                                 writer.writeEndElement();
                                 writer.writeStartElement("colorMode");
                                 writer.writeCharacters("normal");
                                 writer.writeEndElement();
                         }
                         if(cssMap.containsKey("fill")) {
                                 writer.writeStartElement("fill");
                                 writer.writeCharacters(cssMap.get("fill").replace("\\\"","").replace("^","").replace("http","").replace("true","1").replace("false","0").trim());
                                 writer.writeEndElement();
                         }
                         if(cssMap.containsKey("stroke")) {
                                 writer.writeStartElement("outline");
                                 writer.writeCharacters(cssMap.get("stroke").replace("\\\"","").replace("^","").replace("http","").replace("true","1").replace("false","0").trim());
                                 writer.writeEndElement();
                         }
                         writer.writeEndElement();
                 }else if(geomtype.equals("LineString")) {
                         writer.writeStartElement("LineStyle");
                         if(cssMap.containsKey("color")) {
                                 writer.writeStartElement("color");
                                 writer.writeCharacters(cssMap.get("color"));
                                 writer.writeEndElement();
                                 writer.writeStartElement("colorMode");
                                 writer.writeCharacters("normal");
                                 writer.writeEndElement();
                         }
                         if(cssMap.containsKey("stroke-width")) {
                                 writer.writeStartElement("width");
                                 writer.writeCharacters(cssMap.get("stroke-width"));
                                 writer.writeEndElement();
                         }
                         writer.writeEndElement();
                 }else if(geomtype.equals("Point")) {
                         if(cssMap.containsKey("color")) {
                                 writer.writeStartElement("color");
                                 writer.writeCharacters(cssMap.get("color"));
                                 writer.writeEndElement();
                                 writer.writeStartElement("colorMode");
                                 writer.writeCharacters("normal");
                                 writer.writeEndElement();
                         }
                         if(cssMap.containsKey("stroke-width")) {
                                 writer.writeStartElement("width");
                                 writer.writeCharacters(cssMap.get("stroke-width"));
                                 writer.writeEndElement();
                         }
                 }
         }
Referenced by KMLStyleFormatter.formatGeometry().
cssLiteralToMap()
Map<String,String> cssLiteralToMap (String cssString)
Converts a CSS literal to a KML representation to include in a KML document.
Parameters
cssString the css String contained in the literal
Returns
A map of style attributes to include into the KML representation.
{
                 Map<String,String> result=new TreeMap<String,String>();
                 if(cssString.contains(";")) {
                         for(String statement:cssString.split(";")) {
                                 String[] split=statement.split(":");
                                 if(!split[1].trim().isEmpty()) {
                                         String key=split[0].replace("\\\"","").trim();
                                         result.put(key,split[1].replace("\\\"","").replace("^","").replace("http","").replace("true","1").trim());
                                 }
                         }
                 }else if(cssString.contains(",")) {
                         for(String statement:cssString.split(",")) {
                                 String[] split=statement.split(":");
                                 if(!split[1].trim().isEmpty()) {
                                         String key=split[0].replace("\\\"","").trim();
                                         result.put(key,split[1].replace("\\\"","").replace("^","").replace("http","").replace("true","1").trim());
                                 }
                         }
                 }else {
                         String[] split=cssString.split(":");
                         if(!split[1].trim().isEmpty()) {
                                 String key=split[0].replace("\\\"","").trim();
                                 result.put(key,split[1].replace("\\\"","").replace("^","").replace("http","").replace("true","1").trim());
                         }
                 }
                 return result;
         }
Referenced by KMLStyleFormatter.formatGeometry().
formatFooter()
String formatFooter () inherited
{
                 return "";
         }
formatGeometry()
String formatGeometry (String geometrytype, StyleObject styleobj)
Formats a geometry according to a given geometrytype using information from a given styleobj.
Parameters
geometrytype the geometry
styleobj the styleobject to use for formatting
Returns
the formatString to use for styling
Reimplemented from ResultStyleFormatter.
{
                 if(styleobj==null)
                         return "";
                 System.out.println(geometrytype);
                 XMLOutputFactory factory = XMLOutputFactory.newInstance();
                 StringWriter strwriter=new StringWriter();
                 try {
                         XMLStreamWriter writer=new IndentingXMLStreamWriter(factory.createXMLStreamWriter(strwriter));
                         writer.flush();
                         if(geometrytype.contains("Point") && styleobj.pointStyle!=null && !styleobj.pointStyle.trim().isEmpty()) {
                                 writer.writeStartElement("IconStyle");
                                 writer.writeCharacters("");
                                 cssLiteralToKML(cssLiteralToMap(styleobj.pointStyle),"Point",writer);
                                 writer.writeStartElement("Icon");
                                 writer.writeStartElement("href");
                                 writer.writeCharacters(styleobj.pointImage);
                                 writer.writeEndElement();
                                 writer.writeEndElement();
                                 writer.writeEndElement();
                         }
                         if(geometrytype.contains("LineString") && styleobj.lineStringStyle!=null && !styleobj.lineStringStyle.trim().isEmpty()) {
                                 cssLiteralToKML(cssLiteralToMap(styleobj.lineStringStyle),"Point",writer);
                         }
                         if(geometrytype.contains("Polygon")  && styleobj.polygonStyle!=null && !styleobj.polygonStyle.trim().isEmpty()) {
                                 cssLiteralToKML(cssLiteralToMap(styleobj.polygonStyle),"Point",writer);
                         }
                 } catch (XMLStreamException e) {
                         // TODO Auto-generated catch block
                         e.printStackTrace();
                 }
                 return strwriter.toString();
         }
References KMLStyleFormatter.cssLiteralToKML(), KMLStyleFormatter.cssLiteralToMap(), StyleObject.lineStringStyle, StyleObject.pointImage, StyleObject.pointStyle, and StyleObject.polygonStyle.
formatHeader()
String formatHeader () inherited
{
                 return "";
         }
formatter()
String formatter (ResultSet results, String featuretype) throws XMLStreamException
Parameters
results
featuretype
Returns
Exceptions
XMLStreamException
Reimplemented from ResultStyleFormatter.
{
                 // TODO Auto-generated method stub
                 return null;
         }
getFormatter()
static ResultStyleFormatter getFormatter (String formatString) static inherited
Gets a style formatter for a chosen style type.
Parameters
formatString the formatString indicating a given style type
Returns
a ResultStyleFormatter generating the chosen style type
{
                 formatString=formatString.toLowerCase();
                 if(resultMap.containsKey(formatString)) {
                         return resultMap.get(formatString);
                 }
                 formatString=formatString.replace("+","");
                 if(formatString.contains("mapcss")) {
                         return resultMap.get("mapcss");
                 }
                 if(formatString.contains("geojsoncss")) {
                         return resultMap.get("geojsoncss");
                 }
                 if(formatString.contains("sld")) {
                         return resultMap.get("sld");
                 }
                 return null;
         }
Member Data Documentation
exposedType
String exposedType ="application/vnd.geo+json" inherited
Referenced by SLDFormatter.formatter().
lastQueriedElemCount
Integer lastQueriedElemCount =0 inherited
mimeType
String mimeType ="text/plain" inherited
resultMap
Map<String,ResultStyleFormatter> resultMap =new TreeMap<String, ResultStyleFormatter>() static inherited
Referenced by ResultStyleFormatter.[static initializer]().
styleAttribute
String styleAttribute ="" inherited
Referenced by GeoJSONFormatter.formatJSONObject(), GeoJSONFormatter.formatJSONStreaming(), GeoJSONCSSFormatter.GeoJSONCSSFormatter(), and SimpleStyleFormatter.SimpleStyleFormatter().
tagMap
Map<String,Map<String,String> > tagMap
A map which includes tags which are relevant for specific geometry types.