semanticwfs: ResultMetadataFormatter Class Reference
ResultMetadataFormatter Class Reference abstract
Public Member Functions
abstract String formatter (String collectionid, String collectioncall, String collectionurl, JSONObject workingobj, String format) throws XMLStreamException
String formatHeader ()
String formatFooter ()
Static Public Member Functions
static ResultMetadataFormatter getFormatter (String formatString)
Public Attributes
Integer lastQueriedElemCount =0
String mimeType ="text/plain"
String exposedType ="application/vnd.geo+json"
XMLStreamWriter xmlwriter
Static Public Attributes
static Map< String, ResultMetadataFormatter > resultMap =new TreeMap<String, ResultMetadataFormatter>()
Static Package Functions
[static initializer]
Member Function Documentation
[static initializer]()
[static initializer] static package
References ResultMetadataFormatter.resultMap.
formatFooter()
String formatFooter ()
{
                 return "";
         }
formatHeader()
String formatHeader ()
{
                 return "";
         }
formatter()
abstract String formatter (String collectionid, String collectioncall, String collectionurl, JSONObject workingobj, String format) throws XMLStreamException abstract
Reimplemented in GMDFormatter, and DCATFormatter.
Referenced by WebService.getCollectionMetadata().
getFormatter()
static ResultMetadataFormatter getFormatter (String formatString) static
{
                 formatString=formatString.toLowerCase();
                 if(resultMap.containsKey(formatString)) {
                         return resultMap.get(formatString);
                 }
                 formatString=formatString.replace("+","");
                 if(formatString.contains("dcat")) {
                         return resultMap.get("geodcat");
                 }
                 return resultMap.get("gmd");
         }
Referenced by WebService.getCollectionMetadata().
Member Data Documentation
exposedType
String exposedType ="application/vnd.geo+json"
lastQueriedElemCount
Integer lastQueriedElemCount =0
mimeType
String mimeType ="text/plain"
Referenced by DCATFormatter.formatter(), WebService.getCollectionMetadata(), and GMDFormatter.GMDFormatter().
resultMap
Map<String,ResultMetadataFormatter> resultMap =new TreeMap<String, ResultMetadataFormatter>() static
Referenced by ResultMetadataFormatter.[static initializer]().
xmlwriter
XMLStreamWriter xmlwriter
Referenced by GMDFormatter.formatter().