semanticwfs: SLDFormatter Class Reference
SLDFormatter Class Reference
Formats styles according to the styled layer description definition.
Public Member Functions
String formatter (ResultSet results, String featuretype) throws XMLStreamException
void cssLiteralToXML (XMLStreamWriter writer, String cssString)
Formats a cssliteral to an XML representation as needed by SLD.
String formatGeometry (String geometrytype, StyleObject style)
Formats a geometry according to a given geometrytype using information from a given styleobj.
String formatHeader ()
String formatFooter ()
Static Public Member Functions
static ResultStyleFormatter getFormatter (String formatString)
Gets a style formatter for a chosen style type.
Public Attributes
Integer lastQueriedElemCount =0
String mimeType ="text/plain"
String exposedType ="application/vnd.geo+json"
String styleAttribute =""
Static Public Attributes
static Map< String, ResultStyleFormatter > resultMap =new TreeMap<String, ResultStyleFormatter>()
Static Package Functions
[static initializer]
Detailed Description
Formats styles according to the styled layer description definition.
Member Function Documentation
[static initializer]()
[static initializer] static package inherited
References ResultStyleFormatter.resultMap.
cssLiteralToXML()
void cssLiteralToXML (XMLStreamWriter writer, String cssString)
Formats a cssliteral to an XML representation as needed by SLD.
Parameters
writer the XMLWriter to use
cssString a String containing CSS definitions
{
                 Map<String,Map<String,String>> treemap=new TreeMap<>();
                 treemap.put("Fill",new TreeMap<>());
                 treemap.put("Stroke",new TreeMap<>());
                 if(cssString.contains(";")) {
                         for(String statement:cssString.split(";")) {
                                 String[] split=statement.split(":");
                                 if(split[0].contains("stroke")) {
                                         treemap.get("Stroke").put(split[0],split[1]);
                                 }else if(split[0].contains("fill")) {
                                         treemap.get("Fill").put(split[0],split[1]);
                                 }
                         }
                         for(String key:treemap.keySet()) {
                                 try {
                                         writer.writeStartElement("sld:"+key);
                                         for(String keyy:treemap.get(key).keySet()) {
                                                 writer.writeStartElement("sld:CssParameter");
                                                 writer.writeAttribute("name", keyy);
                                                 writer.writeStartElement("ogc:Literal");
                                                 writer.writeCharacters(treemap.get(key).get(keyy));
                                                 writer.writeEndElement();
                                                 writer.writeEndElement();
                                         }
                                         writer.writeEndElement();
                                 } catch (XMLStreamException e) {
                                         // TODO Auto-generated catch block
                                         e.printStackTrace();
                                 }
                         }
                 }
         }
Referenced by SLDFormatter.formatter().
formatFooter()
String formatFooter () inherited
{
                 return "";
         }
formatGeometry()
String formatGeometry (String geometrytype, StyleObject styleobj)
Formats a geometry according to a given geometrytype using information from a given styleobj.
Parameters
geometrytype the geometry
styleobj the styleobject to use for formatting
Returns
the formatString to use for styling
Reimplemented from ResultStyleFormatter.
{
                 // TODO Auto-generated method stub
                 return null;
         }
formatHeader()
String formatHeader () inherited
{
                 return "";
         }
formatter()
String formatter (ResultSet results, String featuretype) throws XMLStreamException
Parameters
results
featuretype
Returns
Exceptions
XMLStreamException
Reimplemented from ResultStyleFormatter.
{
                 StringWriter strwriter = new StringWriter();
                 XMLOutputFactory output = XMLOutputFactory.newInstance();
                 XMLStreamWriter writer;
                         writer = new IndentingXMLStreamWriter(output.createXMLStreamWriter(strwriter));
                         writer.writeStartDocument();
                         writer.writeAttribute("xmlns", "http://www.opengis.net/ogcapi-features-1/1.0");
                         writer.writeAttribute("xmlns:sld", "http://www.opengis.net/sld");
                         writer.writeAttribute("xmlns:ogc", "http://www.opengis.net/ogc");
                         writer.writeAttribute("xmlns:xlink", "http://www.w3.org/1999/xlink");
                         writer.writeAttribute("xmlns:gml", "http://www.opengis.net/gml");
                         writer.writeAttribute("xmlns:xsi","http://www.w3.org/1999/xlink");
                         writer.writeAttribute("version","1.0.0");
                         writer.writeStartElement("sld:UserStyle");
                         writer.writeStartElement("sld:Name");
                         writer.writeCharacters(featuretype+" Style");
                         writer.writeEndElement();
                         writer.writeStartElement("sld:Title");
                         writer.writeCharacters(featuretype+" Style");
                         writer.writeEndElement();
                         writer.writeStartElement("sld:Abstract");
                         writer.writeCharacters("");
                         writer.writeEndElement();
                         writer.writeStartElement("sld:IsDefault");
                         writer.writeCharacters("1");
                         writer.writeEndElement();
                         writer.writeStartElement("sld:FeatureTypeStyle");
                         writer.writeStartElement("sld:Name");
                         writer.writeEndElement();
                         writer.writeStartElement("sld:Title");
                         writer.writeEndElement();
                         writer.writeStartElement("sld:Abstract");
                         writer.writeEndElement();
                         writer.writeStartElement("sld:FeatureTypeName");
                         writer.writeCharacters(featuretype);
                         writer.writeEndElement();
                         writer.writeStartElement("sld:SemanticTypeIdentifier");
                         writer.writeCharacters("generic:geometry");
                         writer.writeEndElement();
                         writer.writeStartElement("sld:Rule");
                         writer.writeStartElement("sld:PolygonSymbolizer");
                         cssLiteralToXML(writer, "");
                         writer.writeEndElement();
                         writer.writeEndElement();
                         writer.writeEndElement();
                         return exposedType;
         }
References SLDFormatter.cssLiteralToXML(), and ResultStyleFormatter.exposedType.
getFormatter()
static ResultStyleFormatter getFormatter (String formatString) static inherited
Gets a style formatter for a chosen style type.
Parameters
formatString the formatString indicating a given style type
Returns
a ResultStyleFormatter generating the chosen style type
{
                 formatString=formatString.toLowerCase();
                 if(resultMap.containsKey(formatString)) {
                         return resultMap.get(formatString);
                 }
                 formatString=formatString.replace("+","");
                 if(formatString.contains("mapcss")) {
                         return resultMap.get("mapcss");
                 }
                 if(formatString.contains("geojsoncss")) {
                         return resultMap.get("geojsoncss");
                 }
                 if(formatString.contains("sld")) {
                         return resultMap.get("sld");
                 }
                 return null;
         }
Member Data Documentation
exposedType
String exposedType ="application/vnd.geo+json" inherited
Referenced by SLDFormatter.formatter().
lastQueriedElemCount
Integer lastQueriedElemCount =0 inherited
mimeType
String mimeType ="text/plain" inherited
resultMap
Map<String,ResultStyleFormatter> resultMap =new TreeMap<String, ResultStyleFormatter>() static inherited
Referenced by ResultStyleFormatter.[static initializer]().
styleAttribute
String styleAttribute ="" inherited
Referenced by GeoJSONFormatter.formatJSONObject(), GeoJSONFormatter.formatJSONStreaming(), GeoJSONCSSFormatter.GeoJSONCSSFormatter(), and SimpleStyleFormatter.SimpleStyleFormatter().