semanticwfs: UserType Enum Reference
UserType Enum Reference
Enumeration type including user levels which may be applied in the SemanticWFS.
Public Member Functions
String getUserTypeString ()
Gets the String representation of the user type.
String toString ()
Public Attributes
Administrator =("administrator")
Administrator role.
Configurer =("configurer")
Configurer role.
User =("user")
User role.
Private Member Functions
UserType (String userTypeString)
Constructor for this class.
Private Attributes
final String userTypeString
Detailed Description
Enumeration type including user levels which may be applied in the SemanticWFS.
Constructor & Destructor Documentation
UserType()
UserType (String userTypeString) private
Constructor for this class.
Parameters
userTypeString The String indicating the usertype to be assigned
{
                 this.userTypeString=userTypeString;
         }
Member Function Documentation
getUserTypeString()
String getUserTypeString ()
Gets the String representation of the user type.
Returns
The String representation
{
                 return userTypeString;
         }
toString()
String toString ()
Referenced by User.User().
{
                 return userTypeString;
         }
Member Data Documentation
Administrator
Administrator =("administrator")
Administrator role.
Referenced by WebService.addEndpoint(), WebService.addFeatureType(), and WebService.saveFeatureTypes().
Configurer
Configurer =("configurer")
Configurer role.
Referenced by WebService.addEndpoint(), WebService.addFeatureType(), and WebService.saveFeatureTypes().
User
User =("user")
User role.
userTypeString
final String userTypeString private