semanticwfs: WebService Class Reference
WebService Class Reference
Implements OGC API Features and WFS webservice functionality.
Public Member Functions
WebService () throws IOException
Constructor for this class.
Response openapiJSON ()
Response openapiYAML ()
void generateOpenAPIDefinitions ()
Generates OpenAPI definitions of the SemanticWFS services for the use with OGC API Features.
Response createExceptionResponse (Exception e, String format)
Generates an exception response.
Response entryPointPOST (@Parameter(description="Service type definition") @DefaultValue("WFS") @QueryParam("SERVICE") String service, @Parameter(description="Request definition") @DefaultValue("GetCapabilities") @QueryParam("REQUEST") String request, @Parameter(description="Version of the web service") @DefaultValue("2.0.0") @QueryParam("VERSION") String version, @Parameter(description="The feature type name to be queried") @DefaultValue("") @QueryParam("TYPENAME") String typename, @Parameter(description="The feature type(s) name(s) to be queried") @DefaultValue("") @QueryParam("TYPENAMES") String typenames, @Parameter(description="The name of the CRS to be returned") @DefaultValue("") @QueryParam("SRSNAME") String srsName, @DefaultValue("gml") @QueryParam("EXCEPTIONS") String exceptions, @Parameter(description="A bounding box used for filtering results") @DefaultValue("") @QueryParam("BBOX") String bbox, @DefaultValue("") @QueryParam("VALUEREFERENCE") String propertyname, @Parameter(description="Sorting order definition") @DefaultValue("ASC") @QueryParam("SORTBY") String sortBy, @DefaultValue("") @QueryParam("STYLES") String style, @DefaultValue("results") @QueryParam("RESULTTYPE") String resultType, @DefaultValue("") @QueryParam("RESOURCEID") String resourceids, @DefaultValue("") @QueryParam("GMLOBJECTID") String gmlobjectid, @DefaultValue("0") @QueryParam("STARTINDEX") String startindex, @DefaultValue("") @QueryParam("FILTER") String filter, @DefaultValue("") @QueryParam("FILTERLANGUAGE") String filterLanguage, @DefaultValue("gml") @QueryParam("OUTPUTFORMAT") String output, @DefaultValue("5") @QueryParam("COUNT") String count)
Entrypoint implementation for OGC API Features for POST requests.
Response vectorTiles (@DefaultValue("CSW") @QueryParam("SERVICE") String service, @DefaultValue("GetCapabilities") @QueryParam("REQUEST") String request, @DefaultValue("2.0.2") @QueryParam("VERSION") String version, @DefaultValue("") @QueryParam("TYPENAME") String typename, @DefaultValue("") @QueryParam("TYPENAMES") String typenames, @DefaultValue("gml") @QueryParam("OUTPUTFORMAT") String output)
Returns a vector tile representation of a given feature type.
Response style (@Parameter(description="The service type which is addressed") @DefaultValue("WFS") @QueryParam("SERVICE") String service, @Parameter(description="Request type of this query") @DefaultValue("GetStyle") @QueryParam("REQUEST") String request, @Parameter(description="Feature type names") @DefaultValue("") @QueryParam("TYPENAME") String typename, @Parameter(description="Feature type names") @DefaultValue("") @QueryParam("TYPENAMES") String typenames, @Parameter(description="Outputformat of the style which is returned") @DefaultValue("gml") @QueryParam("OUTPUTFORMAT") String output)
Returns a style information in a given format for a given featuretype and styleid.
Response getCollectionStyle (@Parameter(description="Feature type name") @PathParam("collectionid") String collectionid, @Parameter(description="Style id") @PathParam("styleid") String styleid, @Parameter(description="Return format") @DefaultValue("html") @QueryParam("f") String format)
Gets a style for a given featuretype with a given style identifier.
Response getCollectionStyles (@Parameter(description="Feature type name") @PathParam("collectionid") String collectionid, @Parameter(description="Return type") @DefaultValue("html") @QueryParam("f") String format)
Gets a list of all styles for a given featuretype.
Response entryPointCSW (@Parameter(description="Service type") @DefaultValue("CSW") @QueryParam("SERVICE") String service, @Parameter(description="Request type") @DefaultValue("GetCapabilities") @QueryParam("REQUEST") String request, @Parameter(description="Version of the webservice") @DefaultValue("2.0.2") @QueryParam("VERSION") String version, @Parameter(description="Feature type names") @DefaultValue("") @QueryParam("TYPENAME") String typename, @Parameter(description="Feature type names") @DefaultValue("") @QueryParam("TYPENAMES") String typenames, @Parameter(description="Return type") @DefaultValue("gml") @QueryParam("OUTPUTFORMAT") String output)
CSW endpoint implementation.
Response entryPointCSWPost (@DefaultValue("CSW") @QueryParam("SERVICE") String service, @DefaultValue("GetCapabilities") @QueryParam("REQUEST") String request, @DefaultValue("2.0.2") @QueryParam("VERSION") String version, @DefaultValue("") @QueryParam("TYPENAME") String typename, @DefaultValue("") @QueryParam("TYPENAMES") String typenames, @DefaultValue("gml") @QueryParam("OUTPUTFORMAT") String output)
CSW endpoint implementation (POST version).
Response entryPoint (@Parameter(description="Service type") @DefaultValue("WFS") @QueryParam("SERVICE") String service, @Parameter(description="Request type") @DefaultValue("GetCapabilities") @QueryParam("REQUEST") String request, @Parameter(description="Service version") @DefaultValue("2.0.0") @QueryParam("VERSION") String version, @Parameter(description="Feature type names") @DefaultValue("") @QueryParam("TYPENAME") String typename, @Parameter(description="Feature type names") @DefaultValue("") @QueryParam("TYPENAMES") String typenames, @Parameter(description="CRS type") @DefaultValue("") @QueryParam("SRSNAME") String srsName, @DefaultValue("gml") @QueryParam("EXCEPTIONS") String exceptions, @Parameter(description="Bounding box for filtering the results") @DefaultValue("") @QueryParam("BBOX") String bbox, @DefaultValue("") @QueryParam("VALUEREFERENCE") String propertyname, @Parameter(description="Sorting order") @DefaultValue("ASC") @QueryParam("SORTBY") String sortBy, @DefaultValue("") @QueryParam("STYLES") String style, @DefaultValue("results") @QueryParam("RESULTTYPE") String resultType, @DefaultValue("") @QueryParam("RESOURCEID") String resourceids, @DefaultValue("") @QueryParam("GMLOBJECTID") String gmlobjectid, @DefaultValue("0") @QueryParam("STARTINDEX") String startindex, @Parameter(description="Filter expression") @DefaultValue("") @QueryParam("FILTER") String filter, @Parameter(description="Filter query language") @DefaultValue("") @QueryParam("FILTERLANGUAGE") String filterLanguage, @Parameter(description="Return format") @DefaultValue("gml") @QueryParam("OUTPUTFORMAT") String output, @Parameter(description="Maximum amount of results to return") @DefaultValue("5") @QueryParam("COUNT") String count)
WFS endpoint implementation.
Response docJSON (@Parameter(description="Return format") @DefaultValue("json") @QueryParam("f") String format)
Response collectionsJSON (@Parameter(description="Return format") @DefaultValue("json") @QueryParam("f") String format)
Response collectionsXML (@Parameter(description="Return format") @DefaultValue("xml") @QueryParam("f") String format)
Response collectionsHTML (@Parameter(description="Return format") @DefaultValue("html") @QueryParam("f") String format)
Response collections (@Parameter(description="Return format", style=ParameterStyle.FORM) @DefaultValue("html") @QueryParam("f") String format)
Returns a list of feature types/collections.
Response getFeatureByIdJSON (@Parameter(description="The collection id") @PathParam("collectionid") String collectionid, @Parameter(description="The feature id") @PathParam("featureid") String featureid, @Parameter(description="The style to be applied") @DefaultValue("") @QueryParam("mapstyle") String style, @Parameter(description="The format to be returned") @DefaultValue("json") @QueryParam("f") String format)
Returns a feature given its feature id.
Response getFeatureByIdXML (@Parameter(description="The collection id") @PathParam("collectionid") String collectionid, @Parameter(description="The feature id") @PathParam("featureid") String featureid, @Parameter(description="The style to be applied") @DefaultValue("") @QueryParam("mapstyle") String style, @Parameter(description="The format to be returned") @DefaultValue("gml") @QueryParam("f") String format)
Returns a feature given its feature id.
Response docCollectionItemJSON (@Parameter(description="The id of the collection to be considered") @PathParam("collectionid") String collectionid, @Parameter(description="The id of the feature to be considered") @PathParam("ext") String ext, @Parameter(description="The id of the feature to be considered") @PathParam("featureid") String featureid, @Parameter(description="The format in which the collection should be returned", example="geojson") @DefaultValue("ldapi") @QueryParam("_format") String format, @Parameter(description="The maximum amount of features to be returned", example="10") @DefaultValue("10") @QueryParam("_pageSize") Integer limit, @Parameter(description="An optional where statement to be used in the SPARQL query", example="10") @DefaultValue("") @QueryParam("_select") String select, @Parameter(description="An optional where statement to be used in the SPARQL query", example="10") @DefaultValue("") @QueryParam("_where") String where, @Parameter(description="The page of the Linked Data API resource to return", example="1") @DefaultValue("1") @QueryParam("_page") Integer page, @Parameter(description="Detailed or minimized view to be returned") @DefaultValue("") @QueryParam("_view") String view, @Parameter(description="The sorting of the given results") @DefaultValue("") @QueryParam("_sort") String sort, @Parameter(description="An optional orderBy statement to be used in the SPARQL query") @DefaultValue("") @QueryParam("_orderBy") String orderBy, @Parameter(description="A subclass definition of the class defining the featurecollection") @DefaultValue("") @QueryParam("type") String type, @Parameter(description="Defines resources with a specified parameter value to be returned") @DefaultValue("") @QueryParam("param") List< String > paramval, @Parameter(description="Defines resources with a specified parameter value greater or equal the given value to be returned") @DefaultValue("") @QueryParam("max-param") String maxparamval, @Parameter(description="Defines resources with a specified parameter value smaller or equal the given value to be returned") @DefaultValue("") @QueryParam("min-param") String minparamval, @Parameter(description="Defines resources with a specified parameter value greater than the given value to be returned") @DefaultValue("") @QueryParam("maxEx-param") String maxExparamval, @Parameter(description="Defines resources with a specified parameter value smaller than the given value to be returned") @DefaultValue("") @QueryParam("minEx-param") String minExparamval, @Parameter(description="Returns only resources with the specified parameter") @QueryParam("exists-param") String existsparam, @Parameter(description="An offset to be considered when returning features", example="10") @DefaultValue("0") @QueryParam("offset") String offset)
Response getFeatureByIdHTML (@Parameter(description="The collection id") @PathParam("collectionid") String collectionid, @Parameter(description="The feature id") @PathParam("featureid") String featureid, @Parameter(description="The style to be applied") @DefaultValue("") @QueryParam("mapstyle") String style, @Parameter(description="The format to be returned") @DefaultValue("html") @QueryParam("f") String format)
Returns a feature given its feature id.
Response getFeatureById (@Parameter(description="The collection id") @PathParam("collectionid") String collectionid, @Parameter(description="The feature id") @PathParam("featureid") String featureid, @Parameter(description="The style to be applied") @DefaultValue("") @QueryParam("style") String style, @Parameter(description="The format to be returned") @DefaultValue("html") @QueryParam("f") String format)
Returns a feature given its feature id.
Response queryables (@Parameter(description="The id of the collection to be considered") @PathParam("collectionid") String collectionid, @Parameter(description="The format in which the collection should be returned", example="geojson") @DefaultValue("html") @QueryParam("f") String format)
Returns information about the queryables of ths given feature type.
Response landingPageHTML (@Parameter(description="The format of the landingpage") @DefaultValue("html") @QueryParam("f") String format)
Response landingPageJSON (@Parameter(description="The format of the landingpage") @DefaultValue("json") @QueryParam("f") String format)
Response landingPageXML (@Parameter(description="The format of the landingpage") @DefaultValue("xml") @QueryParam("f") String format)
Response landingPage (@Parameter(description="The format of the landingpage") @DefaultValue("html") @QueryParam("f") String format)
Returns the landing page of the OGC API Features service.
Response getCollectionsMetadata (@Parameter(description="The format of the collection page") @DefaultValue("html") @QueryParam("f") String format)
Returns the metadata of collections registered in the SemanticWFS.
Response getCollectionMetadata (@PathParam("collectionid") String collectionid, @Parameter(description="The metadata schema to be used") @DefaultValue("gmd") @QueryParam("metadataformat") String mdformat, @Parameter(description="The format to downlift metadata") @DefaultValue("html") @QueryParam("f") String format, @DefaultValue("false") @QueryParam("collectioncall") String collectioncall)
Gets metadata of a given collection.
Response collectionInformationJSON (@Parameter(description="The id of the collection to be considered") @PathParam("collectionid") String collectionid, @Parameter(description="The format in which the collection should be returned", example="geojson") @DefaultValue("json") @QueryParam("f") String format, @Parameter(description="The maximum amount of features to be returned", example="10") @DefaultValue("10") @QueryParam("limit") String limit, @Parameter(description="An offset to be considered when returning features", example="10") @DefaultValue("0") @QueryParam("offset") String offset, @Parameter(description="Defines a bounding box from which to return the given features") @QueryParam("bbox") String bbox)
Response collectionInformationXML (@Parameter(description="The id of the collection to be considered") @PathParam("collectionid") String collectionid, @Parameter(description="The format in which the collection should be returned", example="geojson") @DefaultValue("xml") @QueryParam("f") String format, @Parameter(description="The maximum amount of features to be returned", example="10") @DefaultValue("10") @QueryParam("limit") String limit, @Parameter(description="An offset to be considered when returning features", example="10") @DefaultValue("0") @QueryParam("offset") String offset, @Parameter(description="Defines a bounding box from which to return the given features") @QueryParam("bbox") String bbox)
Response collectionInformationHTML (@Parameter(description="The id of the collection to be considered") @PathParam("collectionid") String collectionid, @Parameter(description="The format in which the collection should be returned", example="geojson") @DefaultValue("html") @QueryParam("f") String format, @Parameter(description="The maximum amount of features to be returned", example="10") @DefaultValue("10") @QueryParam("limit") String limit, @Parameter(description="An offset to be considered when returning features", example="10") @DefaultValue("0") @QueryParam("offset") String offset, @Parameter(description="Defines a bounding box from which to return the given features") @QueryParam("bbox") String bbox)
Response docCollectionJSON (@Parameter(description="The id of the collection to be considered") @PathParam("collectionid") String collectionid, @Parameter(description="The format if given as a file extension") @DefaultValue("") @PathParam("ext") String ext, @Parameter(description="The format in which the collection should be returned", example="ttl") @DefaultValue("ldapi") @QueryParam("_format") String format, @Parameter(description="The maximum amount of features to be returned", example="10") @DefaultValue("10") @QueryParam("_pageSize") Integer limit, @Parameter(description="An optional where statement to be used in the SPARQL query", example="10") @DefaultValue("") @QueryParam("_select") String select, @Parameter(description="An optional where statement to be used in the SPARQL query", example="10") @DefaultValue("") @QueryParam("_where") String where, @Parameter(description="The page of the Linked Data API resource to return", example="1") @DefaultValue("1") @QueryParam("_page") Integer page, @Parameter(description="Detailed or minimized view to be returned") @DefaultValue("") @QueryParam("_view") String view, @Parameter(description="The sorting of the given results") @DefaultValue("") @QueryParam("_sort") String sort, @Parameter(description="An optional orderBy statement to be used in the SPARQL query") @DefaultValue("") @QueryParam("_orderBy") String orderBy, @Parameter(description="A subclass definition of the class defining the featurecollection") @DefaultValue("") @QueryParam("type") String type, @Parameter(description="Defines resources with a specified parameter value to be returned") @DefaultValue("") @QueryParam("param") List< String > paramval, @Parameter(description="Defines resources with a specified parameter value greater or equal the given value to be returned") @DefaultValue("") @QueryParam("max-param") String maxparamval, @Parameter(description="Defines resources with a specified parameter value smaller or equal the given value to be returned") @DefaultValue("") @QueryParam("min-param") String minparamval, @Parameter(description="Defines resources with a specified parameter value greater than the given value to be returned") @DefaultValue("") @QueryParam("maxEx-param") String maxExparamval, @Parameter(description="Defines resources with a specified parameter value smaller than the given value to be returned") @DefaultValue("") @QueryParam("minEx-param") String minExparamval, @Parameter(description="Returns only resources with the specified parameter") @QueryParam("exists-param") String existsparam, @Parameter(description="An offset to be considered when returning features", example="10") @DefaultValue("0") @QueryParam("offset") Integer offset)
Response collectionInformation (@Parameter(description="The id of the collection to be considered") @PathParam("collectionid") String collectionid, @Parameter(description="The format in which the collection should be returned", example="geojson") @DefaultValue("html") @QueryParam("f") String format, @Parameter(description="The maximum amount of features to be returned", example="10") @DefaultValue("10") @QueryParam("limit") String limit, @Parameter(description="An offset to be considered when returning features", example="10") @DefaultValue("0") @QueryParam("offset") String offset, @Parameter(description="Defines a bounding box from which to return the given features") @QueryParam("bbox") String bbox)
Returns a given collection description or parts of it.
Response getSchema (@Parameter(description="The collection id for which to return the schema") @PathParam("collectionid") String collectionid, @Parameter(description="The format in which the schema should be returned", example="json") @DefaultValue("gml") @QueryParam("f") String format)
Returns a schema of a given collection.
Response collectionItemsJSON (@Context HttpHeaders headers, @Parameter(description="The id of the collection") @PathParam("collectionid") String collectionid, @Parameter(description="The format of the result") @DefaultValue("json") @QueryParam("f") String format, @Parameter(description="The query limit", style=ParameterStyle.FORM) @DefaultValue("10") @QueryParam("limit") Integer limit, @Parameter(description="The offset to consider when fetching items") @DefaultValue("0") @QueryParam("offset") Integer offset, @Parameter(description="A bounding box", style=ParameterStyle.FORM) @DefaultValue("") @QueryParam("bbox") String bbox, @Parameter(description="The styling of the item when returned") @DefaultValue("") @QueryParam("style") String style, @Parameter(description="The crs of the data to be returned") @DefaultValue("EPSG:4326") @QueryParam("crs") String crs, @Parameter(description="The crs of a given bounding box") @DefaultValue("") @QueryParam("bbox-crs") String bboxcrs, @Parameter(description="A filter expression") @DefaultValue("") @QueryParam("filter") String filter, @Parameter(description="The language in which the filter expression is formulated") @DefaultValue("") @QueryParam("filter-lang") String filterlang, @Parameter(description="A temporal filter expression") @DefaultValue("") @QueryParam("datetime") String datetime)
Response collectionItemsXML (@Context HttpHeaders headers, @Parameter(description="The id of the collection") @PathParam("collectionid") String collectionid, @Parameter(description="The format of the result") @DefaultValue("gml") @QueryParam("f") String format, @Parameter(description="The query limit", style=ParameterStyle.FORM) @DefaultValue("10") @QueryParam("limit") Integer limit, @Parameter(description="The offset to consider when fetching items") @DefaultValue("0") @QueryParam("offset") Integer offset, @Parameter(description="A bounding box", style=ParameterStyle.FORM) @DefaultValue("") @QueryParam("bbox") String bbox, @Parameter(description="The styling of the item when returned") @DefaultValue("") @QueryParam("style") String style, @Parameter(description="The crs of the data to be returned") @DefaultValue("EPSG:4326") @QueryParam("crs") String crs, @Parameter(description="The crs of a given bounding box") @DefaultValue("") @QueryParam("bbox-crs") String bboxcrs, @Parameter(description="A filter expression") @DefaultValue("") @QueryParam("filter") String filter, @Parameter(description="The language in which the filter expression is formulated") @DefaultValue("") @QueryParam("filter-lang") String filterlang, @Parameter(description="A temporal filter expression") @DefaultValue("") @QueryParam("datetime") String datetime)
Response collectionItemsHTML (@Context HttpHeaders headers, @Parameter(description="The id of the collection") @PathParam("collectionid") String collectionid, @Parameter(description="The format of the result") @DefaultValue("html") @QueryParam("f") String format, @Parameter(description="The query limit", style=ParameterStyle.FORM) @DefaultValue("10") @QueryParam("limit") Integer limit, @Parameter(description="The offset to consider when fetching items") @DefaultValue("0") @QueryParam("offset") Integer offset, @Parameter(description="A bounding box", style=ParameterStyle.FORM) @DefaultValue("") @QueryParam("bbox") String bbox, @Parameter(description="The styling of the item when returned") @DefaultValue("") @QueryParam("style") String style, @Parameter(description="The crs of the data to be returned") @DefaultValue("") @QueryParam("crs") String crs, @Parameter(description="The crs of a given bounding box") @DefaultValue("") @QueryParam("bbox-crs") String bboxcrs, @Parameter(description="A filter expression") @DefaultValue("") @QueryParam("filter") String filter, @Parameter(description="The language in which the filter expression is formulated") @DefaultValue("") @QueryParam("filter-lang") String filterlang, @Parameter(description="A temporal filter expression") @DefaultValue("") @QueryParam("datetime") String datetime)
Response collectionItems (@Context HttpHeaders headers, @Parameter(description="The id of the collection") @PathParam("collectionid") String collectionid, @Parameter(description="The format of the result") @DefaultValue("html") @QueryParam("f") String format, @Parameter(description="The query limit", style=ParameterStyle.FORM) @DefaultValue("10") @QueryParam("limit") Integer limit, @Parameter(description="The offset to consider when fetching items") @DefaultValue("0") @QueryParam("offset") Integer offset, @Parameter(description="The boundingbox to used for querying", style=ParameterStyle.FORM) @DefaultValue("") @QueryParam("bbox") String bbox, @Parameter(description="The styling of the item when returned") @DefaultValue("") @QueryParam("mapstyle") String style, @Parameter(description="The crs of the data to be returned") @DefaultValue("EPSG:4326") @QueryParam("crs") String crs, @Parameter(description="The crs of a given bounding box") @DefaultValue("") @QueryParam("bbox-crs") String bboxcrs, @Parameter(description="A filter expression") @DefaultValue("") @QueryParam("filter") String filter, @Parameter(description="The language in which the filter expression is formulated") @DefaultValue("") @QueryParam("filter-lang") String filterlang, @Parameter(description="A temporal filter expression", style=ParameterStyle.FORM) @DefaultValue("") @QueryParam("datetime") String datetime)
Returns a number of features from a given featuretype.
Response conformanceJSON (@Parameter(description="The format of the conformance page") @DefaultValue("json") @QueryParam("f") String format)
Response conformanceXML (@Parameter(description="The format of the conformance page") @DefaultValue("xml") @QueryParam("f") String format)
Response conformanceHTML (@Parameter(description="The format of the conformance page") @DefaultValue("html") @QueryParam("f") String format)
Response conformance (@Parameter(description="The format of the conformance page") @DefaultValue("html") @QueryParam("f") String format)
Gets conformance information about the OGC API Features service.
Response constructCapabilitiesWFS10 (String version, String versionnamespace) throws XMLStreamException
Constructs a capabilities document for a WFS in version 1.0 .
Response constructCapabilitiesCSW (String version, String versionnamespace) throws XMLStreamException
Constructs a capabilities document for a CSW service .
Response constructCapabilities (String version, String versionnamespace) throws XMLStreamException
Constructs a capabilities document for a WFS in version 1.1 .
void describeConformance (IndentingXMLStreamWriter writer, String versionnamespace, String namespace) throws XMLStreamException
Describes the conformance part of a WFS webservices.
Response getCapabilities (@Parameter(description="The version of the WFS service to target") @DefaultValue("2.0.0") @QueryParam("version") String version) throws XMLStreamException
Returns the capabilities document for a WFS service.
void describeFeatureTypeWFS10 (XMLStreamWriter writer, JSONObject featuretype, String versionnamespace, String version) throws XMLStreamException
Describes a feature type according to the WFS1.0 specification.
void describeFeatureType (XMLStreamWriter writer, JSONObject featuretype, String versionnamespace, String version) throws XMLStreamException
Creates a feature type description.
void describeSpatialCapabilities (XMLStreamWriter writer, String versionnamespace, String namespace) throws XMLStreamException
Writes the spatial capabilities part of the WFS document.
void describeSpatialCapabilitiesWFS10 (XMLStreamWriter writer, String versionnamespace, String namespace) throws XMLStreamException
Creates the spatial capabilities document for a WFS in version 1.0.
void describeScalarCapabilities (XMLStreamWriter writer, String versionnamespace, String namespace) throws XMLStreamException
Writes the scalar capabilities document for a WFS.
Response describeFeatureType (@Parameter(description="The feature type name to describe") @QueryParam("typename") String typename, @Parameter(description="The version of the WFS service") @DefaultValue("version") @QueryParam("version") String version) throws XMLStreamException
Describes a feature type as an answer to a WFS request.
Response describeFeatureTypeJSON (@Parameter(description="The feature type to describe") @QueryParam("typename") String typename, @Parameter(description="The version of the WFS service") @DefaultValue("version") @QueryParam("version") String version)
Describes a feature type in JSON.
Response getGeoClassesFromOntology (@Parameter(description="The SPARQL endpoint to load classes from") @QueryParam("endpoint") String endpoint)
Gets geospatial classes from a SPARQL endpoint.
Response getEndpoints ()
Gets available SPARQL endpoitns from the triplestore configuration.
Response getPropertiesByClass (@Parameter(description="The SPARQL endpoint to load properties from") @QueryParam("endpoint") String endpoint, @Parameter(description="The class from which properties should be loaded") @QueryParam("class") String classs)
Gets available properties associated with a certain class.
Response getFeature (@QueryParam("typename") String typename, @Parameter(description="The output format of the WFS service request") @DefaultValue("json") @QueryParam("outputFormat") String output, @Parameter(description="The amount of features to be returned", example="10") @DefaultValue("10") @QueryParam("count") String count, @Parameter(description="The starting index of the WFS request") @DefaultValue("0") @QueryParam("startindex") String startindex, @Parameter(description="The name of the CRS to be used") @DefaultValue("") @QueryParam("srsName") String srsName, @Parameter(description="Indicates the sorting order") @DefaultValue("ASC") @QueryParam("sortBy") String sortBy, @Parameter(description="The style to apply to the returned collection if any") @DefaultValue("") @QueryParam("mapstyles") String style, @Parameter(description="The version of the WFS", example="2.0.0") @DefaultValue("2.0.0") @QueryParam("version") String version, @Parameter(description="Indicates a specific resource id to be queried") @DefaultValue("") @QueryParam("resourceid") String resourceids, @Parameter(description="A WFS filter expression") @DefaultValue("") @QueryParam("filter") String filter, @Parameter(description="The filter language to be used in the filterExpression parameter") @DefaultValue("CQL") @QueryParam("filterLanguage") String filterLanguage, @Parameter(description="The result type to return") @DefaultValue("results") @QueryParam("resultType") String resultType) throws JSONException, XMLStreamException
Response getGmlObject (@QueryParam("typename") String typename, @QueryParam("GmlObjectId") String gmlobjectid, @DefaultValue("4") @QueryParam("traverseXlinkDepth") String traverseXlinkDepth, @DefaultValue("gml") @QueryParam("outputFormat") String output)
Response getPropertyValue (@Parameter(description="Feature type to query") @QueryParam("typename") String typename, @QueryParam("valuereference") String propertyname, @DefaultValue("json") @QueryParam("outputFormat") String output, @DefaultValue("") @QueryParam("resourceids") String resourceids, @DefaultValue("") @QueryParam("filter") String filter, @DefaultValue("0") @QueryParam("count") String count, @DefaultValue("results") @QueryParam("resultType") String resultType)
Boolean addFeatureType (@Parameter(description="The SPARQL query used to retrive the feature type") @QueryParam("query") String sparqlQuery, @Parameter(description="The featuretype name") @QueryParam("typename") String name, @Parameter(description="The variable indicating the individual in the query") @DefaultValue("item") @QueryParam("indvar") String indvar, @Parameter(description="The limit of the initial sample to retrieve") @DefaultValue("500") @QueryParam("bboxlimit") String bboxlimit, @Parameter(description="The class to query") @QueryParam("class") String classs, @Parameter(description="The service type which is queried") @DefaultValue("WFS") @QueryParam("type") String type, @Parameter(description="The feature type description") @DefaultValue("") @QueryParam("description") String description, @Parameter(description="The EPSG of the feature type to be added") @DefaultValue("EPSG:4326") @QueryParam("targetCRS") String targetCRS, @Parameter(description="The namespace used for the feature type") @QueryParam("namespace") String namespace, @Parameter(description="The triple store to query when loading the feature type") @QueryParam("triplestore") String triplestore, @Parameter(description="The username needed for authentication") @DefaultValue("") @QueryParam("username") String username, @Parameter(description="The password needed for authentication") @DefaultValue("") @QueryParam("password") String password, @Parameter(description="The authtoken for authentication") @DefaultValue("") @QueryParam("authtoken") String authtoken)
Adds a feature type to the SemanticWFS.
Boolean addEndpoint (@Parameter(description="The name of the SPARQL endpoint to add") @QueryParam("name") String name, @Parameter(description="The address of the SPARQL endpoint") @QueryParam("endpoint") String endpoint, @Parameter(description="The type property used in this SPARQL endpoint") @QueryParam("typerel") String typerel, @Parameter(description="The geometry property used by this SPARQL endpoint") @QueryParam("georel") String georel, @Parameter(description="Username for authorization") @QueryParam("username") String username, @Parameter(description="Password for authorization") @QueryParam("password") String password, @Parameter(description="Authtoken if the user is already logged in") @DefaultValue("") @QueryParam("authtoken") String authtoken)
Adds a SPARQL endpoint to the triplestoreconf configuration.
Boolean saveFeatureTypes (@Parameter(description="JSON object containing feature types to be saved") @QueryParam("featjson") String featureTypesJSON, @Parameter(description="Authtoken for authorization") @DefaultValue("") @QueryParam("authtoken") String authtoken)
Saves feature types in the SemanticWFS Service.
Response login (@Parameter(description="Username for authorization") @QueryParam("username") String username, @Parameter(description="Password for authorization") @QueryParam("password") String password)
Performs a login returning an authtoken if successful.
String getFeatureTypes ()
Returns featuretypes known by the SemanticWFS service.
String prefixes ()
Returns prefixes known by the SemanticWFS service.
String addPrefixes (@QueryParam("query") String sparqlQuery, @QueryParam("typename") String name, @QueryParam("namespace") String namespace, @QueryParam("triplestore") String triplestore)
Response queryConfigs ()
Returns the query configuration document.
String queryService (@Parameter(description="SPARQL query to be resolved") @QueryParam("query") String query, @Parameter(description="SPARQL endpoint to query") @QueryParam("endpoint") String endpoint)
Exposes a query service which returns a SPARQL query result as REST.
String queryService (@Parameter(description="SPARQL query to be resolved") @QueryParam("query") String query, @Parameter(description="SPARQL endpoint to be queried") @QueryParam("endpoint") String endpoint, @Parameter(description="Indicates whether geojson should be returned to be shown in a map view") @QueryParam("geojson") String geojson)
Exposes a query service which returns a SPARQL query result as REST.
String transaction ()
Transaction method of the WFS specification.
String lockFeature ()
Lock Feature method of the WFS specification.
Public Attributes
XMLStreamWriter xmlwriter
String SERVICETYPEVERSION = "2.0.0"
String SERVERURL = "http://localhost:8080/WFSGeoSPARQL/rest/wfs?"
Static Public Attributes
static JSONObject triplestoreconf = null
static JSONObject wfsconf = null
static final MediaType openapijson =new MediaType("application", "vnd.oai.openapi+json;version=3.0")
static Map< String, Map< String, String > > featureTypeCache = new TreeMap<>()
static Map< String, Map< String, String > > nameSpaceCache = new TreeMap<>()
static Map< String, Tuple< Date, String > > hitCache = new TreeMap<>()
static Map< String, Map< String, StyleObject > > styleCache = new TreeMap<>()
static Map< String, Double[]> bboxCache = new TreeMap<>()
static long milliesInDays = 24 * 60 * 60 * 1000
Package Attributes
String htmlHead
Detailed Description
Implements OGC API Features and WFS webservice functionality.
Constructor & Destructor Documentation
WebService()
WebService () throws IOException
Constructor for this class.
Loads configuration files and performs initializations.
Exceptions
IOException on error
References TripleStoreConnector.getBoundingBoxFromTripleStoreData().
{
                 if (triplestoreconf == null) {
                         triplestoreconf = new JSONObject(new String(Files.readAllBytes(Paths.get("triplestoreconf.json")), StandardCharsets.UTF_8));
                         System.out.println(triplestoreconf);
                 }
                 if (wfsconf == null) {
                         try {
                                 System.out.println(new String(Files.readAllBytes(Paths.get("wfsconf.json")), StandardCharsets.UTF_8));
                                 System.out.println(new JSONObject(new String(Files.readAllBytes(Paths.get("wfsconf.json")), StandardCharsets.UTF_8)));
                         wfsconf = new JSONObject(new String(Files.readAllBytes(Paths.get("wfsconf.json")), StandardCharsets.UTF_8));
                         }catch(Exception e) {
                                 e.printStackTrace();
                         }
                         System.out.println(wfsconf);
                         System.out.println("in");
                 }
                 System.out.println("out");
                 for (Integer i = 0; i < wfsconf.getJSONArray("datasets").length(); i++) {
                         JSONObject featuretype = wfsconf.getJSONArray("datasets").getJSONObject(i);
                         System.out.println("Featuretype: "+featuretype);
                         if (featuretype.has("name") && !bboxCache.containsKey(featuretype.getString("name").toLowerCase())) {
                                 try {
                                 bboxCache.put(featuretype.getString("name").toLowerCase(),
                                                 TripleStoreConnector.getBoundingBoxFromTripleStoreData(featuretype.getString("triplestore"),
                                                                 featuretype.getString("query")));
                                 }catch(Exception e) {
                                         e.printStackTrace();
                                 }
                         }
                 }
                 htmlHead = "<html><head><link rel=\"stylesheet\" href=\"https://unpkg.com/leaflet@1.5.1/dist/leaflet.css\"\r\n"
                                 + "   integrity=\"sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ==\"\r\n"
                                 + "   crossorigin=\"\"/>\r\n" + "<script src=\"" + wfsconf.getString("baseurl")
                                 + "/config/js/proj4.js\"></script>" + "<script src=\"" + wfsconf.getString("baseurl")
                                 + "/config/js/prefixes.js\"></script>"
                                 + " <link rel=\"stylesheet\" href=\""+ wfsconf.getString("baseurl")+"/config/css/leaflet_legend.css\" />"
                                 + " <link rel=\"stylesheet\" type=\"text/css\" href=\"https://unpkg.com/leaflet-coverage@0.7/leaflet-coverage.css\">\r\n"
                                 + " <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css\" integrity=\"sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb\" crossorigin=\"anonymous\">"
                                 + " <link rel=\"stylesheet\" href=\""+wfsconf.getString("baseurl")+"/config/css/style.css\">"
                                 + "<script src=\"https://unpkg.com/leaflet@1.5.1/dist/leaflet.js\"\r\n"
                                 + "   integrity=\"sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og==\"\r\n"
                                 + "   crossorigin=\"\"></script><link rel=\"stylesheet\" href=\"https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css\"/>\r\n"
                                 + "<script src=\"" + wfsconf.getString("baseurl") + "/config/js/leaflet.pattern.js\"></script>\r\n"
                                 + "<script src=\"" + wfsconf.getString("baseurl")
                                 + "/config/js/Leaflet.geojsoncss.min.js\"></script>\r\n"
                                                                 + "<script src=\"" + wfsconf.getString("baseurl")
                                 + "/config/js/leaflet_legend.js\"></script>\r\n"
                                 + "<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n"
                                 + "<script src=\"https://unpkg.com/covutils@0.6/covutils.min.js\"></script>\r\n"
                                 + "<script src=\"https://unpkg.com/leaflet-coverage@0.7/leaflet-coverage.min.js\"></script>\r\n"
                                 + "<script src=\"https://cdn.jsdelivr.net/covjson-reader/0.16/covjson-reader.min.js\"></script>\r\n"
                                 + "<script src=\"https://unpkg.com/leaflet.vectorgrid@latest/dist/Leaflet.VectorGrid.bundled.js\"></script>\r\n"
                                 + "<script src=\"https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js\"></script>\r\n"
                                 + "<script src='https://api.mapbox.com/mapbox.js/plugins/leaflet-fullscreen/v1.0.1/Leaflet.fullscreen.min.js'></script>\r\n"
                                 + "<link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-fullscreen/v1.0.1/leaflet.fullscreen.css' rel='stylesheet' /></head>";
         }
Member Function Documentation
addEndpoint()
Boolean addEndpoint (@Parameter(description="The name of the SPARQL endpoint to add") @QueryParam("name") String name, @Parameter(description="The address of the SPARQL endpoint") @QueryParam("endpoint") String endpoint, @Parameter(description="The type property used in this SPARQL endpoint") @QueryParam("typerel") String typerel, @Parameter(description="The geometry property used by this SPARQL endpoint") @QueryParam("georel") String georel, @Parameter(description="Username for authorization") @QueryParam("username") String username, @Parameter(description="Password for authorization") @QueryParam("password") String password, @Parameter(description="Authtoken if the user is already logged in") @DefaultValue("") @QueryParam("authtoken") String authtoken)
Adds a SPARQL endpoint to the triplestoreconf configuration.
Parameters
name The name of the SPARQL endpoint
endpoint The SPARQL endpoint address
typerel The type relation of the SPARQL endpoint
georel The geometrical relation of the SPARQL endpoint
username A username required to save the configuration
password A password required to save the configuration
authtoken An authtoken authorizing the configuration
Returns
True if the endpoint has been successfully added, false otherwise
References UserType.Administrator, UserType.Configurer, UserManagementConnection.getInstance(), User.getUserlevel(), and UserManagementConnection.loginAuthToken().
{
                 User user=UserManagementConnection.getInstance().loginAuthToken(authtoken);
                 System.out.println("Add Feature Type");
                 if(true || name!=null && !name.isEmpty() && user!=null && (user.getUserlevel()==UserType.Configurer || user.getUserlevel()==UserType.Administrator)) {
                         JSONArray datasets = wfsconf.getJSONArray("datasets");
                         System.out.println(wfsconf);
                         System.out.println(datasets);
                         System.out.println("To add: "+name+" "+endpoint+" "+typerel+" "+georel);
                         JSONObject toadd = new JSONObject();
                         toadd.put("name", name);
                         toadd.put("endpoint", endpoint);
                         toadd.put("type", typerel);
                         toadd.put("geo", new JSONArray());
                         toadd.getJSONArray("geo").put(georel);
                         System.out.println("Adding feature type: "+toadd);
                         triplestoreconf.getJSONObject("endpoints").put(endpoint,toadd);
                         return true;
                 }
                 return false;
         }
addFeatureType()
Boolean addFeatureType (@Parameter(description="The SPARQL query used to retrive the feature type") @QueryParam("query") String sparqlQuery, @Parameter(description="The featuretype name") @QueryParam("typename") String name, @Parameter(description="The variable indicating the individual in the query") @DefaultValue("item") @QueryParam("indvar") String indvar, @Parameter(description="The limit of the initial sample to retrieve") @DefaultValue("500") @QueryParam("bboxlimit") String bboxlimit, @Parameter(description="The class to query") @QueryParam("class") String classs, @Parameter(description="The service type which is queried") @DefaultValue("WFS") @QueryParam("type") String type, @Parameter(description="The feature type description") @DefaultValue("") @QueryParam("description") String description, @Parameter(description="The EPSG of the feature type to be added") @DefaultValue("EPSG:4326") @QueryParam("targetCRS") String targetCRS, @Parameter(description="The namespace used for the feature type") @QueryParam("namespace") String namespace, @Parameter(description="The triple store to query when loading the feature type") @QueryParam("triplestore") String triplestore, @Parameter(description="The username needed for authentication") @DefaultValue("") @QueryParam("username") String username, @Parameter(description="The password needed for authentication") @DefaultValue("") @QueryParam("password") String password, @Parameter(description="The authtoken for authentication") @DefaultValue("") @QueryParam("authtoken") String authtoken)
Adds a feature type to the SemanticWFS.
Parameters
sparqlQuery The SPARQL query to be used by this feature type.
name The feature type name
indvar The individual variable
bboxlimit
classs
type
description
targetCRS
namespace
triplestore
username
password
authtoken
Returns
References UserType.Administrator, UserType.Configurer, UserManagementConnection.getInstance(), User.getUserlevel(), and UserManagementConnection.loginAuthToken().
                                                                                                               :4326") @QueryParam("targetCRS") String targetCRS,
                         @Parameter(description="The namespace used for the feature type") @QueryParam("namespace") String namespace,
                         @Parameter(description="The triple store to query when loading the feature type")  @QueryParam("triplestore") String triplestore,
                         @Parameter(description="The username needed for authentication") @DefaultValue("") @QueryParam("username") String username,
                         @Parameter(description="The password needed for authentication") @DefaultValue("") @QueryParam("password") String password,
                         @Parameter(description="The authtoken for authentication") @DefaultValue("") @QueryParam("authtoken") String authtoken) {
                 User user=UserManagementConnection.getInstance().loginAuthToken(authtoken);
                 System.out.println("Add Feature Type");
                 if(name==null && classs!=null) {
                         name=classs;
                 }
                 if(true || name!=null && !name.isEmpty() && user!=null && (user.getUserlevel()==UserType.Configurer || user.getUserlevel()==UserType.Administrator)) {
                         JSONArray datasets = wfsconf.getJSONArray("datasets");
                         System.out.println(wfsconf);
                         System.out.println(datasets);
                         System.out.println("To add: "+name+" "+namespace+" "+triplestore+" "+sparqlQuery);
                         JSONObject toadd = new JSONObject();
                         toadd.put("name", name);
                         toadd.put("indvar", indvar);
                         toadd.put("bboxlimit",bboxlimit);
                         toadd.put("class", classs);
                         toadd.put("type",type);
                         toadd.put("description",description);
                         toadd.put("targetCRS",targetCRS);
                         toadd.put("namespace", namespace);
                         toadd.put("triplestore", triplestore);
                         toadd.put("query", sparqlQuery);
                         System.out.println("Adding feature type: "+toadd);
                         datasets.put(toadd);
                         return true;
                 }
                 return false;
         }
addPrefixes()
String addPrefixes (@QueryParam("query") String sparqlQuery, @QueryParam("typename") String name, @QueryParam("namespace") String namespace, @QueryParam("triplestore") String triplestore)
{
                 return wfsconf.toString(2);
         }
collectionInformation()
Response collectionInformation (@Parameter(description="The id of the collection to be considered") @PathParam("collectionid") String collectionid, @Parameter(description="The format in which the collection should be returned", example="geojson") @DefaultValue("html") @QueryParam("f") String format, @Parameter(description="The maximum amount of features to be returned", example="10") @DefaultValue("10") @QueryParam("limit") String limit, @Parameter(description="An offset to be considered when returning features", example="10") @DefaultValue("0") @QueryParam("offset") String offset, @Parameter(description="Defines a bounding box from which to return the given features") @QueryParam("bbox") String bbox)
Returns a given collection description or parts of it.
Parameters
collectionid The id of the collection to be considered
format The format in which to return the collection
limit The maximum amount of features to return
offset The offset from which to start returning features
bbox The boundingbox in which the returned features should fit
Returns
The collection description as String
References ResultFormatter.definition, TripleStoreConnector.getFeatureTypeInformation(), ResultFormatter.getFormatter(), ResultFormatter.labelMap, ResultFormatter.resultMap, and ResultFormatter.urlformat.
{
                 if (collectionid == null) {
                         throw new NotFoundException();
                 }
                 JSONObject workingobj = null;
                 for (int i = 0; i < wfsconf.getJSONArray("datasets").length(); i++) {
                         JSONObject curobj = wfsconf.getJSONArray("datasets").getJSONObject(i);
                         if (curobj.getString("name").equalsIgnoreCase(collectionid)) {
                                 workingobj = curobj;
                                 break;
                         }
                 }
                 if (workingobj == null) {
                         throw new NotFoundException();
                 }
                 if (!featureTypeCache.containsKey(collectionid.toLowerCase())) {
                         featureTypeCache.put(collectionid.toLowerCase(),
                                         TripleStoreConnector.getFeatureTypeInformation(workingobj.getString("query"),
                                                         workingobj.getString("triplestore"), workingobj.getString("name"), workingobj));
                 }
                 Map<String, String> mapping = featureTypeCache.get(collectionid.toLowerCase());
                 if (format != null && format.contains("json")) {
                         JSONObject result = new JSONObject();
                         JSONArray resultlinks=new JSONArray();
                         result.put("id", workingobj.getString("name"));
                         result.put("name", workingobj.getString("name"));
                         result.put("title", workingobj.getString("name"));
                         if(workingobj.has("description")) {
                                 result.put("description", workingobj.getString("description"));
                         }else {
                                 result.put("description", "");
                         }
                         result.put("links",resultlinks);
                         /*JSONObject extent = new JSONObject();
                         result.put("extent", extent);
                         JSONArray spatial = new JSONArray();
                         JSONArray temporal=new JSONArray();
                         temporal.put("1970-01-01T00:00:00Z");
                         temporal.put("2020-08-22T22:10:44Z");
                         extent.put("spatial", spatial);
                         extent.put("temporal",temporal);*/
                         JSONArray crs = new JSONArray();
                         crs.put("http://www.opengis.net/def/crs/EPSG/0/"+workingobj.getString("targetCRS").substring(workingobj.getString("targetCRS").indexOf(":")+1));
                         result.put("storageCRS", "http://www.opengis.net/def/crs/EPSG/0/"+workingobj.getString("targetCRS").substring(workingobj.getString("targetCRS").indexOf(":")+1));
                         result.put("crs", crs);
                         JSONObject link = new JSONObject();
                         link.put("href", wfsconf.getString("baseurl") + "/collections/"+collectionid+"?f=json");
                         link.put("rel", "self");
                         link.put("type", "application/json");
                         link.put("title", "This document");
                         resultlinks.put(link);
                         link = new JSONObject();
                         link.put("href", wfsconf.getString("baseurl") + "/collections/"+collectionid+"?f=xml");
                         link.put("rel", "alternate");
                         link.put("type", "application/xml");
                         link.put("title", "This document as XML");
                         resultlinks.put(link);
                         link = new JSONObject();
                         link.put("href", wfsconf.getString("baseurl") + "/collections/"+collectionid+"?f=html");
                         link.put("rel", "alternate");
                         link.put("type", "text/html");
                         link.put("title", "This document as HTML");
                         resultlinks.put(link);
                         /*JSONArray collections=new JSONArray();
                         result.put("collections",collections);
                         JSONObject collectionentry=new JSONObject();
                         collections.put(collectionentry);
                         collectionentry.put("id", workingobj.getString("name"));
                         collectionentry.put("title", workingobj.getString("name"));
                         collectionentry.put("description", "");
 */
                         JSONArray links = resultlinks;
                         for (ResultFormatter formatter : ResultFormatter.resultMap.values()) {
                                 link = new JSONObject();
                                 if (formatter.exposedType.contains("geojson")) {
                                         link.put("rel", "item");
                                 } else {
                                         link.put("rel", "item");
                                 }
                                 link.put("href", wfsconf.getString("baseurl") + "/collections/" + collectionid + "/items" + "?f="
                                                 + formatter.urlformat);
                                 link.put("type", formatter.exposedType);
                                 link.put("title", collectionid);
                                 links.put(link);
                         }
                         link = new JSONObject();
                         link.put("rel", "describedBy");
                         link.put("href", wfsconf.getString("baseurl") + "/collections/" + collectionid + "/schema/");
                         link.put("type", "application/xml");
                         link.put("title", collectionid + " Schema");
                         links.put(link);
                         return Response.ok(result.toString(2)).type(MediaType.APPLICATION_JSON).build();
                 } else if (format != null && format.contains("gml")) {
                         StringWriter strwriter = new StringWriter();
                         XMLOutputFactory output = XMLOutputFactory.newInstance();
                         XMLStreamWriter writer;
                         try {
                                 writer = new IndentingXMLStreamWriter(output.createXMLStreamWriter(strwriter));
                                 writer.writeStartDocument();
                                 writer.setDefaultNamespace("http://www.opengis.net/ogcapi-features-1/1.0");
                                 writer.writeStartElement("Collection");
                                 writer.setPrefix("atom", "http://www.w3.org/2005/Atom");
                                 writer.writeAttribute("xmlns", "http://www.opengis.net/ogcapi-features-1/1.0");
                                 writer.writeAttribute("xmlns:atom", "http://www.w3.org/2005/Atom");
                                 writer.writeAttribute("xmlns:xsi", "http://www.w3.org/2001/XMLSchema-instance");
                                 writer.writeAttribute("xmlns:sf", "http://www.opengis.net/ogcapi-features-1/1.0/sf");
                                 writer.writeAttribute("xmlns:gml", "http://www.opengis.net/gml/3.2");
                                 writer.writeAttribute("service", "OGCAPI-FEATURES");
                                 writer.writeAttribute("version", "1.0.0");
                                 writer.writeStartElement("links");
                                 writer.writeStartElement("http://www.w3.org/2005/Atom", "link");
                                 writer.writeAttribute("rel", "self");
                                 writer.writeAttribute("title", "This document");
                                 writer.writeAttribute("type", "application/xml");
                                 writer.writeAttribute("href", wfsconf.getString("baseurl") + "/collections/"+collectionid+"/?f=gml");
                                 writer.writeEndElement();
                                 writer.writeStartElement("http://www.w3.org/2005/Atom", "link");
                                 writer.writeAttribute("rel", "alternate");
                                 writer.writeAttribute("title", "This document as JSON");
                                 writer.writeAttribute("type", "application/json");
                                 writer.writeAttribute("href", wfsconf.getString("baseurl") + "/collections/"+collectionid+ "/?f=json");
                                 writer.writeEndElement();
                                 writer.writeStartElement("http://www.w3.org/2005/Atom", "link");
                                 writer.writeAttribute("rel", "alternate");
                                 writer.writeAttribute("title", "This document as HTML");
                                 writer.writeAttribute("type", "text/html");
                                 writer.writeAttribute("href", wfsconf.getString("baseurl") + "/collections/"+collectionid+ "/?f=html");
                                 writer.writeEndElement();
                                 writer.writeEndElement();
                                 writer.writeStartElement("collections");
                                 writer.writeStartElement(collectionid);
                                 writer.writeStartElement("Id");
                                 writer.writeCharacters(collectionid);
                                 writer.writeEndElement();
                                 writer.writeStartElement("Title");
                                 writer.writeCharacters(workingobj.getString("description"));
                                 writer.writeEndElement();
                                 for (ResultFormatter formatter : ResultFormatter.resultMap.values()) {
                                         writer.writeStartElement("http://www.w3.org/2005/Atom", "link");
                                         if (formatter.exposedType.contains("geojson")) {
                                                 writer.writeAttribute("rel", "item");
                                         } else {
                                                 writer.writeAttribute("rel", "item");
                                         }
                                         writer.writeAttribute("title", workingobj.getString("name"));
                                         writer.writeAttribute("type", formatter.exposedType);
                                         writer.writeAttribute("href", wfsconf.getString("baseurl") + "/collections/"
                                                         + workingobj.getString("name") + "/items?f=" + formatter.urlformat);
                                         writer.writeEndElement();
                                 }
                                 writer.writeStartElement("http://www.w3.org/2005/Atom", "link");
                                 writer.writeAttribute("rel", "describedBy");
                                 writer.writeAttribute("title", workingobj.getString("name"));
                                 writer.writeAttribute("type", "application/xml");
                                 writer.writeAttribute("href",
                                                 wfsconf.getString("baseurl") + "/collections/" + workingobj.getString("name") + "/schema/");
                                 writer.writeEndElement();
                                 /*writer.writeStartElement("Extent");
                                 writer.writeStartElement("Spatial");
                                 writer.writeAttribute("crs", "http://www.opengis.net/def/crs/OGC/1.3/CRS84");
                                 writer.writeEndElement();
                                 writer.writeEndElement();*/
                                 writer.writeEndElement();
                                 writer.writeEndElement();
                                 writer.writeEndElement();
                                 writer.writeEndDocument();
                                 writer.flush();
                                 return Response.ok(strwriter.toString(),MediaType.APPLICATION_XML).build();
                         } catch (XMLStreamException e) {
                                 e.printStackTrace();
                                 return this.createExceptionResponse(e, "");
                         }
                 } else if (format == null || format.contains("html")) {
                         System.out.println("WorkingObject: "+workingobj);
                         StringBuilder builder = new StringBuilder();
                         JSONObject geojson = new JSONObject();
                         JSONObject geometry = new JSONObject();
                         JSONObject properties = new JSONObject();
                         geojson.put("type", "Feature");
                         geojson.put("id", collectionid);
                         geojson.put("geometry", geometry);
                         geojson.put("properties", properties);
                         builder.append(htmlHead);
                         builder.append("<script>");
                         builder.append("var definitionlinks={");
                         for (String key : ResultFormatter.labelMap.keySet()) {
                                 builder.append("\""+ResultFormatter.getFormatter(key).urlformat+"\":\""+ResultFormatter.getFormatter(key).definition+"\",\n");
                         }
                         builder.delete(builder.length()-1, builder.length());
                         builder.append("};\n");
                         builder.append("function changeDefLink(){$('#formatlink').attr('href',definitionlinks[$('#format').val()]);}");
                         builder.append("function showCollections(link){window.open(link+\"?offset=\"+$('#offset').val()+\"&limit=\"+$('#limit').val()+\"&crs=\"+$('#crs').val()+\"&f=\"+$('#format').val(),'_blank');} var espg=\"" + (workingobj.has("targetCRS") ? workingobj.get("targetCRS") : "")
                                         + "\";</script><body><header id=\"header\"><h1 align=\"center\">");
                         builder.append(
                                         (workingobj.getString("name") != null ? workingobj.getString("name") : collectionid));
                         builder.append("</h1></header>");
                         builder.append("<div class=\"sticky row crumbs\"><div class=\"col-sm-12 col-md-10 col-md-offset-1\">");
                         builder.append("<a href=\""+wfsconf.getString("baseurl")+"\">Landingpage</a> / <a href=\""+wfsconf.getString("baseurl")+"/collections/\">Collections</a> / <a href=\""+wfsconf.getString("baseurl")+"/collections/"+collectionid+"\">"+workingobj.getString("name")+"</a>");
                     builder.append("</div></div>");
                         builder.append("<div class=\"container-fluid\" role=\"main\"><div class=\"row\"><section>");
                         builder.append(workingobj.getString("description"));
                         builder.append("<h3>Queryables</h3><ul><li>");
                         builder.append("<a href=\""+wfsconf.getString("baseurl") + "/collections/"
                                         + workingobj.getString("name") + "/queryables?f=html\">Queryables of "+workingobj.getString("name")+"</a></li></ul>");
                         builder.append("<h3>View</h3><ul>");
                         builder.append("<li><a href=\"" + wfsconf.getString("baseurl")
                                         + "/collections/" + workingobj.getString("name") + "/items?f=html&limit=1&offset=" + (offset + 1)
                                         + "\">First item</a></li>");
                         builder.append("<li><a href=\""+wfsconf.getString("baseurl") + "/collections/"
                                         + workingobj.getString("name") + "/items?f=html\">First 10 items</a></li>");
                         builder.append("<li><a href=\"" + wfsconf.getString("baseurl")
                         + "/collections/" + workingobj.getString("name") + "/items?f=html&limit=100&offset=" + (offset + 1)
                         + "\">First 100 items</a></li>");
                         builder.append("<li><a href=\"" + wfsconf.getString("baseurl")
                         + "/collections/" + workingobj.getString("name") + "/items?f=html&limit=1000&offset=" + (offset + 1)
                         + "\">First 1000 items</a></li>");
                         builder.append("</ul><h3>Downloads</h3>Number of features:&nbsp;<input type=\"number\" min=\"1\" id=\"limit\" value=\"10\"/>&nbsp;Offset:&nbsp;<input type=\"number\" min=\"1\" id=\"offset\" value=\"0\"/>Format:<select id=\"format\" onchange=\"changeDefLink()\">");
                         for (String key : ResultFormatter.labelMap.keySet()) {
                                 builder.append("<option value=\""+ResultFormatter.getFormatter(key).urlformat+"\">"+ResultFormatter.labelMap.get(key)+"</option>");
                         }
                         builder.append("</select><a id=\"formatlink\" href=\"#\" target=\"_blank\">");
                         builder.append("<svg width=\"1em\" height=\"1em\" viewBox=\"0 0 16 16\" class=\"bi bi-info-circle-fill\" fill=\"currentColor\" xmlns=\"http://www.w3.org/2000/svg\"><path fill-rule=\"evenodd\" d=\"M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412l-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM8 5.5a1 1 0 1 0 0-2 1 1 0 0 0 0 2z\"/></svg>");
                         builder.append("</a>");
                         builder.append("<br/>CRS:<select id=\"crs\"></select><button id=\"showfeaturebutton\" onclick=\"showCollections('"+wfsconf.getString("baseurl")+"/collections/" + workingobj.getString("name") + "/items')\"/>Show</button></section></div></div></div>");
                         builder.append("<footer id=\"footer\"><table width=100%><tbody><tr><td><a href=\"" + wfsconf.getString("baseurl")
                                         + "/collections?f=html\">Back to Collections</a></td><td align=right>This page in <a href=\""
                                         + wfsconf.getString("baseurl") + "/collections/" + workingobj.getString("name")
                                         + "?f=gml\">[GML]</a> <a href=\"" + wfsconf.getString("baseurl") + "/collections/"
                                         + workingobj.getString("name") + "?f=geojson\">[JSON]</a></td></tr></tbody></table></footer><script> $.ajax({url:'../config/epsg.txt',success: function (data){$('#crs').html(data); $('#crs').val(\""+workingobj.getString("targetCRS")+"\");}});</script></body></html>");
                         return Response.ok(builder.toString(),MediaType.TEXT_HTML).build();
                 } else {
                         throw new NotFoundException();
                 }
         }
collectionInformationHTML()
Response collectionInformationHTML (@Parameter(description="The id of the collection to be considered") @PathParam("collectionid") String collectionid, @Parameter(description="The format in which the collection should be returned", example="geojson") @DefaultValue("html") @QueryParam("f") String format, @Parameter(description="The maximum amount of features to be returned", example="10") @DefaultValue("10") @QueryParam("limit") String limit, @Parameter(description="An offset to be considered when returning features", example="10") @DefaultValue("0") @QueryParam("offset") String offset, @Parameter(description="Defines a bounding box from which to return the given features") @QueryParam("bbox") String bbox)
{
                 return collectionInformation(collectionid, format, limit, offset, bbox);
         }
collectionInformationJSON()
Response collectionInformationJSON (@Parameter(description="The id of the collection to be considered") @PathParam("collectionid") String collectionid, @Parameter(description="The format in which the collection should be returned", example="geojson") @DefaultValue("json") @QueryParam("f") String format, @Parameter(description="The maximum amount of features to be returned", example="10") @DefaultValue("10") @QueryParam("limit") String limit, @Parameter(description="An offset to be considered when returning features", example="10") @DefaultValue("0") @QueryParam("offset") String offset, @Parameter(description="Defines a bounding box from which to return the given features") @QueryParam("bbox") String bbox)
{
                 return collectionInformation(collectionid, format, limit, offset, bbox);
         }
collectionInformationXML()
Response collectionInformationXML (@Parameter(description="The id of the collection to be considered") @PathParam("collectionid") String collectionid, @Parameter(description="The format in which the collection should be returned", example="geojson") @DefaultValue("xml") @QueryParam("f") String format, @Parameter(description="The maximum amount of features to be returned", example="10") @DefaultValue("10") @QueryParam("limit") String limit, @Parameter(description="An offset to be considered when returning features", example="10") @DefaultValue("0") @QueryParam("offset") String offset, @Parameter(description="Defines a bounding box from which to return the given features") @QueryParam("bbox") String bbox)
{
                 return collectionInformation(collectionid, format, limit, offset, bbox);
         }
collectionItems()
Response collectionItems (@Context HttpHeaders headers, @Parameter(description="The id of the collection") @PathParam("collectionid") String collectionid, @Parameter(description="The format of the result") @DefaultValue("html") @QueryParam("f") String format, @Parameter(description="The query limit", style=ParameterStyle.FORM) @DefaultValue("10") @QueryParam("limit") Integer limit, @Parameter(description="The offset to consider when fetching items") @DefaultValue("0") @QueryParam("offset") Integer offset, @Parameter(description="The boundingbox to used for querying", style=ParameterStyle.FORM) @DefaultValue("") @QueryParam("bbox") String bbox, @Parameter(description="The styling of the item when returned") @DefaultValue("") @QueryParam("mapstyle") String style, @Parameter(description="The crs of the data to be returned") @DefaultValue("EPSG:4326") @QueryParam("crs") String crs, @Parameter(description="The crs of a given bounding box") @DefaultValue("") @QueryParam("bbox-crs") String bboxcrs, @Parameter(description="A filter expression") @DefaultValue("") @QueryParam("filter") String filter, @Parameter(description="The language in which the filter expression is formulated") @DefaultValue("") @QueryParam("filter-lang") String filterlang, @Parameter(description="A temporal filter expression", style=ParameterStyle.FORM) @DefaultValue("") @QueryParam("datetime") String datetime)
Returns a number of features from a given featuretype.
Parameters
collectionid The featuretype to return from
format The format of the result
limit The maximum amount of features to return
offset The offset from which to return features
bbox The bounding box in which features which should be returned are contained
style The style to apply
bboxcrs The CRS of the boundingbox to apply
filter A filter expression
filterlang The filter expression language
datetime A time constraint
Returns
The query result as String
References TripleStoreConnector.executeQuery(), ResultFormatter.fileextension, TripleStoreConnector.getFeatureTypeInformation(), ResultFormatter.getFormatter(), ResultFormatter.mimeType, WebService.nameSpaceCache, and ResultFormatter.resultMap.
                                                                                                         :4326") @QueryParam("crs") String crs,
                         @Parameter(description="The crs of a given bounding box") @DefaultValue("") @QueryParam("bbox-crs") String bboxcrs,
                         @Parameter(description="A filter expression") @DefaultValue("") @QueryParam("filter") String filter,
                         @Parameter(description="The language in which the filter expression is formulated") @DefaultValue("") @QueryParam("filter-lang") String filterlang,
                         @Parameter(description="A temporal filter expression",style=ParameterStyle.FORM) @DefaultValue("") @QueryParam("datetime") String datetime) {
                 System.out.println("Limit: " + limit);
                 System.out.println("FORMAT: "+format);
                 if (collectionid == null) {
                         throw new NotFoundException();
                 }
                 /*if(format.isEmpty() && headers.getAcceptableMediaTypes().isEmpty()) {
                         format="html";
                 }else if(format.isEmpty() && !headers.getAcceptableMediaTypes().isEmpty()) {
                         for(MediaType mediatype:headers.getAcceptableMediaTypes()) {
                                 if(ResultFormatter.resultMap.containsKey(mediatype.toString())) {
                                         format=mediatype.toString();
                                         break;
                                 }
                         }
                 }*/
                 System.out.println("FORMAT: "+format);
                 JSONObject workingobj=null;
                 for (int i = 0; i < wfsconf.getJSONArray("datasets").length(); i++) {
                         JSONObject curobj = wfsconf.getJSONArray("datasets").getJSONObject(i);
                         if (curobj.getString("name").equalsIgnoreCase(collectionid)) {
                                 workingobj = curobj;
                                 break;
                         }
                 }
                 if (workingobj == null) {
                         throw new NotFoundException();
                 }
                 if (!workingobj.has("attcount") && !workingobj.getString("query").contains("?rel")
                                 && !workingobj.getString("query").contains("?val")) {
                         featureTypeCache.put(collectionid.toLowerCase(),
                                         TripleStoreConnector.getFeatureTypeInformation(workingobj.getString("query"),
                                                         workingobj.getString("triplestore"), workingobj.getString("name"), workingobj));
                         workingobj.put("attcount", 1);
                 } else if (!workingobj.has("attcount")) {
                         featureTypeCache.put(collectionid.toLowerCase(),
                                         TripleStoreConnector.getFeatureTypeInformation(workingobj.getString("query"),
                                                         workingobj.getString("triplestore"), workingobj.getString("name"), workingobj));
                 }
                 if (!workingobj.has("attcount") || workingobj.getInt("attcount") == 0)
                         workingobj.put("attcount", 1);
                 System.out.println("Attcount: " + workingobj.getInt("attcount"));
                 System.out.println(limit);
                 try {
                         String res="";
                         // System.out.println(res);
                         // System.out.println(res);
                         if (format != null && format.contains("json") && !format.contains("covjson") && !format.contains("jsonp") && !format.contains("seq") && !format.equalsIgnoreCase("rdfjson")) {
                             res = TripleStoreConnector.executeQuery(workingobj.getString("query"),
                                                         workingobj.getString("triplestore"), format,
                                                         limit.toString(),
                                                         offset.toString(), "sf:featureMember", collectionid,
                                                         "", workingobj, filter, "", crs,bboxcrs, bbox,
                                                         style,true,(workingobj.has("invertXY")?workingobj.getBoolean("invertXY"):false),null);
                                 if (res == null || res.isEmpty()) {
                                         System.out.println("RES: "+res);
                                         throw new NotFoundException();
                                 }
                                 JSONObject result = new JSONObject();
                                 JSONArray links = new JSONArray();
                                 for (ResultFormatter formatter : ResultFormatter.resultMap.values()) {
                                         JSONObject link = new JSONObject();
                                         if (formatter.exposedType.contains("geojson")) {
                                                 link.put("rel", "self");
                                                 JSONObject nextlink = new JSONObject();
                                                 nextlink.put("rel", "next");
                                                 nextlink.put("href", wfsconf.getString("baseurl") + "/collections/" + collectionid + "/items?offset="+(Integer.valueOf(offset)+Integer.valueOf(limit))+"&limit="+limit+"&f="
                                                                 + formatter.urlformat);
                                                 nextlink.put("type", formatter.exposedType);
                                                 nextlink.put("title", "next page");
                                                 links.put(nextlink);
                                         } else {
                                                 link.put("rel", "alternate");
                                         }
                                         link.put("href", wfsconf.getString("baseurl") + "/collections/" + collectionid + "/items?f="
                                                         + formatter.urlformat);
                                         link.put("type", formatter.exposedType);
                                         link.put("title", collectionid);
                                         links.put(link);
                                 }
                                 if (ResultFormatter.getFormatter(format).mimeType.contains("jsonld")) {
                                         return Response.ok(res).type("text/plain").build();
                                 }
                                 JSONObject jsonresult = new JSONObject(res);
                                 JSONArray features = jsonresult.getJSONArray("features");
                                 if (jsonresult.has("@context")) {
                                         result.put("@context", jsonresult.getJSONObject("@context"));
                                 }
                                 result.put("type", "FeatureCollection");
                                 result.put("links", links);
                                 result.put("timeStamp", System.currentTimeMillis());
                                 result.put("numberMatched", features.length());
                                 result.put("numberReturned", features.length());
                                 result.put("features", features);
                                 return Response.ok(result.toString(2),ResultFormatter.getFormatter(format).mimeType).build();
                         } else if (format != null && format.contains("gml")) {
                             res = TripleStoreConnector.executeQuery(workingobj.getString("query"),
                                                         workingobj.getString("triplestore"), format,
                                                         limit.toString(),
                                                         offset.toString(), "sf:featureMember", collectionid,
                                                         "", workingobj, filter, "", crs,bboxcrs, bbox,
                                                         style,true,(workingobj.has("invertXY")?workingobj.getBoolean("invertXY"):false),null);
                                 if (res == null || res.isEmpty()) {
                                         System.out.println("RES: "+res);
                                         throw new NotFoundException();
                                 }
                                 StringWriter strwriter = new StringWriter();
                                 XMLOutputFactory output = XMLOutputFactory.newInstance();
                                 XMLStreamWriter writer;
                                 System.out.println("GML RESULT!!!");
                                 try {
                                         writer = new IndentingXMLStreamWriter(output.createXMLStreamWriter(strwriter));
                                         writer.writeStartDocument();
                                         writer.writeStartElement("sf:FeatureCollection");
                                         writer.writeAttribute("xmlns", "http://www.opengis.net/ogcapi-features-1/1.0");
                                         writer.writeAttribute("xmlns:atom", "http://www.w3.org/2005/Atom");
                                         writer.writeAttribute("xmlns:xsi", "http://www.w3.org/2001/XMLSchema-instance");
                                         writer.writeAttribute("xmlns:sf", "http://www.opengis.net/ogcapi-features-1/1.0/sf");
                                         writer.writeAttribute("xmlns:gml", "http://www.opengis.net/gml/3.2");
                                         writer.setDefaultNamespace("http://www.opengis.net/ogcapi-features-1/1.0");
                                         for (String ns : WebService.nameSpaceCache.get(collectionid.toLowerCase()).keySet()) {
                                                 writer.writeAttribute(
                                                                 "xmlns:" + WebService.nameSpaceCache.get(collectionid.toLowerCase()).get(ns), ns);
                                         }
                                         writer.setPrefix("atom", "http://www.w3.org/2005/Atom");
                                         writer.writeAttribute("service", "OGCAPI-FEATURES");
                                         writer.writeAttribute("version", "1.0.0");
                                         writer.writeStartElement("gml:boundedBy");
                                         writer.writeEndElement();
                                         writer.writeStartElement("Title");
                                         writer.writeCharacters(collectionid);
                                         writer.writeEndElement();
                                         writer.writeStartElement("Description");
                                         writer.writeCharacters(collectionid);
                                         writer.writeEndElement();
                                         for (ResultFormatter formatter : ResultFormatter.resultMap.values()) {
                                                 writer.writeStartElement("http://www.w3.org/2005/Atom", "link");
                                                 if (formatter.exposedType.contains("json")) {
                                                         writer.writeAttribute("rel", "self");
                                                 } else {
                                                         writer.writeAttribute("rel", "alternate");
                                                 }
                                                 writer.writeAttribute("title", workingobj.getString("name"));
                                                 writer.writeAttribute("type", formatter.exposedType);
                                                 writer.writeAttribute("href", wfsconf.getString("baseurl") + "/collections/"
                                                                 + workingobj.getString("name") + "/items?f=" + formatter.exposedType);
                                                 writer.writeEndElement();
                                         }
                                         strwriter.append(res);
                                         writer.writeEndElement();
                                         writer.writeEndDocument();
                                         writer.flush();
                                         System.out.println("GML RESULT!");
                                         return Response.ok(strwriter.toString(),ResultFormatter.getFormatter(format).mimeType)
                                                         .build();
                                 } catch (XMLStreamException e) {
                                         e.printStackTrace();
                                         // TODO Auto-generated catch block
                                         return this.createExceptionResponse(e, "");
                                 }
                         } else if (format == null || format.contains("html")) {
                             res = TripleStoreConnector.executeQuery(workingobj.getString("query"),
                                                         workingobj.getString("triplestore"), format,
                                                         limit.toString(),
                                                         offset.toString(), "sf:featureMember", collectionid,
                                                         "", workingobj, filter, "", crs,bboxcrs, bbox,
                                                         style,true,(workingobj.has("invertXY")?workingobj.getBoolean("invertXY"):false),null);
                                 if (res == null || res.isEmpty()) {
                                         System.out.println("RES: "+res);
                                         throw new NotFoundException();
                                 }
                                 StringBuilder builder = new StringBuilder();
                                 builder.append(htmlHead);
                                 builder.append("<body><header id=\"header\"><h1 align=\"center\">");
                                 builder.append(collectionid);
                                 builder.append("</h1></header>");
                                 builder.append("<div class=\"sticky row crumbs\"><div class=\"col-sm-12 col-md-10 col-md-offset-1\">");
                                 builder.append("<a href=\""+wfsconf.getString("baseurl")+"\">Landingpage</a> / <a href=\""+wfsconf.getString("baseurl")+"/collections/\">Collections</a> / <a href=\""+wfsconf.getString("baseurl")+"/collections/"+collectionid+"\">"+workingobj.getString("name")+"</a> / <a href=\""+wfsconf.getString("baseurl")+"/collections/"+collectionid+"/items?f=html\">Items</a>");
                             builder.append("</div></div>");
                                 builder.append("<div class=\"container-fluid\" role=\"main\"><div class=\"row\">");
                                 builder.append(res);
                                 // builder.append("<script>$( document ).ready(function()
                                 // {$('#queryres').DataTable({\"scrollX\":\"100%\",\"scrollCollapse\":
                                 // true});});</script>");
                                 if (Integer.valueOf(limit) == 1) {
                                         builder.append("<table width=100%><tr><td><a href=\"" + wfsconf.getString("baseurl")
                                                         + "/collections/" + workingobj.getString("name") + "/items?f=html&limit=1&offset="
                                                         + (Integer.valueOf(offset) != 0 ? (Integer.valueOf(offset) - 1) + "" : "0")
                                                         + "\">[Previous]</a></td><td align=right><a href=\"" + wfsconf.getString("baseurl")
                                                         + "/collections/" + workingobj.getString("name") + "/items?f=html&limit=1&offset="
                                                         + (Integer.valueOf(offset) + 1) + "\">[Next]</a></td></tr></table></div></div></div>");
                                 }
                                 builder.append("</div><footer id=\"footer\"><table width=100%><tbody><tr><td><a href=\"" + wfsconf.getString("baseurl") + "/collections/"
                                                 + collectionid + "?f=html\">Back to " + collectionid
                                                 + " Collection</a></td><td align=right>This page in <a href=\"" + wfsconf.getString("baseurl")
                                                 + "/collections/" + workingobj.getString("name") + "/items?f=gml&limit=" + limit + "&offset="
                                                 + offset + "\">[GML]</a> <a href=\"" + wfsconf.getString("baseurl") + "/collections/"
                                                 + workingobj.getString("name") + "/items?f=geojson&limit=" + limit + "&offset=" + offset
                                                 + "\">[JSON]</a></td></tr></tbody></table></footer>");
                                 builder.append("</body></html>");
                                 return Response.ok(builder.toString(),ResultFormatter.getFormatter(format).mimeType).build();
                         } else {
                                 final JSONObject wko2=workingobj;
                                 StreamingOutput stream = new StreamingOutput() {
                                     @Override
                                     public void write(OutputStream os) throws IOException,
                                     WebApplicationException {
                                       Writer writer = new BufferedWriter(new OutputStreamWriter(os));
                                       String res;
                                         try {
                                                 res = TripleStoreConnector.executeQuery(wko2.getString("query"),
                                                                 wko2.getString("triplestore"), format,
                                                                         limit.toString(),
                                                                         offset.toString(), "sf:featureMember", collectionid,
                                                                         "", wko2, filter, "", crs,bboxcrs, bbox,
                                                                         style,true,(wko2.has("invertXY")?wko2.getBoolean("invertXY"):false),writer);
                                               if(res!=null && !res.isEmpty()) {
                                                   writer.write(res);
                                               }
                                         } catch (JSONException | XMLStreamException | IOException e) {
                                                 // TODO Auto-generated catch block
                                                 e.printStackTrace();
                                         }
                                         writer.close();
                                     }
                                   };
                                 return Response.ok(stream,ResultFormatter.getFormatter(format).mimeType)
                                                 .header("Content-Disposition", "attachment; filename*=UTF-8''" + collectionid+"_items."
                                                                 +ResultFormatter.getFormatter(format).fileextension)
                                                 .build();
                         }
                 } catch (JSONException | XMLStreamException | IOException e1) {
                         e1.printStackTrace();
                         return Response.ok("",MediaType.TEXT_PLAIN).build();
                 }
         }
collectionItemsHTML()
Response collectionItemsHTML (@Context HttpHeaders headers, @Parameter(description="The id of the collection") @PathParam("collectionid") String collectionid, @Parameter(description="The format of the result") @DefaultValue("html") @QueryParam("f") String format, @Parameter(description="The query limit", style=ParameterStyle.FORM) @DefaultValue("10") @QueryParam("limit") Integer limit, @Parameter(description="The offset to consider when fetching items") @DefaultValue("0") @QueryParam("offset") Integer offset, @Parameter(description="A bounding box", style=ParameterStyle.FORM) @DefaultValue("") @QueryParam("bbox") String bbox, @Parameter(description="The styling of the item when returned") @DefaultValue("") @QueryParam("style") String style, @Parameter(description="The crs of the data to be returned") @DefaultValue("") @QueryParam("crs") String crs, @Parameter(description="The crs of a given bounding box") @DefaultValue("") @QueryParam("bbox-crs") String bboxcrs, @Parameter(description="A filter expression") @DefaultValue("") @QueryParam("filter") String filter, @Parameter(description="The language in which the filter expression is formulated") @DefaultValue("") @QueryParam("filter-lang") String filterlang, @Parameter(description="A temporal filter expression") @DefaultValue("") @QueryParam("datetime") String datetime)
{
                 return collectionItems(headers,collectionid, format, limit, offset, bbox, style,crs, bboxcrs, filter, filterlang, datetime);
         }
collectionItemsJSON()
Response collectionItemsJSON (@Context HttpHeaders headers, @Parameter(description="The id of the collection") @PathParam("collectionid") String collectionid, @Parameter(description="The format of the result") @DefaultValue("json") @QueryParam("f") String format, @Parameter(description="The query limit", style=ParameterStyle.FORM) @DefaultValue("10") @QueryParam("limit") Integer limit, @Parameter(description="The offset to consider when fetching items") @DefaultValue("0") @QueryParam("offset") Integer offset, @Parameter(description="A bounding box", style=ParameterStyle.FORM) @DefaultValue("") @QueryParam("bbox") String bbox, @Parameter(description="The styling of the item when returned") @DefaultValue("") @QueryParam("style") String style, @Parameter(description="The crs of the data to be returned") @DefaultValue("EPSG:4326") @QueryParam("crs") String crs, @Parameter(description="The crs of a given bounding box") @DefaultValue("") @QueryParam("bbox-crs") String bboxcrs, @Parameter(description="A filter expression") @DefaultValue("") @QueryParam("filter") String filter, @Parameter(description="The language in which the filter expression is formulated") @DefaultValue("") @QueryParam("filter-lang") String filterlang, @Parameter(description="A temporal filter expression") @DefaultValue("") @QueryParam("datetime") String datetime)
                                                                                                         :4326") @QueryParam("crs") String crs,
                         @Parameter(description="The crs of a given bounding box") @DefaultValue("") @QueryParam("bbox-crs") String bboxcrs,
                         @Parameter(description="A filter expression") @DefaultValue("") @QueryParam("filter") String filter,
                         @Parameter(description="The language in which the filter expression is formulated") @DefaultValue("") @QueryParam("filter-lang") String filterlang,
                         @Parameter(description="A temporal filter expression") @DefaultValue("") @QueryParam("datetime") String datetime) {
                 return collectionItems(headers,collectionid, format, limit, offset, bbox, style,crs, bboxcrs, filter, filterlang, datetime);
         }
collectionItemsXML()
Response collectionItemsXML (@Context HttpHeaders headers, @Parameter(description="The id of the collection") @PathParam("collectionid") String collectionid, @Parameter(description="The format of the result") @DefaultValue("gml") @QueryParam("f") String format, @Parameter(description="The query limit", style=ParameterStyle.FORM) @DefaultValue("10") @QueryParam("limit") Integer limit, @Parameter(description="The offset to consider when fetching items") @DefaultValue("0") @QueryParam("offset") Integer offset, @Parameter(description="A bounding box", style=ParameterStyle.FORM) @DefaultValue("") @QueryParam("bbox") String bbox, @Parameter(description="The styling of the item when returned") @DefaultValue("") @QueryParam("style") String style, @Parameter(description="The crs of the data to be returned") @DefaultValue("EPSG:4326") @QueryParam("crs") String crs, @Parameter(description="The crs of a given bounding box") @DefaultValue("") @QueryParam("bbox-crs") String bboxcrs, @Parameter(description="A filter expression") @DefaultValue("") @QueryParam("filter") String filter, @Parameter(description="The language in which the filter expression is formulated") @DefaultValue("") @QueryParam("filter-lang") String filterlang, @Parameter(description="A temporal filter expression") @DefaultValue("") @QueryParam("datetime") String datetime)
                                                                                                         :4326") @QueryParam("crs") String crs,
                         @Parameter(description="The crs of a given bounding box") @DefaultValue("") @QueryParam("bbox-crs") String bboxcrs,
                         @Parameter(description="A filter expression") @DefaultValue("") @QueryParam("filter") String filter,
                         @Parameter(description="The language in which the filter expression is formulated") @DefaultValue("") @QueryParam("filter-lang") String filterlang,
                         @Parameter(description="A temporal filter expression") @DefaultValue("") @QueryParam("datetime") String datetime) {
                 return collectionItems(headers,collectionid, format, limit, offset, bbox, style,crs, bboxcrs, filter, filterlang, datetime);
         }
collections()
Response collections (@Parameter(description="Return format", style=ParameterStyle.FORM) @DefaultValue("html") @QueryParam("f") String format)
Returns a list of feature types/collections.
Parameters
format The format in which the result is returned
Returns
The result as String
References ResultFormatter.getFormatter(), ResultFormatter.mimeType, and ResultFormatter.resultMap.
{
                 System.out.println(format);
                 if (format != null && format.contains("json")) {
                         JSONObject result = new JSONObject();
                         JSONArray links = new JSONArray();
                         JSONArray collections = new JSONArray();
                         JSONObject link = new JSONObject();
                         link.put("rel", "self");
                         link.put("title", "This document");
                         link.put("type", "application/json");
                         link.put("href", wfsconf.get("baseurl") + "/collections?f=json");
                         links.put(link);
                         link = new JSONObject();
                         link.put("rel", "alternate");
                         link.put("title", "This document as XML");
                         link.put("type", "text/xml");
                         link.put("href", wfsconf.get("baseurl") + "/collections?f=gml");
                         links.put(link);
                         link = new JSONObject();
                         link.put("rel", "alternate");
                         link.put("title", "This document as HTML");
                         link.put("type", "text/html");
                         link.put("href", wfsconf.get("baseurl") + "/collections?f=html");
                         links.put(link);
                         link = new JSONObject();
                         link.put("rel", "describedBy");
                         link.put("title", "XML Schema for this dataset");
                         link.put("type", "application/xml");
                         link.put("href", "http://www.acme.com/3.0/wfs/collections/schema");
                         links.put(link);
                         result.put("links", links);
                         result.put("collections", collections);
                         for (int i = 0; i < wfsconf.getJSONArray("datasets").length(); i++) {
                                 JSONObject coll = new JSONObject();
                                 JSONObject curobj = wfsconf.getJSONArray("datasets").getJSONObject(i);
                                 coll.put("id", curobj.getString("name"));
                                 coll.put("name", curobj.getString("name"));
                                 coll.put("title", curobj.getString("name"));
                                 if(curobj.has("description"))
                                         coll.put("description", curobj.getString("description"));
                                 /*JSONObject extent = new JSONObject();
                                 JSONArray spatial = new JSONArray();
                                 JSONArray temporal=new JSONArray();
                                 temporal.put("1970-01-01T00:00:00Z");
                                 temporal.put("2020-08-22T22:10:44Z");*/
                                 JSONArray crs=new JSONArray();
                                 crs.put("http://www.opengis.net/def/crs/EPSG/0/"+curobj.getString("targetCRS").substring(curobj.getString("targetCRS").indexOf(":")+1));
                                 coll.put("storageCRS", "http://www.opengis.net/def/crs/EPSG/0/"+curobj.getString("targetCRS").substring(curobj.getString("targetCRS").indexOf(":")+1));
                                 coll.put("crs",crs);
                                 /*coll.put("extent", extent);
                                 extent.put("spatial", spatial);
                                 extent.put("temporal", temporal);*/
                                 JSONArray colinks = new JSONArray();
                                 for (ResultFormatter formatter : ResultFormatter.resultMap.values()) {
                                         link = new JSONObject();
                                         link.put("rel", "item");
                                         link.put("href", wfsconf.getString("baseurl") + "/collections/" + curobj.getString("name")
                                                         + "/items" + "?f=" + formatter.urlformat);
                                         link.put("type", formatter.exposedType);
                                         link.put("title", curobj.getString("name"));
                                         colinks.put(link);
                                 }
                                 link.put("rel", "self");
                                 link.put("title", "This document");
                                 link.put("type", "application/json");
                                 link.put("href", wfsconf.get("baseurl") + "/collections/"+curobj.getString("name")+"?f=json");
                                 colinks.put(link);
                                 link = new JSONObject();
                                 link.put("rel", "alternate");
                                 link.put("title", "This document as XML");
                                 link.put("type", "text/xml");
                                 link.put("href", wfsconf.get("baseurl") + "/collections/"+curobj.getString("name")+"?f=xml");
                                 colinks.put(link);
                                 link = new JSONObject();
                                 link.put("rel", "alternate");
                                 link.put("title", "This document as HTML");
                                 link.put("type", "text/html");
                                 link.put("href", wfsconf.get("baseurl") + "/collections/"+curobj.getString("name")+"?f=html");
                                 colinks.put(link);
                                 link = new JSONObject();
                                 link.put("rel", "describedBy");
                                 link.put("title", "XML Schema for this dataset");
                                 link.put("type", "application/xml");
                                 link.put("href", "http://www.acme.com/3.0/wfs/collections/"+curobj.getString("name")+"/schema");
                                 colinks.put(link);
                                 coll.put("links", colinks);
                                 collections.put(coll);
                         }
                         return Response.ok(result.toString(2)).type(ResultFormatter.getFormatter(format).mimeType).build();
                 } else if (format != null && format.contains("xml")) {
                         StringWriter strwriter = new StringWriter();
                         XMLOutputFactory output = XMLOutputFactory.newInstance();
                         XMLStreamWriter writer;
                         try {
                                 writer = new IndentingXMLStreamWriter(output.createXMLStreamWriter(strwriter));
                                 writer.writeStartDocument();
                                 writer.setDefaultNamespace("http://www.opengis.net/ogcapi-features-1/1.0");
                                 writer.setPrefix("atom", "http://www.w3.org/2005/Atom");
                                 writer.writeStartElement("Collections");
                                 writer.writeAttribute("xmlns", "http://www.opengis.net/ogcapi-features-1/1.0");
                                 writer.writeAttribute("xmlns:atom", "http://www.w3.org/2005/Atom");
                                 writer.writeAttribute("xmlns:xsi", "http://www.w3.org/2001/XMLSchema-instance");
                                 writer.writeAttribute("xmlns:sf", "http://www.opengis.net/ogcapi-features-1/1.0/sf");
                                 writer.writeAttribute("xmlns:gml", "http://www.opengis.net/gml/3.2");
                                 writer.writeAttribute("service", "OGCAPI-FEATURES");
                                 writer.writeAttribute("version", "1.0.0");
                                 writer.writeStartElement("Title");
                                 writer.writeCharacters(wfsconf.getString("servicetitle"));
                                 writer.writeEndElement();
                                 writer.writeStartElement("Description");
                                 writer.writeCharacters(" ");
                                 writer.writeEndElement();
                                 writer.writeStartElement("http://www.w3.org/2005/Atom", "link");
                                 writer.writeAttribute("rel", "self");
                                 writer.writeAttribute("title", "This document");
                                 writer.writeAttribute("type", "text/xml");
                                 writer.writeAttribute("href", wfsconf.get("baseurl") + "/collections?f=xml");
                                 writer.writeEndElement();
                                 writer.writeStartElement("http://www.w3.org/2005/Atom", "link");
                                 writer.writeAttribute("rel", "alternate");
                                 writer.writeAttribute("title", "This document as JSON");
                                 writer.writeAttribute("type", "application/json");
                                 writer.writeAttribute("href", wfsconf.get("baseurl") + "/collections?f=json");
                                 writer.writeEndElement();
                                 writer.writeStartElement("http://www.w3.org/2005/Atom", "link");
                                 writer.writeAttribute("rel", "alternate");
                                 writer.writeAttribute("title", "This document as HTML");
                                 writer.writeAttribute("type", "application/json");
                                 writer.writeAttribute("href", wfsconf.get("baseurl") + "/collections?f=html");
                                 writer.writeEndElement();
                                 writer.writeStartElement("http://www.w3.org/2005/Atom", "link");
                                 writer.writeAttribute("rel", "describedBy");
                                 writer.writeAttribute("title", "XML Schema for this dataset");
                                 writer.writeAttribute("type", "application/xml");
                                 writer.writeAttribute("href", "http://www.acme.com/3.0/wfs/collections/schema");
                                 writer.writeEndElement();
                                 for (int i = 0; i < wfsconf.getJSONArray("datasets").length(); i++) {
                                         JSONObject curobj = wfsconf.getJSONArray("datasets").getJSONObject(i);
                                         writer.writeStartElement("Collection");
                                         writer.writeStartElement("Id");
                                         writer.writeCharacters(curobj.getString("name"));
                                         writer.writeEndElement();
                                         writer.writeStartElement("Title");
                                         writer.writeCharacters(curobj.getString("name"));
                                         writer.writeEndElement();
                                         writer.writeStartElement("Description");
                                         if(curobj.has("description"))
                                                 writer.writeCharacters(curobj.getString("description"));
                                         else {
                                                 writer.writeCharacters("");
                                         }
                                         writer.writeEndElement();
                                         for (ResultFormatter formatter : ResultFormatter.resultMap.values()) {
                                                 writer.writeStartElement("http://www.w3.org/2005/Atom", "link");
                                                 writer.writeAttribute("rel", "items");
                                                 writer.writeAttribute("title", curobj.getString("name"));
                                                 writer.writeAttribute("type", formatter.exposedType);
                                                 writer.writeAttribute("href", wfsconf.getString("baseurl") + "/collections/"
                                                                 + curobj.getString("name") + "/items?f=" + formatter.exposedType);
                                                 writer.writeEndElement();
                                         }
                                         writer.writeEndElement();
                                         /*writer.writeStartElement("Extent");
                                         writer.writeStartElement("Spatial");
                                         writer.writeAttribute("crs", "http://www.opengis.net/def/crs/OGC/1.3/CRS84");
                                         writer.writeEndElement();
                                         writer.writeEndElement();*/
                                 }
                                 writer.writeEndElement();
                                 writer.writeEndDocument();
                                 writer.flush();
                                 return Response.ok(strwriter.toString()).type(ResultFormatter.getFormatter(format).mimeType).build();
                         } catch (XMLStreamException e) {
                                 // TODO Auto-generated catch block
                                 e.printStackTrace();
                                 return this.createExceptionResponse(e, "");
                         }
                 } else if (format == null || format.contains("html")) {
                         StringBuilder builder = new StringBuilder();
                         builder.append(htmlHead);
                         builder.append("<header id=\"header\"><div class=\"page-header\"><h1 align=center>");
                         builder.append("FeatureCollection View");
                         builder.append("</h1></div></header>");
                         builder.append("<div class=\"sticky row crumbs\"><div class=\"col-sm-12 col-md-10 col-md-offset-1\">");
                         builder.append("<a href=\""+wfsconf.getString("baseurl")+"\">Landingpage</a> / <a href=\""+wfsconf.getString("baseurl")+"/collections/\">Collections</a>");
                     builder.append("</div></div>");
                         builder.append(
                                         "<div class=\"container-fluid\" role=\"main\"><div class=\"row\"><div class=\"col-sm-12\"><table class=\"description\" id=\"collectiontable\" width=100% border=1><thead><tr><th>Collection</th><th>Description</th><th>Schema</th></tr></thead><tbody>");
                         for (int i = 0; i < wfsconf.getJSONArray("datasets").length(); i++) {
                                 JSONObject curobj = wfsconf.getJSONArray("datasets").getJSONObject(i);
                                 if(i%2==0){
                                     builder.append("<tr class=\"even\">");
                                 }else{
                                     builder.append("<tr class=\"odd\">");
                                 }
                                 builder.append("<td align=center><a href=\"" + wfsconf.getString("baseurl") + "/collections/"
                                                 + wfsconf.getJSONArray("datasets").getJSONObject(i).get("name") + "?f=html\">"
                                                 + wfsconf.getJSONArray("datasets").getJSONObject(i).get("name") + "</a></td><td align=center>");
                                 if (wfsconf.getJSONArray("datasets").getJSONObject(i).has("description")) {
                                         builder.append(wfsconf.getJSONArray("datasets").getJSONObject(i).get("description"));
                                 }
                                 builder.append("</td><td align=center>");
                                 if (wfsconf.getJSONArray("datasets").getJSONObject(i).has("schema")) {
                                         builder.append("<a href=\"" + wfsconf.getJSONArray("datasets").getJSONObject(i).get("schema")
                                                         + "\" target=\"_blank\">[Schema]</a>");
                                 } else {
                                         builder.append("<a href=\"" + wfsconf.getString("baseurl") + "/collections/"
                                                         + curobj.getString("name") + "/schema\" target=\"_blank\">[XML Schema]</a><br/>");
                                         builder.append("<a href=\"" + wfsconf.getString("baseurl") + "/collections/"
                                                         + curobj.getString("name") + "/schema?f=json\" target=\"_blank\">[JSON Schema]</a>");
                                 }
                                 /*builder.append("</td><td align=center>");
                                 Integer counter = 0;
                                 for (ResultFormatter formatter : ResultFormatter.resultMap.values()) {
                                         if (counter % 4 == 0) {
                                                 builder.append("<br>");
                                         }
                                         builder.append("<a href=\"" + wfsconf.getString("baseurl") + "/collections/"
                                                         + curobj.getString("name") + "/items?f=" + formatter.exposedType + "\">["
                                                         + formatter.exposedType.toUpperCase() + "]</a>&nbsp;&nbsp;");
                                         counter++;
                                 }*/
                                 builder.append("</td></tr>");
                         }
                         builder.append("</tbody></table>");
                         builder.append("</div></div></div><footer id=\"footer\"><table width=100%><tbody><tr><td><a href=\"" + wfsconf.getString("baseurl")
                                         + "/?f=html\">Back to LandingPage</a></td><td align=right>This page in <a href=\""
                                         + wfsconf.getString("baseurl") + "/collections?f=gml\">[XML]</a> <a href=\""
                                         + wfsconf.getString("baseurl")
                                         + "/collections?f=json\">[JSON]</a></td></tr></table></footer><script>$('#collectiontable').DataTable();</script></body></html>");
                         return Response.ok(builder.toString()).type(ResultFormatter.getFormatter(format).mimeType).build();
                 } else {
                         throw new NotFoundException();
                 }
         }
collectionsHTML()
Response collectionsHTML (@Parameter(description="Return format") @DefaultValue("html") @QueryParam("f") String format)
{
                 return collections(format);
         }
collectionsJSON()
Response collectionsJSON (@Parameter(description="Return format") @DefaultValue("json") @QueryParam("f") String format)
{
                 return collections(format);
         }
collectionsXML()
Response collectionsXML (@Parameter(description="Return format") @DefaultValue("xml") @QueryParam("f") String format)
{
                 return collections(format);
         }
conformance()
Response conformance (@Parameter(description="The format of the conformance page") @DefaultValue("html") @QueryParam("f") String format)
Gets conformance information about the OGC API Features service.
Parameters
format The return format for the conformance declaration
Returns
The conformance declaration as String
{
                 if (format != null && format.contains("json")) {
                         JSONObject result = new JSONObject();
                         JSONArray conforms = new JSONArray();
                         conforms.put("http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core");
                         conforms.put("http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30");
                         conforms.put("http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/html");
                         conforms.put("http://www.opengis.net/spec/ogcapi-features-2/1.0/conf/crs");
                         conforms.put("http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson");
                         conforms.put("http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/gmlsf0");
                         result.put("conformsTo", conforms);
                         return Response.ok(result.toString(2)).type(MediaType.APPLICATION_JSON).build();
                 } else if (format != null && format.contains("xml")) {
                         StringWriter strwriter = new StringWriter();
                         XMLOutputFactory output = XMLOutputFactory.newInstance();
                         XMLStreamWriter writer;
                         try {
                                 writer = new IndentingXMLStreamWriter(output.createXMLStreamWriter(strwriter));
                                 writer.writeStartDocument();
                                 writer.setDefaultNamespace("http://www.opengis.net/ogcapi-features-1/1.0");
                                 writer.writeStartElement("ConformsTo");
                                 writer.writeAttribute("service", "OGCAPI-FEATURES");
                                 writer.writeAttribute("version", "1.0.0");
                                 writer.writeNamespace(null, "http://www.opengis.net/ogcapi-features-1/1.0");
                                 writer.writeNamespace("atom", "http://www.w3.org/2005/Atom");
                                 writer.writeNamespace("xsi", "http://www.w3.org/2001/XMLSchema-instance");
                                 writer.writeAttribute("xsi:schemaLocation",
                                                 "http://www.opengis.net/ogcapi-features-1/1.0../../xml/core.xsd");
                                 writer.writeStartElement("atom:link");
                                 writer.writeAttribute("href", "http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core");
                                 writer.writeEndElement();
                                 writer.writeStartElement("atom:link");
                                 writer.writeAttribute("href", "http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30");
                                 writer.writeEndElement();
                                 writer.writeStartElement("atom:link");
                                 writer.writeAttribute("href", "http://www.opengis.net/spec/ogcapi-features-2/1.0/conf/crs");
                                 writer.writeEndElement();
                                 writer.writeStartElement("atom:link");
                                 writer.writeAttribute("href", "http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/html");
                                 writer.writeEndElement();
                                 writer.writeStartElement("atom:link");
                                 writer.writeAttribute("href", "http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson");
                                 writer.writeEndElement();
                                 writer.writeStartElement("atom:link");
                                 writer.writeAttribute("href", "http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/gmlsf0");
                                 writer.writeEndElement();
                                 writer.writeEndElement();
                                 writer.writeEndDocument();
                                 writer.flush();
                                 return Response.ok(strwriter.toString()).type(MediaType.APPLICATION_XML).build();
                         } catch (XMLStreamException e) {
                                 e.printStackTrace();
                                 return this.createExceptionResponse(e, "");
                         }
                 } else if (format == null || format.contains("html")) {
                         StringBuilder builder = new StringBuilder();
                         builder.append("<html><head>" + htmlHead
                                         + "</head><body><header id=\"header\"><h1 align=\"center\">Conformance</h1></header><div class=\"container-fluid\" role=\"main\"><div class=\"row\"><div class=\"col-sm-12\"><ul>");
                         builder.append(
                                         "<li><a target=\"_blank\" href=\"http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core\">Core</a></li>");
                         builder.append(
                                         "<li><a target=\"_blank\" href=\"http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30\">Oas30</a></li>");
                         builder.append(
                                         "<li><a target=\"_blank\" href=\"http://www.opengis.net/spec/ogcapi-features-2/1.0/conf/crs\">Crs</a></li>");
                         builder.append(
                                         "<li><a target=\"_blank\" href=\"http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/html\">HTML</a></li>");
                         builder.append(
                                         "<li><a target=\"_blank\" href=\"http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson\">GeoJSON</a></li>");
                         builder.append(
                                         "<li><a target=\"_blank\" href=\"http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/gmlsf0\">GMLSf0</a></li>");
                         builder.append("</ul></div></div></div><footer id=\"footer\"><table width=\"100%\"><tbody><tr><td><a href=\"" + wfsconf.getString("baseurl")
                                         + "/?f=html\">Back to LandingPage</a></td><td align=right>This page in <a href=\""
                                         + wfsconf.getString("baseurl") + "/conformance?f=gml\">[GML]</a> <a href=\"" + wfsconf.getString("baseurl")
                                         + "/conformance?f=geojson\">[JSON]</a></td></tr></tbody></table></footer></body></html>");
                         return Response.ok(builder.toString()).type(MediaType.TEXT_HTML).build();
                 } else {
                         throw new NotFoundException();
                 }
         }
conformanceHTML()
Response conformanceHTML (@Parameter(description="The format of the conformance page") @DefaultValue("html") @QueryParam("f") String format)
{
                 return conformance(format);
         }
conformanceJSON()
Response conformanceJSON (@Parameter(description="The format of the conformance page") @DefaultValue("json") @QueryParam("f") String format)
{
                 return conformance(format);
         }
conformanceXML()
Response conformanceXML (@Parameter(description="The format of the conformance page") @DefaultValue("xml") @QueryParam("f") String format)
{
                 return conformance(format);
         }
constructCapabilities()
Response constructCapabilities (String version, String versionnamespace) throws XMLStreamException
Constructs a capabilities document for a WFS in version 1.1 .
Parameters
version The version of the WFS service
versionnamespace The namespace to use
Returns
The capabilities document as String
Exceptions
XMLStreamException on error
{
                 String serviceType = "WFS";
                 String owsns = "http://www.opengis.net/ows/1.1";
                 if ("1.0.0".equals(version))
                         return constructCapabilitiesWFS10(version, versionnamespace);
                 if ("1.0.0".equals(version) || "1.1.0".equals(version)) {
                         versionnamespace = "";
                 } else {
                         versionnamespace = "/" + versionnamespace;
                 }
                 XMLOutputFactory factory = XMLOutputFactory.newInstance();
                 StringWriter strwriter = new StringWriter();
                 XMLStreamWriter xmlwriter = factory.createXMLStreamWriter(strwriter);
                 IndentingXMLStreamWriter writer = new IndentingXMLStreamWriter(xmlwriter);
                 writer.writeStartDocument();
                 writer.writeStartElement("WFS_Capabilities");
                 writer.setPrefix("wfs", "http://www.opengis.net/wfs" + versionnamespace);
                 writer.writeDefaultNamespace("http://www.opengis.net/wfs" + versionnamespace);
                 writer.writeAttribute("version", version);
                 writer.writeNamespace("xsi", "http://www.w3.org/2001/XMLSchema-instance");
                 writer.writeNamespace("wfs", "http://www.opengis.net/wfs" + versionnamespace);
                 writer.writeNamespace("ows", "http://www.opengis.net/ows/1.1");
                 writer.writeNamespace("sf", "http://www.opengis.net/ogcapi-features-1/1.0/sf");
                 writer.writeNamespace("ogc", "http://www.opengis.net/ogc");
                 writer.writeNamespace("fes", "http://www.opengis.net/fes" + versionnamespace);
                 writer.writeNamespace("gml", "http://www.opengis.net/gml");
                 writer.writeNamespace("xlink", "http://www.w3.org/1999/xlink");
                 writer.writeAttribute("xsi:schemaLocation", "http://www.opengis.net/wfs" + versionnamespace+" http://schemas.opengis.net/wfs/"+versionnamespace+"/wfs.xsd http://inspire.ec.europa.eu/schemas/inspire_dls/1.0 http://inspire.ec.europa.eu/schemas/inspire_dls/1.0/inspire_dls.xsd");
                 // ServiceInformation
                 writer.writeStartElement(owsns, "ServiceIdentification");
                 writer.writeStartElement(owsns, "ServiceType");
                 writer.writeAttribute("codeSpace", "OGC");
                 writer.writeCharacters(serviceType);
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "ServiceTypeVersion");
                 writer.writeCharacters(version);
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "Title");
                 writer.writeCharacters(wfsconf.has("servicetitle") ? wfsconf.getString("servicetitle") : "");
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "Fees");
                 writer.writeCharacters(wfsconf.has("fees") ? wfsconf.getString("fees") : "none");
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "Abstract");
                 writer.writeCharacters(wfsconf.has("abstract") ? wfsconf.getString("abstract") : "");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "OperationsMetadata");
                 writer.writeStartElement(owsns, "Operation");
                 writer.writeAttribute("name", "GetCapabilities");
                 writer.writeStartElement(owsns, "DCP");
                 writer.writeStartElement(owsns, "HTTP");
                 writer.writeStartElement(owsns, "Get");
                 writer.writeAttribute("xlink:type", "simple");
                 writer.writeAttribute("xlink:href", wfsconf.getString("baseurl") + "/wfs?");
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "Post");
                 writer.writeAttribute("xlink:type", "simple");
                 writer.writeAttribute("xlink:href", wfsconf.getString("baseurl") + "/wfs");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "Parameter");
                 writer.writeAttribute("name", "AcceptVersions");
                 writer.writeStartElement(owsns, "AllowedValues");
                 writer.writeStartElement(owsns, "Value");
                 writer.writeCharacters(version);
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "Operation");
                 writer.writeAttribute("name", "GetPropertyValue");
                 writer.writeStartElement(owsns, "DCP");
                 writer.writeStartElement(owsns, "HTTP");
                 writer.writeStartElement(owsns, "Get");
                 writer.writeAttribute("xlink:type", "simple");
                 writer.writeAttribute("xlink:href", wfsconf.getString("baseurl") + "/wfs?");
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "Post");
                 writer.writeAttribute("xlink:type", "simple");
                 writer.writeAttribute("xlink:href", wfsconf.getString("baseurl") + "/wfs");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "Operation");
                 writer.writeAttribute("name", "DescribeFeatureType");
                 writer.writeStartElement(owsns, "DCP");
                 writer.writeStartElement(owsns, "HTTP");
                 writer.writeStartElement(owsns, "Get");
                 writer.writeAttribute("xlink:type", "simple");
                 writer.writeAttribute("xlink:href", wfsconf.getString("baseurl") + "/wfs?");
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "Post");
                 writer.writeAttribute("xlink:type", "simple");
                 writer.writeAttribute("xlink:href", wfsconf.getString("baseurl") + "/wfs");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "Operation");
                 writer.writeAttribute("name", "GetGmlObject");
                 writer.writeStartElement(owsns, "DCP");
                 writer.writeStartElement(owsns, "HTTP");
                 writer.writeStartElement(owsns, "Get");
                 writer.writeAttribute("xlink:type", "simple");
                 writer.writeAttribute("xlink:href", wfsconf.getString("baseurl") + "/wfs?");
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "Post");
                 writer.writeAttribute("xlink:type", "simple");
                 writer.writeAttribute("xlink:href", wfsconf.getString("baseurl") + "/wfs");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "Operation");
                 writer.writeAttribute("name", "GetFeature");
                 writer.writeStartElement(owsns, "DCP");
                 writer.writeStartElement(owsns, "HTTP");
                 writer.writeStartElement(owsns, "Get");
                 writer.writeAttribute("xlink:type", "simple");
                 writer.writeAttribute("xlink:href", wfsconf.getString("baseurl") + "/wfs?");
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "Post");
                 writer.writeAttribute("xlink:type", "simple");
                 writer.writeAttribute("xlink:href", wfsconf.getString("baseurl") + "/wfs");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "Parameter");
                 writer.writeAttribute("name", "AcceptVersions");
                 writer.writeStartElement(owsns, "AllowedValues");
                 writer.writeStartElement(owsns, "Value");
                 writer.writeCharacters(version);
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(owsns,"Constraint");
                 writer.writeAttribute("name", "ImplementsBasicWFS");
                 writer.writeStartElement(owsns,"DefaultValue");
                 writer.writeCharacters("TRUE");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(owsns,"Constraint");
                 writer.writeAttribute("name", "ImplementsTransactionalWFS");
                 writer.writeStartElement(owsns,"DefaultValue");
                 writer.writeCharacters("TRUE");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(owsns,"Constraint");
                 writer.writeAttribute("name", "KVPEncoding");
                 writer.writeStartElement(owsns,"DefaultValue");
                 writer.writeCharacters("TRUE");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(owsns,"Constraint");
                 writer.writeAttribute("name", "ImplementsAdHocQuery");
                 writer.writeStartElement(owsns,"DefaultValue");
                 writer.writeCharacters("TRUE");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(owsns,"Constraint");
                 writer.writeAttribute("name", "ImplementsResourceId");
                 writer.writeStartElement(owsns,"DefaultValue");
                 writer.writeCharacters("TRUE");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(owsns,"Constraint");
                 writer.writeAttribute("name", "ImplementsMinStandardFilter");
                 writer.writeStartElement(owsns,"DefaultValue");
                 writer.writeCharacters("TRUE");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(owsns,"Constraint");
                 writer.writeAttribute("name", "ImplementsMinTemporalFilter");
                 writer.writeStartElement(owsns,"DefaultValue");
                 writer.writeCharacters("TRUE");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(owsns,"Constraint");
                 writer.writeAttribute("name", "ImplementsMinimumXPath");
                 writer.writeStartElement(owsns,"DefaultValue");
                 writer.writeCharacters("TRUE");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(owsns,"Constraint");
                 writer.writeAttribute("name", "ImplementsResultPaging");
                 writer.writeStartElement(owsns,"DefaultValue");
                 writer.writeCharacters("TRUE");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement("http://www.opengis.net/wfs" + versionnamespace, "FeatureTypeList");
                 writer.writeStartElement("http://www.opengis.net/wfs" + versionnamespace, "Operations");
                 writer.writeStartElement("http://www.opengis.net/wfs" + versionnamespace, "Operation");
                 writer.writeCharacters("Query");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 for (int i = 0; i < wfsconf.getJSONArray("datasets").length(); i++) {
                         describeFeatureType(writer, wfsconf.getJSONArray("datasets").getJSONObject(i), versionnamespace, version);
                 }
                 writer.writeEndElement();
                 writer.writeStartElement("http://www.opengis.net/fes" + versionnamespace, "Filter_Capabilities");
                 describeConformance(writer,versionnamespace,"http://www.opengis.net/fes"+versionnamespace);
                 describeSpatialCapabilities(writer, versionnamespace, "http://www.opengis.net/fes" + versionnamespace);
                 describeScalarCapabilities(writer, versionnamespace, "http://www.opengis.net/fes" + versionnamespace);
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndDocument();
                 return Response.ok(strwriter.toString()).type(MediaType.APPLICATION_XML).build();
         }
constructCapabilitiesCSW()
Response constructCapabilitiesCSW (String version, String versionnamespace) throws XMLStreamException
Constructs a capabilities document for a CSW service .
Parameters
version The version of the WFS service
versionnamespace The namespace to use
Returns
The capabilities document as String
Exceptions
XMLStreamException on error
{
                 String serviceType = "CSW";
                 String owsns = "http://www.opengis.net/ows/1.1";
                 XMLOutputFactory factory = XMLOutputFactory.newInstance();
                 StringWriter strwriter = new StringWriter();
                 XMLStreamWriter xmlwriter;
                 xmlwriter = factory.createXMLStreamWriter(strwriter);
                 IndentingXMLStreamWriter writer = new IndentingXMLStreamWriter(xmlwriter);
                 writer.writeStartDocument();
                 writer.setPrefix("csw", "http://www.opengis.net/cat/csw/" + versionnamespace);
                 writer.writeStartElement("http://www.opengis.net/cat/csw/" + versionnamespace, "Capabilities");
                 writer.writeDefaultNamespace("http://www.opengis.net/wfs" + versionnamespace);
                 writer.writeAttribute("version", version);
                 writer.writeNamespace("csw", "http://www.opengis.net/cat/csw/" + versionnamespace);
                 writer.writeNamespace("wfs", "http://www.opengis.net/wfs" + versionnamespace);
                 writer.writeNamespace("ows", "http://www.opengis.net/ows/1.1");
                 writer.writeNamespace("sf", "http://www.opengis.net/ogcapi-features-1/1.0/sf");
                 writer.writeNamespace("ogc", "http://www.opengis.net/ogc");
                 writer.writeNamespace("fes", "http://www.opengis.net/fes" + versionnamespace);
                 writer.writeNamespace("gml", "http://www.opengis.net/gml");
                 writer.writeNamespace("xlink", "http://www.w3.org/1999/xlink");
                 writer.writeStartElement(owsns, "ServiceIdentification");
                 writer.writeStartElement(owsns, "ServiceType");
                 writer.writeAttribute("codeSpace", "OGC");
                 writer.writeCharacters(serviceType);
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "ServiceTypeVersion");
                 writer.writeCharacters(version);
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "Title");
                 writer.writeCharacters(
                                 wfsconf.has("servicetitle") ? wfsconf.getString("servicetitle").replace("WFS", "CSW") : "");
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "Fees");
                 writer.writeCharacters(wfsconf.has("fees") ? wfsconf.getString("fees") : "none");
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "Abstract");
                 writer.writeCharacters(wfsconf.has("abstract") ? wfsconf.getString("abstract") : "");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "OperationsMetadata");
                 writer.writeStartElement(owsns, "Operation");
                 writer.writeAttribute("name", "GetCapabilities");
                 writer.writeStartElement(owsns, "DCP");
                 writer.writeStartElement(owsns, "HTTP");
                 writer.writeStartElement(owsns, "Get");
                 writer.writeAttribute("xlink:type", "simple");
                 writer.writeAttribute("xlink:href", wfsconf.getString("baseurl") + "/csw?");
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "Post");
                 writer.writeAttribute("xlink:type", "simple");
                 writer.writeAttribute("xlink:href", wfsconf.getString("baseurl") + "/csw");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "Parameter");
                 writer.writeAttribute("name", "sections");
                 writer.writeStartElement(owsns, "Value");
                 writer.writeCharacters("ServiceIdentification");
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "Value");
                 writer.writeCharacters("ServiceProvider");
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "Value");
                 writer.writeCharacters("OperationsMetadata");
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "Value");
                 writer.writeCharacters("Filter_Capabilities");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "Operation");
                 writer.writeAttribute("name", "DescribeRecord");
                 writer.writeStartElement(owsns, "DCP");
                 writer.writeStartElement(owsns, "HTTP");
                 writer.writeStartElement(owsns, "Get");
                 writer.writeAttribute("xlink:type", "simple");
                 writer.writeAttribute("xlink:href", wfsconf.getString("baseurl") + "/csw?");
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "Post");
                 writer.writeAttribute("xlink:type", "simple");
                 writer.writeAttribute("xlink:href", wfsconf.getString("baseurl") + "/csw");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "Operation");
                 writer.writeAttribute("name", "GetRecords");
                 writer.writeStartElement(owsns, "DCP");
                 writer.writeStartElement(owsns, "HTTP");
                 writer.writeStartElement(owsns, "Get");
                 writer.writeAttribute("xlink:type", "simple");
                 writer.writeAttribute("xlink:href", wfsconf.getString("baseurl") + "/csw?");
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "Post");
                 writer.writeAttribute("xlink:type", "simple");
                 writer.writeAttribute("xlink:href", wfsconf.getString("baseurl") + "/csw");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "Operation");
                 writer.writeAttribute("name", "GetRecordById");
                 writer.writeStartElement(owsns, "DCP");
                 writer.writeStartElement(owsns, "HTTP");
                 writer.writeStartElement(owsns, "Get");
                 writer.writeAttribute("xlink:type", "simple");
                 writer.writeAttribute("xlink:href", wfsconf.getString("baseurl") + "/csw?");
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "Post");
                 writer.writeAttribute("xlink:type", "simple");
                 writer.writeAttribute("xlink:href", wfsconf.getString("baseurl") + "/csw");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "Operation");
                 writer.writeAttribute("name", "Harvest");
                 writer.writeStartElement(owsns, "DCP");
                 writer.writeStartElement(owsns, "HTTP");
                 writer.writeStartElement(owsns, "Get");
                 writer.writeAttribute("xlink:type", "simple");
                 writer.writeAttribute("xlink:href", wfsconf.getString("baseurl") + "/csw?");
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "Post");
                 writer.writeAttribute("xlink:type", "simple");
                 writer.writeAttribute("xlink:href", wfsconf.getString("baseurl") + "/csw");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(owsns, "Parameter");
                 writer.writeAttribute("name", "AcceptVersions");
                 writer.writeStartElement(owsns, "AllowedValues");
                 writer.writeStartElement(owsns, "Value");
                 writer.writeCharacters(version);
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement("http://www.opengis.net/fes" + versionnamespace, "Filter_Capabilities");
                 describeConformance(writer, versionnamespace, "http://www.opengis.net/fes" + versionnamespace);
                 describeSpatialCapabilities(writer, versionnamespace, "http://www.opengis.net/fes" + versionnamespace);
                 describeScalarCapabilities(writer, versionnamespace, "http://www.opengis.net/fes" + versionnamespace);
                 writer.writeEndElement();
                 writer.writeEndDocument();
                 return Response.ok(strwriter.toString()).type(MediaType.APPLICATION_XML).build();
         }
constructCapabilitiesWFS10()
Response constructCapabilitiesWFS10 (String version, String versionnamespace) throws XMLStreamException
Constructs a capabilities document for a WFS in version 1.0 .
Parameters
version The version of the WFS service
versionnamespace The namespace to use
Returns
The capabilities document as String
Exceptions
XMLStreamException on error
References ResultFormatter.resultMap.
{
                 XMLOutputFactory factory = XMLOutputFactory.newInstance();
                 StringWriter strwriter = new StringWriter();
                 XMLStreamWriter xmlwriter = factory.createXMLStreamWriter(strwriter);
                 IndentingXMLStreamWriter writer = new IndentingXMLStreamWriter(xmlwriter);
                 writer.writeStartDocument();
                 writer.writeStartElement("WFS_Capabilities");
                 writer.setPrefix("wfs", "http://www.opengis.net/wfs");
                 writer.writeDefaultNamespace("http://www.opengis.net/wfs");
                 writer.writeAttribute("version", version);
                 writer.writeNamespace("wfs", "http://www.opengis.net/wfs");
                 writer.writeNamespace("ows", "http://www.opengis.net/ows/1.1");
                 writer.writeNamespace("ogc", "http://www.opengis.net/ogc");
                 writer.writeNamespace("gml", "http://www.opengis.net/gml");
                 writer.writeNamespace("xlink", "http://www.w3.org/1999/xlink");
                 writer.writeStartElement("Service");
                 writer.writeStartElement("Name");
                 writer.writeCharacters(wfsconf.has("servicetitle") ? wfsconf.getString("servicetitle") : "");
                 writer.writeEndElement();
                 writer.writeStartElement("Title");
                 writer.writeCharacters(wfsconf.has("servicetitle") ? wfsconf.getString("servicetitle") : "");
                 writer.writeEndElement();
                 writer.writeStartElement("Abstract");
                 writer.writeCharacters(wfsconf.has("abstract") ? wfsconf.getString("abstract") : "");
                 writer.writeEndElement();
                 writer.writeStartElement("Fees");
                 writer.writeCharacters(wfsconf.has("fees") ? wfsconf.getString("fees") : "none");
                 writer.writeEndElement();
                 writer.writeStartElement("OnlineResource");
                 writer.writeCharacters(wfsconf.has("baseurl") ? wfsconf.getString("baseurl") : "");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement("Capability");
                 writer.writeStartElement("Request");
                 writer.writeStartElement("GetCapabilities");
                 writer.writeStartElement("DCPType");
                 writer.writeStartElement("HTTP");
                 writer.writeStartElement("Get");
                 writer.writeAttribute("onlineResource", wfsconf.getString("baseurl") + "/wfs?");
                 writer.writeEndElement();
                 writer.writeStartElement("Post");
                 writer.writeAttribute("onlineResource", wfsconf.getString("baseurl") + "/wfs");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement("GetGmlObject");
                 writer.writeStartElement("DCPType");
                 writer.writeStartElement("HTTP");
                 writer.writeStartElement("Get");
                 writer.writeAttribute("onlineResource", wfsconf.getString("baseurl") + "/wfs?");
                 writer.writeEndElement();
                 writer.writeStartElement("Post");
                 writer.writeAttribute("onlineResource", wfsconf.getString("baseurl") + "/wfs");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement("GetPropertyValue");
                 writer.writeStartElement("DCPType");
                 writer.writeStartElement("HTTP");
                 writer.writeStartElement("Get");
                 writer.writeAttribute("onlineResource", wfsconf.getString("baseurl") + "/wfs?");
                 writer.writeEndElement();
                 writer.writeStartElement("Post");
                 writer.writeAttribute("onlineResource", wfsconf.getString("baseurl") + "/wfs");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement("DescribeFeatureType");
                 writer.writeStartElement("SchemaDescriptionLanguage");
                 writer.writeStartElement("XMLSCHEMA");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement("DCPType");
                 writer.writeStartElement("HTTP");
                 writer.writeStartElement("Get");
                 writer.writeAttribute("onlineResource", wfsconf.getString("baseurl") + "/wfs?");
                 writer.writeEndElement();
                 writer.writeStartElement("Post");
                 writer.writeAttribute("onlineResource", wfsconf.getString("baseurl") + "/wfs");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement("GetFeature");
                 writer.writeStartElement("ResultFormat");
                 for (ResultFormatter format : ResultFormatter.resultMap.values()) {
                         if (!format.exposedType.isEmpty()) {
                                 if (format.exposedType.contains("/")) {
                                         writer.writeStartElement(format.exposedType.substring(format.exposedType.lastIndexOf('/') + 1)
                                                         .replace("+", "").toUpperCase());
                                         writer.writeEndElement();
                                 } else {
                                         writer.writeStartElement(format.exposedType.toUpperCase());
                                         writer.writeEndElement();
                                 }
                         }
                 }
                 writer.writeEndElement();
                 writer.writeStartElement("DCPType");
                 writer.writeStartElement("HTTP");
                 writer.writeStartElement("Get");
                 writer.writeAttribute("onlineResource", wfsconf.getString("baseurl") + "/wfs?");
                 writer.writeEndElement();
                 writer.writeStartElement("Post");
                 writer.writeAttribute("onlineResource", wfsconf.getString("baseurl") + "/wfs");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement("FeatureTypeList");
                 writer.writeStartElement("Operations");
                 writer.writeStartElement("Query");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 for (int i = 0; i < wfsconf.getJSONArray("datasets").length(); i++) {
                         describeFeatureTypeWFS10(writer, wfsconf.getJSONArray("datasets").getJSONObject(i), versionnamespace,
                                         version);
                 }
                 writer.writeEndElement();
                 writer.writeStartElement("http://www.opengis.net/ogc", "Filter_Capabilities");
                 describeSpatialCapabilitiesWFS10(writer, versionnamespace, "http://www.opengis.net/ogc");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndDocument();
                 return Response.ok(strwriter.toString()).type(MediaType.APPLICATION_XML).build();
         }
createExceptionResponse()
Response createExceptionResponse (Exception e, String format)
Generates an exception response.
Parameters
e The exception to get the message from
format The return format
Returns
The exception response
{
                 if (format == null || format.equals("gml")) {
                         StringWriter strwriter = new StringWriter();
                         XMLOutputFactory output = XMLOutputFactory.newInstance();
                         XMLStreamWriter writer;
                         try {
                                 writer = new IndentingXMLStreamWriter(output.createXMLStreamWriter(strwriter));
                                 writer.writeStartDocument();
                                 writer.writeStartElement("ExceptionReport");
                                 writer.setDefaultNamespace("http://www.opengis.net/ogc");
                                 writer.writeNamespace("xsi", "https://www.w3.org/2001/XMLSchema-instance");
                                 writer.writeStartElement("Exception");
                                 writer.writeAttribute("locator", e.getStackTrace()[0].getClassName());
                                 writer.writeStartElement("ExceptionText");
                                 writer.writeCharacters(e.getMessage());
                                 writer.writeEndElement();
                                 writer.writeEndElement();
                                 writer.writeEndDocument();
                                 writer.flush();
                         } catch (XMLStreamException e1) {
                                 // TODO Auto-generated catch block
                                 e1.printStackTrace();
                                 return Response.ok("").type(MediaType.APPLICATION_XML).build();
                         }
                         return Response.ok(strwriter.toString()).type(MediaType.APPLICATION_XML).build();
                 }
                 return Response.ok("").type(MediaType.APPLICATION_XML).build();
         }
describeConformance()
void describeConformance (IndentingXMLStreamWriter writer, String versionnamespace, String namespace) throws XMLStreamException
Describes the conformance part of a WFS webservices.
Parameters
writer The XML writer
versionnamespace The versionnamespace
namespace The namespace to follow
Exceptions
XMLStreamException on error
{
                 System.out.println(namespace);
                 writer.writeStartElement(namespace,"Conformance");
                 writer.writeStartElement(namespace,"Constraint");
                 writer.writeAttribute("name","ImplementsQuery");
                 writer.writeStartElement("http://www.opengis.net/ows/1.1","DefaultValue");
                 writer.writeCharacters("TRUE");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(namespace,"Constraint");
                 writer.writeAttribute("name","ImplementsAdHocQuery");
                 writer.writeStartElement("http://www.opengis.net/ows/1.1","DefaultValue");
                 writer.writeCharacters("TRUE");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(namespace,"Constraint");
                 writer.writeAttribute("name","ImplementsFunctions");
                 writer.writeStartElement("http://www.opengis.net/ows/1.1","DefaultValue");
                 writer.writeCharacters("TRUE");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(namespace,"Constraint");
                 writer.writeAttribute("name","ImplementsMinStandardFilter");
                 writer.writeStartElement("http://www.opengis.net/ows/1.1","DefaultValue");
                 writer.writeCharacters("TRUE");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(namespace,"Constraint");
                 writer.writeAttribute("name","ImplementsMinSpatialFilter");
                 writer.writeStartElement("http://www.opengis.net/ows/1.1","DefaultValue");
                 writer.writeCharacters("TRUE");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(namespace,"Constraint");
                 writer.writeAttribute("name","ImplementsSpatialFilter");
                 writer.writeStartElement("http://www.opengis.net/ows/1.1","DefaultValue");
                 writer.writeCharacters("TRUE");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(namespace,"Constraint");
                 writer.writeAttribute("name","ImplementsMinTemporalFilter");
                 writer.writeStartElement("http://www.opengis.net/ows/1.1","DefaultValue");
                 writer.writeCharacters("TRUE");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(namespace,"Constraint");
                 writer.writeAttribute("name","ImplementsResourceId");
                 writer.writeStartElement("http://www.opengis.net/ows/1.1","DefaultValue");
                 writer.writeCharacters("TRUE");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(namespace,"Constraint");
                 writer.writeAttribute("name","ImplementsMinimumXPath");
                 writer.writeStartElement("http://www.opengis.net/ows/1.1","DefaultValue");
                 writer.writeCharacters("TRUE");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(namespace,"Constraint");
                 writer.writeAttribute("name","ImplementsTemporalFilter");
                 writer.writeStartElement("http://www.opengis.net/ows/1.1","DefaultValue");
                 writer.writeCharacters("FALSE");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(namespace,"Constraint");
                 writer.writeAttribute("name","ImplementsVersionNav");
                 writer.writeStartElement("http://www.opengis.net/ows/1.1","DefaultValue");
                 writer.writeCharacters("TRUE");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(namespace,"Constraint");
                 writer.writeAttribute("name","ImplementsSorting");
                 writer.writeStartElement("http://www.opengis.net/ows/1.1","AllowedValues");
                 writer.writeStartElement("http://www.opengis.net/ows/1.1","Value");
                 writer.writeCharacters("ASC");
                 writer.writeEndElement();
                 writer.writeStartElement("http://www.opengis.net/ows/1.1","Value");
                 writer.writeCharacters("DESC");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement("http://www.opengis.net/ows/1.1","DefaultValue");
                 writer.writeCharacters("ASC");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(namespace,"Constraint");
                 writer.writeAttribute("name","ImplementsExtendedOperators");
                 writer.writeStartElement("http://www.opengis.net/ows/1.1","DefaultValue");
                 writer.writeCharacters("FALSE");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
         }
describeFeatureType() [1/2]
void describeFeatureType (XMLStreamWriter writer, JSONObject featuretype, String versionnamespace, String version) throws XMLStreamException
Creates a feature type description.
Parameters
writer the XMLWriter for writing the feature type description
featuretype the feature type to describe
versionnamespace the versionnamespace to use
version the version to write
Exceptions
XMLStreamException on error
References TripleStoreConnector.getBoundingBoxFromTripleStoreData(), and ResultFormatter.resultMap.
{
                 if ("1.0.0".equals(version) || "1.1.0".equals(version)) {
                         versionnamespace = "";
                 } else {
                         versionnamespace = "/" + versionnamespace;
                         versionnamespace = versionnamespace.replace("//", "/");
                 }
                 writer.writeStartElement("http://www.opengis.net/wfs" + versionnamespace, "FeatureType");
                 writer.writeStartElement("http://www.opengis.net/wfs" + versionnamespace, "Name");
                 writer.writeCharacters(featuretype.getString("name"));
                 writer.writeEndElement();
                 writer.writeStartElement("http://www.opengis.net/wfs" + versionnamespace, "Title");
                 writer.writeCharacters(featuretype.getString("name"));
                 writer.writeEndElement();
                 writer.writeStartElement("http://www.opengis.net/wfs" + versionnamespace, "DefaultCRS");
                 writer.writeCharacters("urn:ogc:def:crs:EPSG::4326");
                 writer.writeEndElement();
                 writer.writeStartElement("http://www.opengis.net/wfs" + versionnamespace, "OutputFormats");
                 for (ResultFormatter format : ResultFormatter.resultMap.values()) {
                         if (!format.exposedType.isEmpty()) {
                                 writer.writeStartElement("http://www.opengis.net/wfs" + versionnamespace, "Format");
                                 writer.writeCharacters(format.exposedType);
                                 writer.writeEndElement();
                         }
                 }
                 writer.writeEndElement();
                 if (!bboxCache.containsKey(featuretype.getString("name").toLowerCase())) {
                         bboxCache.put(featuretype.getString("name").toLowerCase(),
                                         TripleStoreConnector.getBoundingBoxFromTripleStoreData(featuretype.getString("triplestore"),
                                                         featuretype.getString("query")));
                 }
                 Double[] bbox = bboxCache.get(featuretype.getString("name").toLowerCase());
                 writer.writeStartElement("http://www.opengis.net/ows/1.1", "WGS84BoundingBox");
                 writer.writeAttribute("dimensions", "2");
                 writer.writeStartElement("http://www.opengis.net/ows/1.1", "lowerCorner");
                 writer.writeCharacters(bbox[0] + " " + bbox[1]);
                 writer.writeEndElement();
                 writer.writeStartElement("http://www.opengis.net/ows/1.1", "upperCorner");
                 writer.writeCharacters(bbox[2] + " " + bbox[3]);
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
         }
describeFeatureType() [2/2]
Response describeFeatureType (@Parameter(description="The feature type name to describe") @QueryParam("typename") String typename, @Parameter(description="The version of the WFS service") @DefaultValue("version") @QueryParam("version") String version) throws XMLStreamException
Describes a feature type as an answer to a WFS request.
Parameters
typename The feature type to describe
version The version of the WFS
Returns
The feature type description document
Exceptions
XMLStreamException on error
References TripleStoreConnector.getFeatureTypeInformation().
{
                 if (typename == null)
                         throw new NotFoundException();
                 JSONObject workingobj = null;
                 for (int i = 0; i < wfsconf.getJSONArray("datasets").length(); i++) {
                         JSONObject curobj = wfsconf.getJSONArray("datasets").getJSONObject(i);
                         if (curobj.getString("name").equalsIgnoreCase(typename)) {
                                 workingobj = curobj;
                                 break;
                         }
                 }
                 if (workingobj == null)
                         throw new NotFoundException();
                 XMLOutputFactory factory = XMLOutputFactory.newInstance();
                 StringWriter strwriter = new StringWriter();
                 XMLStreamWriter xmlwriter = factory.createXMLStreamWriter(strwriter);
                 IndentingXMLStreamWriter writer = new IndentingXMLStreamWriter(xmlwriter);
                 String versionnamespace = version.substring(0, version.lastIndexOf('.'));
                 if ("1.0.0".equals(version) || "1.1.0".equals(version)) {
                         versionnamespace = "";
                 } else {
                         versionnamespace = "/" + versionnamespace;
                         versionnamespace = versionnamespace.replace("//", "/");
                 }
                 writer.writeStartDocument();
                 writer.writeStartElement("schema");
                 // writer.writeAttribute("targetNamespace",(workingobj.has("namespace")?workingobj.getString("namespace"):wfsconf.getString("baseurl")));
                 writer.writeDefaultNamespace("http://www.w3.org/2001/XMLSchema");
                 writer.writeNamespace("app",
                                 (workingobj.has("namespace") ? workingobj.getString("namespace") : wfsconf.getString("baseurl")));
                 writer.setPrefix("app",
                                 (workingobj.has("namespace") ? workingobj.getString("namespace") : wfsconf.getString("baseurl")));
                 writer.writeNamespace("wfs", "http://www.opengis.net/wfs" + versionnamespace);
                 writer.writeNamespace("ows", "http://www.opengis.net/ows/1.1");
                 writer.writeNamespace("sf", "http://www.opengis.net/ogcapi-features-1/1.0/sf");
                 writer.writeNamespace("ogc", "http://www.opengis.net/ogc");
                 writer.writeNamespace("fes", "http://www.opengis.net/fes" + versionnamespace);
                 writer.writeNamespace("gml", "http://www.opengis.net/gml");
                 writer.writeNamespace("xlink", "http://www.w3.org/1999/xlink");
                 writer.writeStartElement("element");
                 writer.writeAttribute("name", typename);
                 writer.writeAttribute("type", typename + "Type");
                 writer.writeAttribute("substitutionGroup", "gml:_Feature");
                 writer.writeEndElement();
                 writer.writeStartElement("complexType");
                 writer.writeAttribute("name", typename + "Type");
                 writer.writeStartElement("complexContent");
                 writer.writeStartElement("extension");
                 writer.writeAttribute("base", "gml:AbstractFeatureType");
                 writer.writeStartElement("all");
                 if (!featureTypeCache.containsKey(typename.toLowerCase())) {
                         featureTypeCache.put(typename.toLowerCase(),
                                         TripleStoreConnector.getFeatureTypeInformation(workingobj.getString("query"),
                                                         workingobj.getString("triplestore"), workingobj.getString("name"), workingobj));
                 }
                 writer.writeStartElement("element");
                 writer.writeAttribute("name", "the_geom");
                 writer.writeAttribute("minOccurs", "0");
                 writer.writeAttribute("type",
                                 "gml:" + (workingobj.has("geometrytype") ? workingobj.getString("geometrytype") : "Geometry")
                                                 + "PropertyType");
                 writer.writeEndElement();
                 Map<String, String> mapping = featureTypeCache.get(typename.toLowerCase());
                 for (String elem : mapping.keySet()) {
                         if (elem.equals("namespaces"))
                                 continue;
                         writer.writeStartElement("element");
                         if (elem.startsWith("http") && elem.contains("#")) {
                                 writer.writeAttribute("name", elem.substring(elem.lastIndexOf('#') + 1));
                         } else if (elem.startsWith("http") && elem.contains("/")) {
                                 writer.writeAttribute("name", elem.substring(elem.lastIndexOf('/') + 1));
                         } else {
                                 writer.writeAttribute("name", elem);
                         }
                         if (mapping.get(elem).contains("^^")) {
                                 writer.writeAttribute("type", mapping.get(elem).substring(mapping.get(elem).lastIndexOf("^^") + 2));
                         } else if (mapping.get(elem).startsWith("http") || mapping.get(elem).startsWith("file:/")) {
                                 writer.writeAttribute("type", "string");
                         } else {
                                 writer.writeAttribute("type", "string");
                         }
                         writer.writeAttribute("minOccurs", "0");
                         writer.writeEndElement();
                 }
                 // writer.writeEndElement();
                 // this.describeFeatureType(writer,
                 // workingobj,version.substring(0,version.lastIndexOf('.')),version);
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndDocument();
                 return Response.ok(strwriter.toString()).type(MediaType.APPLICATION_XML).build();
         }
describeFeatureTypeJSON()
Response describeFeatureTypeJSON (@Parameter(description="The feature type to describe") @QueryParam("typename") String typename, @Parameter(description="The version of the WFS service") @DefaultValue("version") @QueryParam("version") String version)
Describes a feature type in JSON.
Parameters
typename The type name to describe
version The version of the WFS
Returns
The JSON document to return
References TripleStoreConnector.getFeatureTypeInformation().
{
                 if (typename == null)
                         throw new NotFoundException();
                 JSONObject workingobj = null;
                 for (int i = 0; i < wfsconf.getJSONArray("datasets").length(); i++) {
                         JSONObject curobj = wfsconf.getJSONArray("datasets").getJSONObject(i);
                         if (curobj.getString("name").equalsIgnoreCase(typename)) {
                                 workingobj = curobj;
                                 break;
                         }
                 }
                 if (workingobj == null)
                         throw new NotFoundException();
                 JSONObject schema = new JSONObject();
                 JSONArray required = new JSONArray();
                 schema.put("definitions", new JSONObject());
                 schema.put("$schema", "http://json-schema.org/draft-07/schema#");
                 schema.put("$id", wfsconf.getString("baseurl") + "/collections/" + typename + "/schema?f=json");
                 schema.put("type", "object");
                 schema.put("title", typename);
                 schema.put("description", (workingobj.has("description") ? workingobj.getString("description") : ""));
                 schema.put("readOnly", true);
                 schema.put("writeOnly", false);
                 schema.put("required", required);
                 JSONObject properties = new JSONObject();
                 schema.put("properties", properties);
                 if (!featureTypeCache.containsKey(typename.toLowerCase())) {
                         featureTypeCache.put(typename.toLowerCase(),
                                         TripleStoreConnector.getFeatureTypeInformation(workingobj.getString("query"),
                                                         workingobj.getString("triplestore"), workingobj.getString("name"), workingobj));
                 }
                 Map<String, String> mapping = featureTypeCache.get(typename.toLowerCase());
                 for (String elem : mapping.keySet()) {
                         if (elem.equals("namespaces"))
                                 continue;
                         if (elem.startsWith("http") && elem.contains("#")) {
                                 required.put(elem.substring(elem.lastIndexOf('#') + 1));
                         } else if (elem.startsWith("http") && elem.contains("/")) {
                                 required.put(elem.substring(elem.lastIndexOf('/') + 1));
                         } else {
                                 required.put(elem);
                         }
                 }
                 for (String elem : mapping.keySet()) {
                         if (elem.equals("namespaces"))
                                 continue;
                         JSONObject prop = new JSONObject();
                         String curprop = "";
                         if (elem.startsWith("http") && elem.contains("#")) {
                                 curprop = elem.substring(elem.lastIndexOf('#') + 1);
                                 properties.put(curprop, prop);
                         } else if (elem.startsWith("http") && elem.contains("/")) {
                                 curprop = elem.substring(elem.lastIndexOf('/') + 1);
                                 properties.put(elem.substring(elem.lastIndexOf('/') + 1), prop);
                         } else {
                                 curprop = elem;
                                 properties.put(elem, prop);
                         }
                         prop.put("$id", wfsconf.getString("baseurl") + "/collections/" + typename + "/" + curprop);
                         if (mapping.get(elem).contains("^^")) {
                                 prop.put("type", mapping.get(elem).substring(mapping.get(elem).lastIndexOf("^^") + 2));
                         } else if (mapping.get(elem).startsWith("http") || mapping.get(elem).startsWith("file:/")) {
                                 prop.put("type", "string");
                         } else {
                                 prop.put("type", "string");
                         }
                         prop.put("title", curprop);
                         prop.put("description", curprop + " Property");
                         JSONArray examples = new JSONArray();
                         prop.put("examples", examples);
                 }
                 return Response.ok(schema.toString(2)).type(MediaType.APPLICATION_JSON).build();
         }
describeFeatureTypeWFS10()
void describeFeatureTypeWFS10 (XMLStreamWriter writer, JSONObject featuretype, String versionnamespace, String version) throws XMLStreamException
Describes a feature type according to the WFS1.0 specification.
Parameters
writer XMLWriter to write the specification
featuretype the feature type to consider
versionnamespace the versionnamespace to write
version the version to use
Exceptions
XMLStreamException on error
References TripleStoreConnector.getBoundingBoxFromTripleStoreData(), and ResultFormatter.resultMap.
{
                 writer.setPrefix("wfs", "http://www.opengis.net/wfs");
                 writer.writeStartElement("http://www.opengis.net/wfs", "FeatureType");
                 writer.writeStartElement("http://www.opengis.net/wfs", "Name");
                 writer.writeCharacters(featuretype.getString("name"));
                 writer.writeEndElement();
                 writer.writeStartElement("http://www.opengis.net/wfs", "Title");
                 writer.writeCharacters(featuretype.getString("name"));
                 writer.writeEndElement();
                 writer.writeStartElement("http://www.opengis.net/wfs", "SRS");
                 writer.writeCharacters("urn:ogc:def:crs:EPSG::4326");
                 writer.writeEndElement();
                 writer.writeStartElement("http://www.opengis.net/wfs", "OutputFormats");
                 for (ResultFormatter format : ResultFormatter.resultMap.values()) {
                         if (!format.exposedType.isEmpty()) {
                                 writer.writeStartElement("http://www.opengis.net/wfs", "Format");
                                 writer.writeCharacters(format.exposedType);
                                 writer.writeEndElement();
                         }
                 }
                 writer.writeEndElement();
                 if (!bboxCache.containsKey(featuretype.getString("name").toLowerCase())) {
                         bboxCache.put(featuretype.getString("name").toLowerCase(),
                                         TripleStoreConnector.getBoundingBoxFromTripleStoreData(featuretype.getString("triplestore"),
                                                         featuretype.getString("query")));
                 }
                 Double[] bbox = bboxCache.get(featuretype.getString("name").toLowerCase());
                 writer.writeStartElement("http://www.opengis.net/ows/1.1", "LatLongBoundingBox");
                 writer.writeAttribute("minx", bbox[0] + "");
                 writer.writeAttribute("miny", bbox[1] + "");
                 writer.writeAttribute("maxx", bbox[2] + "");
                 writer.writeAttribute("maxy", bbox[3] + "");
                 writer.writeEndElement();
                 writer.writeEndElement();
         }
describeScalarCapabilities()
void describeScalarCapabilities (XMLStreamWriter writer, String versionnamespace, String namespace) throws XMLStreamException
Writes the scalar capabilities document for a WFS.
Parameters
writer The XMLStreamWriter to write the capabilities document with
versionnamespace The versionnamespace to use
namespace The namespace to use for writing
Exceptions
XMLStreamException on error
{
                 writer.writeStartElement(namespace, "Scalar_Capabilities");
                 writer.writeStartElement(namespace, "LogicalOperators");
                 writer.writeEndElement();
                 writer.writeStartElement(namespace, "ComparisonOperators");
                 writer.writeStartElement(namespace, "ComparisonOperator");
                 writer.writeCharacters("LessThan");
                 writer.writeEndElement();
                 writer.writeStartElement(namespace, "ComparisonOperator");
                 writer.writeCharacters("GreaterThan");
                 writer.writeEndElement();
                 writer.writeStartElement(namespace, "ComparisonOperator");
                 writer.writeCharacters("LessThanEqualTo");
                 writer.writeEndElement();
                 writer.writeStartElement(namespace, "ComparisonOperator");
                 writer.writeCharacters("GreaterThanEqualTo");
                 writer.writeEndElement();
                 writer.writeStartElement(namespace, "ComparisonOperator");
                 writer.writeCharacters("EqualTo");
                 writer.writeEndElement();
                 writer.writeStartElement(namespace, "ComparisonOperator");
                 writer.writeCharacters("NotEqualTo");
                 writer.writeEndElement();
                 writer.writeStartElement(namespace, "ComparisonOperator");
                 writer.writeCharacters("Like");
                 writer.writeEndElement();
                 writer.writeStartElement(namespace, "ComparisonOperator");
                 writer.writeCharacters("Between");
                 writer.writeEndElement();
                 writer.writeStartElement(namespace, "ArithmeticOperators");
                 writer.writeEndElement();
                 writer.writeEndElement();
         }
describeSpatialCapabilities()
void describeSpatialCapabilities (XMLStreamWriter writer, String versionnamespace, String namespace) throws XMLStreamException
Writes the spatial capabilities part of the WFS document.
Parameters
writer The XMLWriter to write the document part
versionnamespace The versionnamespace to write
namespace The namespace to use
Exceptions
XMLStreamException on error
{
                 writer.writeStartElement(namespace, "Spatial_Capabilities");
                 writer.writeStartElement(namespace, "GeometryOperands");
                 writer.writeStartElement(namespace, "GeometryOperand");
                 writer.writeAttribute("name", "gml:Box");
                 writer.writeEndElement();
                 writer.writeStartElement(namespace, "GeometryOperand");
                 writer.writeAttribute("name", "gml:Envelope");
                 writer.writeEndElement();
                 writer.writeStartElement(namespace, "GeometryOperand");
                 writer.writeAttribute("name", "gml:Point");
                 writer.writeEndElement();
                 writer.writeStartElement(namespace, "GeometryOperand");
                 writer.writeAttribute("name", "gml:LineString");
                 writer.writeEndElement();
                 writer.writeStartElement(namespace, "GeometryOperand");
                 writer.writeAttribute("name", "gml:Curve");
                 writer.writeEndElement();
                 writer.writeStartElement(namespace, "GeometryOperand");
                 writer.writeAttribute("name", "gml:Polygon");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeStartElement(namespace, "SpatialOperators");
                 writer.writeStartElement(namespace, "SpatialOperator");
                 writer.writeAttribute("name", "BBOX");
                 writer.writeEndElement();
                 writer.writeStartElement(namespace, "SpatialOperator");
                 writer.writeAttribute("name", "Intersects");
                 writer.writeEndElement();
                 writer.writeStartElement(namespace, "SpatialOperator");
                 writer.writeAttribute("name", "Contains");
                 writer.writeEndElement();
                 writer.writeStartElement(namespace, "SpatialOperator");
                 writer.writeAttribute("name", "Crosses");
                 writer.writeEndElement();
                 writer.writeStartElement(namespace, "SpatialOperator");
                 writer.writeAttribute("name", "Touches");
                 writer.writeEndElement();
                 writer.writeStartElement(namespace, "SpatialOperator");
                 writer.writeAttribute("name", "Within");
                 writer.writeEndElement();
                 writer.writeStartElement(namespace, "SpatialOperator");
                 writer.writeAttribute("name", "Overlaps");
                 writer.writeEndElement();
                 writer.writeStartElement(namespace, "SpatialOperator");
                 writer.writeAttribute("name", "Disjoint");
                 writer.writeEndElement();
                 writer.writeStartElement(namespace, "SpatialOperator");
                 writer.writeAttribute("name", "Equals");
                 writer.writeEndElement();
                 writer.writeStartElement(namespace, "SpatialOperator");
                 writer.writeAttribute("name", "DWithin");
                 writer.writeEndElement();
                 writer.writeEndElement();
                 writer.writeEndElement();
         }
describeSpatialCapabilitiesWFS10()
void describeSpatialCapabilitiesWFS10 (XMLStreamWriter writer, String versionnamespace, String namespace) throws XMLStreamException
Creates the spatial capabilities document for a WFS in version 1.0.
Parameters
writer The XMLWriter to write the documentation with
versionnamespace The versionnamespace to use for writing
namespace The namespace to use
Exceptions
XMLStreamException on error
{
                 writer.writeStartElement(namespace, "Spatial_Capabilities");
                 writer.writeStartElement(namespace, "Spatial_Operators");
                 writer.writeStartElement(namespace, "BBOX");
                 writer.writeEndElement();
                 writer.writeStartElement(namespace, "Intersects");
                 writer.writeEndElement();
                 writer.writeStartElement(namespace, "Contains");
                 writer.writeEndElement();
                 writer.writeStartElement(namespace, "Crosses");
                 writer.writeEndElement();
                 writer.writeStartElement(namespace, "Touches");
                 writer.writeEndElement();
                 writer.writeStartElement(namespace, "Within");
                 writer.writeEndElement();
                 writer.writeStartElement(namespace, "Overlaps");
                 writer.writeEndElement();
                 writer.writeStartElement(namespace, "Disjoint");
                 writer.writeEndElement();
                 writer.writeStartElement(namespace, "Equals");
                 writer.writeEndElement();
                 writer.writeStartElement(namespace, "DWithin");
                 writer.writeEndElement();
                 writer.writeEndElement();
         }
docCollectionItemJSON()
Response docCollectionItemJSON (@Parameter(description="The id of the collection to be considered") @PathParam("collectionid") String collectionid, @Parameter(description="The id of the feature to be considered") @PathParam("ext") String ext, @Parameter(description="The id of the feature to be considered") @PathParam("featureid") String featureid, @Parameter(description="The format in which the collection should be returned", example="geojson") @DefaultValue("ldapi") @QueryParam("_format") String format, @Parameter(description="The maximum amount of features to be returned", example="10") @DefaultValue("10") @QueryParam("_pageSize") Integer limit, @Parameter(description="An optional where statement to be used in the SPARQL query", example="10") @DefaultValue("") @QueryParam("_select") String select, @Parameter(description="An optional where statement to be used in the SPARQL query", example="10") @DefaultValue("") @QueryParam("_where") String where, @Parameter(description="The page of the Linked Data API resource to return", example="1") @DefaultValue("1") @QueryParam("_page") Integer page, @Parameter(description="Detailed or minimized view to be returned") @DefaultValue("") @QueryParam("_view") String view, @Parameter(description="The sorting of the given results") @DefaultValue("") @QueryParam("_sort") String sort, @Parameter(description="An optional orderBy statement to be used in the SPARQL query") @DefaultValue("") @QueryParam("_orderBy") String orderBy, @Parameter(description="A subclass definition of the class defining the featurecollection") @DefaultValue("") @QueryParam("type") String type, @Parameter(description="Defines resources with a specified parameter value to be returned") @DefaultValue("") @QueryParam("param") List< String > paramval, @Parameter(description="Defines resources with a specified parameter value greater or equal the given value to be returned") @DefaultValue("") @QueryParam("max-param") String maxparamval, @Parameter(description="Defines resources with a specified parameter value smaller or equal the given value to be returned") @DefaultValue("") @QueryParam("min-param") String minparamval, @Parameter(description="Defines resources with a specified parameter value greater than the given value to be returned") @DefaultValue("") @QueryParam("maxEx-param") String maxExparamval, @Parameter(description="Defines resources with a specified parameter value smaller than the given value to be returned") @DefaultValue("") @QueryParam("minEx-param") String minExparamval, @Parameter(description="Returns only resources with the specified parameter") @QueryParam("exists-param") String existsparam, @Parameter(description="An offset to be considered when returning features", example="10") @DefaultValue("0") @QueryParam("offset") String offset)
References TripleStoreConnector.executeLDAPIQuery(), ResultFormatter.fileextension, ResultFormatter.getFormatter(), and ResultFormatter.mimeType.
{
                 String queryString="",additionalwhereclauses="";
                 JSONObject workingobj=null;
                 for (int i = 0; i < wfsconf.getJSONArray("datasets").length(); i++) {
                         JSONObject curobj = wfsconf.getJSONArray("datasets").getJSONObject(i);
                         if (curobj.getString("name").equalsIgnoreCase(collectionid)) {
                                 workingobj = curobj;
                                 break;
                         }
                 }
                 if (workingobj == null) {
                         throw new NotFoundException();
                 }
                 if(!select.isEmpty()) {
                         queryString=select;
                 }else {
                         queryString=workingobj.getString("query");
                 }
                 if(queryString.contains("WHERE {")) {
                         queryString=queryString.replace("WHERE {", "WHERE {\n BIND( <"+workingobj.getString("namespace")+featureid+"> AS ?item)\n");
                 }else if(queryString.contains("WHERE{")) {
                         queryString=queryString.replace("WHERE{", "WHERE{\n BIND( <"+workingobj.getString("namespace")+featureid+"> AS ?item)\n");
                 }
                 if(!where.isEmpty() && select.isEmpty()) {
                         queryString=queryString.substring(0,queryString.indexOf("WHERE"));
                         queryString+="WHERE {\n"+where+"\n}";
                 }
                 Integer addvarcounter=0;
                 /*if(existsparam!=null) {
                         for(String str:existsparam) {
                                 additionalwhereclauses+=triplestoreconf.getJSONObject(collectionid.toLowerCase()).getString("indvar")+" "+str+" ?var"+addvarcounter+++System.lineSeparator();
                         }
                 }
                 if(type!=null) {
                         for(String str:type) {
                                 additionalwhereclauses+=triplestoreconf.getJSONObject(collectionid.toLowerCase()).getString("indvar")+" rdf:type "+str+System.lineSeparator();
                         }
                 }*/
                 if(!orderBy.isEmpty()) {
                         queryString+=System.lineSeparator()+orderBy;
                 }
                 queryString+=System.lineSeparator()+"LIMIT "+limit;
                 if(page>1) {
                         queryString+=System.lineSeparator()+"OFFSET "+page*limit;
                 }
                 if(collectionid.contains(".")) {
                         if(format.isEmpty()) {
                                 format=collectionid.substring(collectionid.lastIndexOf('.')+1);
                         }
                         collectionid=collectionid.substring(0,collectionid.lastIndexOf('.'));
                 }
                 final String qs=queryString;
                 final String formatt=format;
                 final JSONObject workingobjj=workingobj;
                 StreamingOutput stream = new StreamingOutput() {
                     @Override
                     public void write(OutputStream os) throws IOException,
                     WebApplicationException {
                       Writer writer = new BufferedWriter(new OutputStreamWriter(os));
                       String res;
                         try {
                                 res = TripleStoreConnector.executeLDAPIQuery(qs, formatt,null, workingobjj.getString("triplestore"), workingobjj,writer);
                               if(res!=null && !res.isEmpty()) {
                                   writer.write(res);
                               }
                         } catch (JSONException | IOException e) {
                                 // TODO Auto-generated catch block
                                 e.printStackTrace();
                         }
                         writer.close();
                     }
                   };
                 return Response.ok(stream,ResultFormatter.getFormatter(format).mimeType)
                                 .header("Content-Disposition", "attachment; filename*=UTF-8''" + collectionid+"_items."
                                                 +ResultFormatter.getFormatter(format).fileextension)
                                 .build();
         }
docCollectionJSON()
Response docCollectionJSON (@Parameter(description="The id of the collection to be considered") @PathParam("collectionid") String collectionid, @Parameter(description="The format if given as a file extension") @DefaultValue("") @PathParam("ext") String ext, @Parameter(description="The format in which the collection should be returned", example="ttl") @DefaultValue("ldapi") @QueryParam("_format") String format, @Parameter(description="The maximum amount of features to be returned", example="10") @DefaultValue("10") @QueryParam("_pageSize") Integer limit, @Parameter(description="An optional where statement to be used in the SPARQL query", example="10") @DefaultValue("") @QueryParam("_select") String select, @Parameter(description="An optional where statement to be used in the SPARQL query", example="10") @DefaultValue("") @QueryParam("_where") String where, @Parameter(description="The page of the Linked Data API resource to return", example="1") @DefaultValue("1") @QueryParam("_page") Integer page, @Parameter(description="Detailed or minimized view to be returned") @DefaultValue("") @QueryParam("_view") String view, @Parameter(description="The sorting of the given results") @DefaultValue("") @QueryParam("_sort") String sort, @Parameter(description="An optional orderBy statement to be used in the SPARQL query") @DefaultValue("") @QueryParam("_orderBy") String orderBy, @Parameter(description="A subclass definition of the class defining the featurecollection") @DefaultValue("") @QueryParam("type") String type, @Parameter(description="Defines resources with a specified parameter value to be returned") @DefaultValue("") @QueryParam("param") List< String > paramval, @Parameter(description="Defines resources with a specified parameter value greater or equal the given value to be returned") @DefaultValue("") @QueryParam("max-param") String maxparamval, @Parameter(description="Defines resources with a specified parameter value smaller or equal the given value to be returned") @DefaultValue("") @QueryParam("min-param") String minparamval, @Parameter(description="Defines resources with a specified parameter value greater than the given value to be returned") @DefaultValue("") @QueryParam("maxEx-param") String maxExparamval, @Parameter(description="Defines resources with a specified parameter value smaller than the given value to be returned") @DefaultValue("") @QueryParam("minEx-param") String minExparamval, @Parameter(description="Returns only resources with the specified parameter") @QueryParam("exists-param") String existsparam, @Parameter(description="An offset to be considered when returning features", example="10") @DefaultValue("0") @QueryParam("offset") Integer offset)
References TripleStoreConnector.executeLDAPIQuery(), ResultFormatter.fileextension, ResultFormatter.getFormatter(), ResultFormatter.mimeType, and WebService.triplestoreconf.
{
                 String queryString="",additionalwhereclauses="";
                 JSONObject workingobj=null;
                 for (int i = 0; i < wfsconf.getJSONArray("datasets").length(); i++) {
                         JSONObject curobj = wfsconf.getJSONArray("datasets").getJSONObject(i);
                         if (curobj.getString("name").equalsIgnoreCase(collectionid)) {
                                 workingobj = curobj;
                                 break;
                         }
                 }
                 if (workingobj == null) {
                         throw new NotFoundException();
                 }
                 if(!select.isEmpty()) {
                         queryString=select;
                 }else {
                         queryString=workingobj.getString("query");
                 }
                 if(limit>=1 || offset>0) {
                         StringBuilder toreplace=new StringBuilder();
                         toreplace.append("WHERE{ { SELECT ?"+workingobj.getString("indvar")+" WHERE { ?"+workingobj.getString("indvar")+" <"+WebService.triplestoreconf.getJSONObject("endpoints").getJSONObject(workingobj.getString("triplestore")).getString("type")+"> <"+workingobj.getString("class")+"> . }"+System.lineSeparator());
                         if(limit>=1) {
                                 toreplace.append(" LIMIT "+limit+System.lineSeparator());
                         }
                         if(offset>0) {
                                 toreplace.append(" OFFSET "+offset+System.lineSeparator());
                         }
                         toreplace.append(" } "+System.lineSeparator());
                         queryString=queryString.replace("WHERE{", toreplace);
                 }
                 if(!where.isEmpty() && select.isEmpty()) {
                         queryString=queryString.substring(0,queryString.indexOf("WHERE"));
                         queryString+="WHERE {\n"+where+"\n}";
                 }
                 Integer addvarcounter=0;
                 /*if(existsparam!=null) {
                         for(String str:existsparam) {
                                 additionalwhereclauses+=triplestoreconf.getJSONObject(collectionid.toLowerCase()).getString("indvar")+" "+str+" ?var"+addvarcounter+++System.lineSeparator();
                         }
                 }
                 if(type!=null) {
                         for(String str:type) {
                                 additionalwhereclauses+=triplestoreconf.getJSONObject(collectionid.toLowerCase()).getString("indvar")+" rdf:type "+str+System.lineSeparator();
                         }
                 }*/
                 if(!orderBy.isEmpty()) {
                         queryString+=System.lineSeparator()+orderBy;
                 }
                 /*queryString+=System.lineSeparator()+"LIMIT "+limit;
                 if(page>1) {
                         queryString+=System.lineSeparator()+"OFFSET "+page*limit;
                 }*/
                 if(!ext.isEmpty()) {
                         if(format.isEmpty()) {
                                 format=ext;
                         }
                         collectionid=collectionid.substring(0,collectionid.lastIndexOf('.'));
                 }
                 final String qs=queryString;
                 final String formatt=format;
                 final JSONObject workingobjj=workingobj;
                 StreamingOutput stream = new StreamingOutput() {
                     @Override
                     public void write(OutputStream os) throws IOException,
                     WebApplicationException {
                       Writer writer = new BufferedWriter(new OutputStreamWriter(os));
                       String res;
                         try {
                                 res = TripleStoreConnector.executeLDAPIQuery(qs, formatt,null, workingobjj.getString("triplestore"), workingobjj,writer);
                               if(res!=null && !res.isEmpty()) {
                                   writer.write(res);
                               }
                         } catch (JSONException | IOException e) {
                                 // TODO Auto-generated catch block
                                 e.printStackTrace();
                         }
                         writer.close();
                     }
                   };
                 return Response.ok(stream,ResultFormatter.getFormatter(format).mimeType)
                                 .header("Content-Disposition", "attachment; filename*=UTF-8''" + collectionid+"_items."
                                                 +ResultFormatter.getFormatter(format).fileextension)
                                 .build();
         }
docJSON()
Response docJSON (@Parameter(description="Return format") @DefaultValue("json") @QueryParam("f") String format)
{
                 return collections(format);
         }
entryPoint()
Response entryPoint (@Parameter(description="Service type") @DefaultValue("WFS") @QueryParam("SERVICE") String service, @Parameter(description="Request type") @DefaultValue("GetCapabilities") @QueryParam("REQUEST") String request, @Parameter(description="Service version") @DefaultValue("2.0.0") @QueryParam("VERSION") String version, @Parameter(description="Feature type names") @DefaultValue("") @QueryParam("TYPENAME") String typename, @Parameter(description="Feature type names") @DefaultValue("") @QueryParam("TYPENAMES") String typenames, @Parameter(description="CRS type") @DefaultValue("") @QueryParam("SRSNAME") String srsName, @DefaultValue("gml") @QueryParam("EXCEPTIONS") String exceptions, @Parameter(description="Bounding box for filtering the results") @DefaultValue("") @QueryParam("BBOX") String bbox, @DefaultValue("") @QueryParam("VALUEREFERENCE") String propertyname, @Parameter(description="Sorting order") @DefaultValue("ASC") @QueryParam("SORTBY") String sortBy, @DefaultValue("") @QueryParam("STYLES") String style, @DefaultValue("results") @QueryParam("RESULTTYPE") String resultType, @DefaultValue("") @QueryParam("RESOURCEID") String resourceids, @DefaultValue("") @QueryParam("GMLOBJECTID") String gmlobjectid, @DefaultValue("0") @QueryParam("STARTINDEX") String startindex, @Parameter(description="Filter expression") @DefaultValue("") @QueryParam("FILTER") String filter, @Parameter(description="Filter query language") @DefaultValue("") @QueryParam("FILTERLANGUAGE") String filterLanguage, @Parameter(description="Return format") @DefaultValue("gml") @QueryParam("OUTPUTFORMAT") String output, @Parameter(description="Maximum amount of results to return") @DefaultValue("5") @QueryParam("COUNT") String count)
WFS endpoint implementation.
Parameters
service The service identifier
request The request identifier
version The service version
typename The feature type name to request
typenames The feature type name to request
srsName
exceptions
bbox
propertyname
sortBy
style
resultType
resourceids
gmlobjectid
startindex
filter
filterLanguage
output
count
Returns
{
                 System.out.println("Request: " + request);
                 System.out.println("ResultType: " + resultType);
                 if (typename.isEmpty() && !typenames.isEmpty()) {
                         typename = typenames;
                 }
                 if (service.equalsIgnoreCase("WFS")) {
                         if ("getCapabilities".equalsIgnoreCase(request)) {
                                 try {
                                         return this.constructCapabilities(version, version.substring(0, version.lastIndexOf('.')));
                                 } catch (XMLStreamException e) {
                                         e.printStackTrace();
                                         return Response.ok("").type(MediaType.TEXT_PLAIN).build();
                                 }
                         }
                         if ("describeFeatureType".equalsIgnoreCase(request)) {
                                 try {
                                         return this.describeFeatureType(typename, version);
                                 } catch (XMLStreamException e) {
                                         e.printStackTrace();
                                         return Response.ok("").type(MediaType.TEXT_PLAIN).build();
                                 }
                         }
                         if ("getFeature".equalsIgnoreCase(request)) {
                                 try {
                                         return this.getFeature(typename, output, count, startindex, srsName, sortBy, style, version,
                                                         resourceids, filter, filterLanguage, resultType);
                                 } catch (XMLStreamException e) {
                                         e.printStackTrace();
                                         return Response.ok("").type(MediaType.TEXT_PLAIN).build();
                                 }
                         }
                         if ("getPropertyValue".equalsIgnoreCase(request)) {
                                 return this.getPropertyValue(typename, propertyname, output, resourceids, filter, count, resultType);
                         }
                         if ("getGmlObject".equalsIgnoreCase(request)) {
                                 return this.getGmlObject(typename, gmlobjectid, "4", output);
                         }
                 }
                 return Response.ok("").type(MediaType.TEXT_PLAIN).build();
         }
entryPointCSW()
Response entryPointCSW (@Parameter(description="Service type") @DefaultValue("CSW") @QueryParam("SERVICE") String service, @Parameter(description="Request type") @DefaultValue("GetCapabilities") @QueryParam("REQUEST") String request, @Parameter(description="Version of the webservice") @DefaultValue("2.0.2") @QueryParam("VERSION") String version, @Parameter(description="Feature type names") @DefaultValue("") @QueryParam("TYPENAME") String typename, @Parameter(description="Feature type names") @DefaultValue("") @QueryParam("TYPENAMES") String typenames, @Parameter(description="Return type") @DefaultValue("gml") @QueryParam("OUTPUTFORMAT") String output)
CSW endpoint implementation.
Parameters
service The service identifier
request The request identifier
version The service version
typename The feature type name to request
typenames The feature type name to request
output The requested return format
Returns
The CSW service description as XML
{
                 if (service.equalsIgnoreCase("CSW")) {
                         if ("getCapabilities".equalsIgnoreCase(request)) {
                                 try {
                                         return this.constructCapabilitiesCSW(version, version.substring(0, version.lastIndexOf('.')));
                                 } catch (XMLStreamException e) {
                                         // TODO Auto-generated catch block
                                         e.printStackTrace();
                                         return Response.ok("").type(MediaType.TEXT_PLAIN).build();
                                 }
                         }
                         if ("describeRecord".equalsIgnoreCase(request)) {
                                 return Response.ok("").type(MediaType.TEXT_PLAIN).build();
                         }
                         if ("harvest".equalsIgnoreCase(request)) {
                                 return Response.ok("").type(MediaType.TEXT_PLAIN).build();
                         }
                         if ("getRecords".equalsIgnoreCase(request)) {
                                 return this.getCollectionMetadata(typename, output, "false","");
                         }
                         if ("getRecordById".equalsIgnoreCase(request)) {
                                 return this.getCollectionsMetadata(output);
                         }
                 }
                 return Response.ok("").type(MediaType.TEXT_PLAIN).build();
         }
entryPointCSWPost()
Response entryPointCSWPost (@DefaultValue("CSW") @QueryParam("SERVICE") String service, @DefaultValue("GetCapabilities") @QueryParam("REQUEST") String request, @DefaultValue("2.0.2") @QueryParam("VERSION") String version, @DefaultValue("") @QueryParam("TYPENAME") String typename, @DefaultValue("") @QueryParam("TYPENAMES") String typenames, @DefaultValue("gml") @QueryParam("OUTPUTFORMAT") String output)
CSW endpoint implementation (POST version).
Parameters
service The service identifier
request The request identifier
version The service version
typename The feature type name to request
typenames The feature type name to request
output The requested return format
Returns
The CSW service description as XML
{
                 return this.entryPointCSW(service, request, version, typename, typenames, output);
         }
entryPointPOST()
Response entryPointPOST (@Parameter(description="Service type definition") @DefaultValue("WFS") @QueryParam("SERVICE") String service, @Parameter(description="Request definition") @DefaultValue("GetCapabilities") @QueryParam("REQUEST") String request, @Parameter(description="Version of the web service") @DefaultValue("2.0.0") @QueryParam("VERSION") String version, @Parameter(description="The feature type name to be queried") @DefaultValue("") @QueryParam("TYPENAME") String typename, @Parameter(description="The feature type(s) name(s) to be queried") @DefaultValue("") @QueryParam("TYPENAMES") String typenames, @Parameter(description="The name of the CRS to be returned") @DefaultValue("") @QueryParam("SRSNAME") String srsName, @DefaultValue("gml") @QueryParam("EXCEPTIONS") String exceptions, @Parameter(description="A bounding box used for filtering results") @DefaultValue("") @QueryParam("BBOX") String bbox, @DefaultValue("") @QueryParam("VALUEREFERENCE") String propertyname, @Parameter(description="Sorting order definition") @DefaultValue("ASC") @QueryParam("SORTBY") String sortBy, @DefaultValue("") @QueryParam("STYLES") String style, @DefaultValue("results") @QueryParam("RESULTTYPE") String resultType, @DefaultValue("") @QueryParam("RESOURCEID") String resourceids, @DefaultValue("") @QueryParam("GMLOBJECTID") String gmlobjectid, @DefaultValue("0") @QueryParam("STARTINDEX") String startindex, @DefaultValue("") @QueryParam("FILTER") String filter, @DefaultValue("") @QueryParam("FILTERLANGUAGE") String filterLanguage, @DefaultValue("gml") @QueryParam("OUTPUTFORMAT") String output, @DefaultValue("5") @QueryParam("COUNT") String count)
Entrypoint implementation for OGC API Features for POST requests.
Parameters
service
request
version
typename
typenames
srsName
exceptions
bbox
propertyname
sortBy
style
resultType
resourceids
gmlobjectid
startindex
filter
filterLanguage
output
count
Returns
{
                 return entryPoint(service, request, version, typename, typenames, srsName, exceptions, bbox, propertyname,
                                 sortBy, style, resultType, resourceids, gmlobjectid, startindex, filter, filterLanguage, output, count);
         }
generateOpenAPIDefinitions()
void generateOpenAPIDefinitions ()
Generates OpenAPI definitions of the SemanticWFS services for the use with OGC API Features.
{
                 JSONObject defs=new JSONObject();
                 for (Integer i = 0; i < wfsconf.getJSONArray("datasets").length(); i++) {
                         JSONObject featuretype = wfsconf.getJSONArray("datasets").getJSONObject(i);
                         JSONObject curobj=new JSONObject();
                         defs.put("/collections/"+featuretype.getString("name"), curobj);
                         JSONObject get=new JSONObject();
                         curobj.put("get", get);
                         get.put("summary", featuretype.getString("description"));
                         get.put("description", featuretype.getString("description"));
                         get.put("operationId", featuretype.getString("name"));
                         JSONObject parameters=new JSONObject();
                         get.put("parameters", parameters);
                 }
         }
getCapabilities()
Response getCapabilities (@Parameter(description="The version of the WFS service to target") @DefaultValue("2.0.0") @QueryParam("version") String version) throws XMLStreamException
Returns the capabilities document for a WFS service.
Parameters
version The version of the WFS service to target
Returns
The capabilities document as String
Exceptions
XMLStreamException on error
{
                 if (!version.equals("2.0.0") && !version.equals("1.1.0"))
                         version = "2.0.0";
                 return constructCapabilities(version, version.substring(0, version.lastIndexOf('.')));
         }
getCollectionMetadata()
Response getCollectionMetadata (@PathParam("collectionid") String collectionid, @Parameter(description="The metadata schema to be used") @DefaultValue("gmd") @QueryParam("metadataformat") String mdformat, @Parameter(description="The format to downlift metadata") @DefaultValue("html") @QueryParam("f") String format, @DefaultValue("false") @QueryParam("collectioncall") String collectioncall)
Gets metadata of a given collection.
Parameters
collectionid The feture type of the collection
mdformat The metadata format to use
format The downlift format in which to return the metadata
collectioncall indicates whether this method has been called from a higher level method
Returns
The metadata as String
References ResultMetadataFormatter.formatter(), TripleStoreConnector.getFeatureTypeInformation(), ResultMetadataFormatter.getFormatter(), and ResultMetadataFormatter.mimeType.
{
                 if (collectionid == null) {
                         throw new NotFoundException();
                 }
                 JSONObject workingobj = null;
                 for (int i = 0; i < wfsconf.getJSONArray("datasets").length(); i++) {
                         JSONObject curobj = wfsconf.getJSONArray("datasets").getJSONObject(i);
                         if (curobj.getString("name").equalsIgnoreCase(collectionid)) {
                                 workingobj = curobj;
                                 break;
                         }
                 }
                 if (workingobj == null) {
                         throw new NotFoundException();
                 }
                 if (!featureTypeCache.containsKey(collectionid.toLowerCase())) {
                         featureTypeCache.put(collectionid.toLowerCase(),
                                         TripleStoreConnector.getFeatureTypeInformation(workingobj.getString("query"),
                                                         workingobj.getString("triplestore"), workingobj.getString("name"), workingobj));
                 }
                 String collectionurl=wfsconf.getString("baseurl") + "/collections/" + collectionid;
                 try {
                         return Response.ok(ResultMetadataFormatter.getFormatter(mdformat)
                                         .formatter(collectionid, collectioncall, collectionurl, workingobj,format))
                                         .type(ResultMetadataFormatter.getFormatter(mdformat).mimeType).build();
                 } catch (XMLStreamException e1) {
                         e1.printStackTrace();
                         return this.createExceptionResponse(e1, "");
                 }
         }
getCollectionsMetadata()
Response getCollectionsMetadata (@Parameter(description="The format of the collection page") @DefaultValue("html") @QueryParam("f") String format)
Returns the metadata of collections registered in the SemanticWFS.
Parameters
format The metadataformat in which to return the results
Returns
The results as String
{
                 StringWriter strwriter = new StringWriter();
                 XMLOutputFactory output = XMLOutputFactory.newInstance();
                 XMLStreamWriter writer;
                 try {
                         writer = new IndentingXMLStreamWriter(output.createXMLStreamWriter(strwriter));
                         writer.writeStartDocument();
                         writer.setPrefix("gmd", "http://www.isotc211.org/2005/gmd");
                         writer.setPrefix("gmx", "http://www.isotc211.org/2005/gmx");
                         writer.setPrefix("gco", "http://www.isotc211.org/2005/gco");
                         writer.setPrefix("csw", "http://www.opengis.net/cat/csw/2.0.2");
                         writer.writeStartElement("http://www.opengis.net/cat/csw/2.0.2", "GetRecordsResponse");
                         writer.writeNamespace("csw", "http://www.opengis.net/cat/csw/2.0.2");
                         writer.writeStartElement("http://www.opengis.net/cat/csw/2.0.2", "SearchStatus");
                         writer.writeAttribute("timestamp", new Date(System.currentTimeMillis()).toGMTString());
                         writer.writeEndElement();
                         writer.writeStartElement("http://www.opengis.net/cat/csw/2.0.2", "SearchResults");
                         writer.flush();
                         this.xmlwriter = writer;
                         for (int i = 0; i < wfsconf.getJSONArray("datasets").length(); i++) {
                                 JSONObject curobj = wfsconf.getJSONArray("datasets").getJSONObject(i);
                                 getCollectionMetadata(curobj.getString("name"), "gmd", "true","");
                         }
                         writer.writeEndElement();
                         writer.writeEndDocument();
                         writer.flush();
                         return Response.ok(strwriter.toString()).type(MediaType.APPLICATION_XML).build();
                 } catch (XMLStreamException e) {
                         e.printStackTrace();
                         return this.createExceptionResponse(e, "");
                 }
         }
getCollectionStyle()
Response getCollectionStyle (@Parameter(description="Feature type name") @PathParam("collectionid") String collectionid, @Parameter(description="Style id") @PathParam("styleid") String styleid, @Parameter(description="Return format") @DefaultValue("html") @QueryParam("f") String format)
Gets a style for a given featuretype with a given style identifier.
Parameters
collectionid the featuretype name
styleid the styleid
format the format in which the style is returned
Returns
The style as String
References TripleStoreConnector.getStyle(), StyleObject.toHTML(), StyleObject.toJSON(), StyleObject.toString(), and StyleObject.toXML().
{
                 if (collectionid == null) {
                         throw new NotFoundException();
                 }
                 JSONObject workingobj = null;
                 for (int i = 0; i < wfsconf.getJSONArray("datasets").length(); i++) {
                         JSONObject curobj = wfsconf.getJSONArray("datasets").getJSONObject(i);
                         if (curobj.getString("name").equalsIgnoreCase(collectionid)) {
                                 workingobj = curobj;
                                 break;
                         }
                 }
                 if (workingobj == null) {
                         throw new NotFoundException();
                 }
                 StyleObject obj = TripleStoreConnector.getStyle(collectionid, styleid, workingobj.getString("triplestore"),
                                 workingobj.getString("namespace"));
                 if (obj == null) {
                         throw new NotFoundException();
                 }
                 if (format.contains("json")) {
                         return Response.ok(obj.toJSON()).type(MediaType.APPLICATION_JSON).build();
                 } else if (format.contains("xml")) {
                         return Response.ok(obj.toXML()).type(MediaType.APPLICATION_XML).build();
                 } else if (format.contains("html")) {
                         return Response.ok(obj.toHTML()).type(MediaType.TEXT_HTML).build();
                 }
                 return Response.ok(obj.toString()).type(MediaType.TEXT_PLAIN).build();
         }
getCollectionStyles()
Response getCollectionStyles (@Parameter(description="Feature type name") @PathParam("collectionid") String collectionid, @Parameter(description="Return type") @DefaultValue("html") @QueryParam("f") String format)
Gets a list of all styles for a given featuretype.
Parameters
collectionid the featuretype name
f the format in which the style is returned
Returns
The style as String
References TripleStoreConnector.getStyleNames().
{
                 if (collectionid == null) {
                         throw new NotFoundException();
                 }
                 JSONObject workingobj = null;
                 for (int i = 0; i < wfsconf.getJSONArray("datasets").length(); i++) {
                         JSONObject curobj = wfsconf.getJSONArray("datasets").getJSONObject(i);
                         if (curobj.getString("name").equalsIgnoreCase(collectionid)) {
                                 workingobj = curobj;
                                 break;
                         }
                 }
                 if (workingobj == null) {
                         throw new NotFoundException();
                 }
                 if (format.contains("json")) {
                         return Response.ok(TripleStoreConnector.getStyleNames(wfsconf.getString("baseurl"), workingobj, format))
                                         .type(MediaType.APPLICATION_JSON).build();
                 } else if (format.contains("html")) {
                         return Response.ok(TripleStoreConnector.getStyleNames(wfsconf.getString("baseurl"), workingobj, format))
                                         .type(MediaType.TEXT_HTML).build();
                 }
                 return Response.ok(TripleStoreConnector.getStyleNames(wfsconf.getString("baseurl"), workingobj, format))
                                 .type(MediaType.APPLICATION_XML).build();
         }
getEndpoints()
Response getEndpoints ()
Gets available SPARQL endpoitns from the triplestore configuration.
Returns
A JSON document containing SPARQL endpoint descriptions
{
                 return Response.ok(triplestoreconf.toString(2)).type(MediaType.APPLICATION_JSON).build();
         }
getFeature()
Response getFeature (@QueryParam("typename") String typename, @Parameter(description="The output format of the WFS service request") @DefaultValue("json") @QueryParam("outputFormat") String output, @Parameter(description="The amount of features to be returned", example="10") @DefaultValue("10") @QueryParam("count") String count, @Parameter(description="The starting index of the WFS request") @DefaultValue("0") @QueryParam("startindex") String startindex, @Parameter(description="The name of the CRS to be used") @DefaultValue("") @QueryParam("srsName") String srsName, @Parameter(description="Indicates the sorting order") @DefaultValue("ASC") @QueryParam("sortBy") String sortBy, @Parameter(description="The style to apply to the returned collection if any") @DefaultValue("") @QueryParam("mapstyles") String style, @Parameter(description="The version of the WFS", example="2.0.0") @DefaultValue("2.0.0") @QueryParam("version") String version, @Parameter(description="Indicates a specific resource id to be queried") @DefaultValue("") @QueryParam("resourceid") String resourceids, @Parameter(description="A WFS filter expression") @DefaultValue("") @QueryParam("filter") String filter, @Parameter(description="The filter language to be used in the filterExpression parameter") @DefaultValue("CQL") @QueryParam("filterLanguage") String filterLanguage, @Parameter(description="The result type to return") @DefaultValue("results") @QueryParam("resultType") String resultType) throws JSONException, XMLStreamException
References TripleStoreConnector.executeQuery(), and TripleStoreConnector.getFeatureTypeInformation().
{
                 System.out.println(typename);
                 if (typename == null) {
                         throw new NotFoundException();
                 }
                 JSONObject workingobj = null;
                 for (int i = 0; i < wfsconf.getJSONArray("datasets").length(); i++) {
                         JSONObject curobj = wfsconf.getJSONArray("datasets").getJSONObject(i);
                         if (curobj.getString("name").equalsIgnoreCase(typename)) {
                                 workingobj = curobj;
                                 break;
                         }
                 }
                 if (workingobj == null)
                         throw new NotFoundException();
                 String res = "";
                 System.out.println(hitCache);
                 if (resultType.equalsIgnoreCase("hits") && hitCache.containsKey(typename.toLowerCase())
                                 && (hitCache.get(typename.toLowerCase()).getOne().getTime() + milliesInDays) > System
                                                 .currentTimeMillis()) {
                         res = hitCache.get(typename.toLowerCase()).getTwo();
                 } else {
                         if (!workingobj.has("attcount") && !workingobj.getString("query").contains("?rel")
                                         && !workingobj.getString("query").contains("?val")) {
                                 featureTypeCache.put(typename.toLowerCase(),
                                                 TripleStoreConnector.getFeatureTypeInformation(workingobj.getString("query"),
                                                                 workingobj.getString("triplestore"), workingobj.getString("name"), workingobj));
                                 workingobj.put("attcount", 1);
                         } else if (!workingobj.has("attcount")) {
                                 featureTypeCache.put(typename.toLowerCase(),
                                                 TripleStoreConnector.getFeatureTypeInformation(workingobj.getString("query"),
                                                                 workingobj.getString("triplestore"), workingobj.getString("name"), workingobj));
                         }
                         if (workingobj.getInt("attcount") == 0) {
                                 workingobj.put("attcount", 1);
                         }
                         try {
                                 res = TripleStoreConnector.executeQuery(workingobj.getString("query"),
                                                 workingobj.getString("triplestore"), output,
                                                 "" + count,
                                                 "" + startindex, "gml:featureMember",
                                                 typename, resourceids, workingobj, filter, resultType, srsName,"",
                                                 "", style,false,
                                                 (workingobj.has("invertXY")?workingobj.getBoolean("invertXY"):false),null);
                                 System.out.println(res);
                                 if (res==null || res.isEmpty()) {
                                         throw new NotFoundException();
                                 }
                                 if (resultType.equalsIgnoreCase("hits")) {
                                         hitCache.put(typename.toLowerCase(),
                                                         new Tuple<Date, String>(new Date(System.currentTimeMillis()), res));
                                 }
                         } catch (JSONException | XMLStreamException | IOException e1) {
                                 e1.printStackTrace();
                                 return this.createExceptionResponse(e1, "");
                         }
                 }
                 System.out.println(output);
                 if (output.contains("gml")) {
                         StringWriter strwriter = new StringWriter();
                         XMLOutputFactory outputf = XMLOutputFactory.newInstance();
                         XMLStreamWriter writer;
                         try {
                                 writer = new IndentingXMLStreamWriter(outputf.createXMLStreamWriter(strwriter));
                                 writer.writeStartDocument();
                                 writer.writeStartElement("wfs:FeatureCollection");
                                 writer.writeDefaultNamespace((wfsconf.getString("baseurl") + "/").replace("//", "/"));
                                 writer.writeNamespace("ows", "http://www.opengis.net/ows/1.1");
                                 writer.writeNamespace("sf", "http://www.opengis.net/ogcapi-features-1/1.0/sf");
                                 writer.writeNamespace("ogc", "http://www.opengis.net/ogc");
                                 writer.writeNamespace("gml", "http://www.opengis.net/gml");
                                 writer.writeNamespace("wfs", "http://www.opengis.net/wfs");
                                 writer.writeNamespace("xlink", "http://www.w3.org/1999/xlink");
                                 writer.setPrefix("gml", "http://www.opengis.net/gml");
                                 writer.setPrefix("wfs", "http://www.opengis.net/wfs");
                                 if (resultType.equalsIgnoreCase("hits")) {
                                         writer.writeAttribute("numberOfFeatures", res);
                                 } else {
                                         for (String ns : nameSpaceCache.get(typename.toLowerCase()).keySet()) {
                                                 writer.setPrefix(nameSpaceCache.get(typename.toLowerCase()).get(ns), ns);
                                                 writer.writeNamespace(nameSpaceCache.get(typename.toLowerCase()).get(ns), ns);
                                         }
                                         writer.writeCharacters("");
                                         writer.flush();
                                         strwriter.write(res);
                                 }
                                 writer.writeEndElement();
                                 writer.writeEndDocument();
                                 writer.flush();
                                 String result=strwriter.toString();
                                 String firstline=result.substring(0,result.indexOf(System.lineSeparator())).trim();
                                 if(firstline.isEmpty()) {
                                         return Response.ok(result.substring(result.indexOf(System.lineSeparator())+1)).type(MediaType.APPLICATION_XML).build();
                                 }else {
                                         return Response.ok(result).type(MediaType.APPLICATION_XML).build();
                                 }
                         } catch (Exception e) {
                                 e.printStackTrace();
                                 return this.createExceptionResponse(e, "");
                         }
                 } else if (output.contains("json")) {
                         JSONObject result = new JSONObject();
                         JSONArray links = new JSONArray();
                         JSONObject jsonresult = new JSONObject(res);
                         JSONArray features = jsonresult.getJSONArray("features");
                         if (jsonresult.has("@context")) {
                                 result.put("@context", jsonresult.getJSONObject("@context"));
                         }
                         result.put("type", "FeatureCollection");
                         result.put("links", links);
                         result.put("timeStamp", System.currentTimeMillis());
                         if (resultType.equalsIgnoreCase("hits")) {
                                 result.put("numberMatched", res);
                         } else {
                                 result.put("numberMatched", features.length());
                         }
                         result.put("numberReturned", features.length());
                         result.put("features", features);
                         System.out.println("EXPORT JSON: " + result.toString());
                         return Response.ok(result.toString(2)).type(MediaType.APPLICATION_JSON).build();
                 } else if (output.contains("html")) {
                         StringBuilder builder = new StringBuilder();
                         builder.append(htmlHead);
                         builder.append("<body><header><h1 align=\"center\">");
                         builder.append(typename);
                         builder.append("</h1></header><div class=\"container-fluid\" role=\"main\"><div class=\"row\">");
                         builder.append(res);
                         // builder.append("<script>$( document ).ready(function()
                         // {$('#queryres').DataTable({\"scrollX\":\"100%\",\"scrollCollapse\":
                         // true});});</script></div></div></div></body></html>");
                         return Response.ok(builder.toString()).type(MediaType.TEXT_HTML).build();
                 } else if (output.contains("csv") || output.contains("geouri") || output.contains("geohash")) {
                         return Response.ok(res).type(MediaType.TEXT_PLAIN).build();
                 } else if (output.contains("gpx")) {
                         return Response.ok(res).type(MediaType.TEXT_PLAIN).build();
                 }
                 return Response.ok("").type(MediaType.TEXT_PLAIN).build();
         }
getFeatureById()
Response getFeatureById (@Parameter(description="The collection id") @PathParam("collectionid") String collectionid, @Parameter(description="The feature id") @PathParam("featureid") String featureid, @Parameter(description="The style to be applied") @DefaultValue("") @QueryParam("style") String style, @Parameter(description="The format to be returned") @DefaultValue("html") @QueryParam("f") String format)
Returns a feature given its feature id.
Parameters
collectionid The feature type
featureid The feature id to return
style The style in which to style the feature
format The format in which to return the feature
Returns
The feature as String in the given format
References TripleStoreConnector.executeQuery(), TripleStoreConnector.getFeatureTypeInformation(), and ResultFormatter.resultMap.
{
                 System.out.println(collectionid + " - " + featureid + " - " + style);
                 if (collectionid == null) {
                         throw new NotFoundException();
                 }
                 JSONObject workingobj = null;
                 for (int i = 0; i < wfsconf.getJSONArray("datasets").length(); i++) {
                         JSONObject curobj = wfsconf.getJSONArray("datasets").getJSONObject(i);
                         if (curobj.getString("name").equalsIgnoreCase(collectionid)) {
                                 workingobj = curobj;
                                 break;
                         }
                 }
                 if (workingobj == null) {
                         throw new NotFoundException();
                 }
                 if (!workingobj.has("attcount") && !workingobj.getString("query").contains("?rel")
                                 && !workingobj.getString("query").contains("?val")) {
                         workingobj.put("attcount", 1);
                 } else if (!workingobj.has("attcount")) {
                         featureTypeCache.put(collectionid.toLowerCase(),
                                         TripleStoreConnector.getFeatureTypeInformation(workingobj.getString("query"),
                                                         workingobj.getString("triplestore"), workingobj.getString("name"), workingobj));
                 }
                 String query = workingobj.getString("query");
                 String res = "";
                 try {
                         res = TripleStoreConnector.executeQuery(query, workingobj.getString("triplestore"),
                                         format, "0", "0",
                                         "sf:featureMember", collectionid, featureid, workingobj,
                                         "", "", "","", "", style,false,
                                         (workingobj.has("invertXY")?workingobj.getBoolean("invertXY"):false),null);
                         System.out.println(res);
                         if (res == null || res.isEmpty()) {
                                 throw new NotFoundException();
                         }
                 } catch (JSONException | XMLStreamException | IOException e1) {
                         // TODO Auto-generated catch block
                         return this.createExceptionResponse(e1, "");
                 }
                 if (format != null && format.contains("json")) {
                         JSONObject result = new JSONObject();
                         JSONArray links = new JSONArray();
                         result.put("links", links);
                         for (ResultFormatter formatter : ResultFormatter.resultMap.values()) {
                                 JSONObject link = new JSONObject();
                                 if (formatter.exposedType.contains("geojson")) {
                                         link.put("rel", "self");
                                 } else {
                                         link.put("rel", "alternate");
                                 }
                                 link.put("href", wfsconf.getString("baseurl") + "/collections/" + collectionid + "/items/" + featureid
                                                 + "?f=" + formatter.exposedType);
                                 link.put("type", formatter.exposedType);
                                 link.put("title", featureid);
                                 links.put(link);
                         }
                         result.put("id", featureid);
                         JSONObject jsonresult = new JSONObject(res);
                         JSONObject features = jsonresult.getJSONArray("features").getJSONObject(0);
                         if (jsonresult.has("@context")) {
                                 result.put("@context", jsonresult.getJSONObject("@context"));
                         }
                         result.put("type", "Feature");
                         result.put("links", links);
                         result.put("timeStamp", System.currentTimeMillis());
                         result.put("numberMatched", features.length());
                         result.put("numberReturned", features.length());
                         result.put("geometry", features.getJSONObject("geometry"));
                         result.put("properties", features.getJSONObject("properties"));
                         return Response.ok(result.toString(2)).type(MediaType.APPLICATION_JSON).build();
                 } else if (format != null && format.contains("gml")) {
                         StringWriter strwriter = new StringWriter();
                         XMLOutputFactory output = XMLOutputFactory.newInstance();
                         XMLStreamWriter writer;
                         try {
                                 writer = new IndentingXMLStreamWriter(output.createXMLStreamWriter(strwriter));
                                 writer.writeStartDocument();
                                 writer.setDefaultNamespace("http://www.opengis.net/ogcapi-features-1/1.0");
                                 writer.setPrefix("atom", "http://www.w3.org/2005/Atom");
                                 writer.writeStartElement("sf:Feature");
                                 writer.writeAttribute("xmlns", "http://www.opengis.net/ogcapi-features-1/1.0");
                                 writer.writeAttribute("xmlns:atom", "http://www.w3.org/2005/Atom");
                                 writer.writeAttribute("xmlns:xsi", "http://www.w3.org/2001/XMLSchema-instance");
                                 writer.writeAttribute("xmlns:sf", "http://www.opengis.net/ogcapi-features-1/1.0/sf");
                                 writer.writeAttribute("xmlns:gml", "http://www.opengis.net/gml/3.2");
                                 writer.writeAttribute("service", "OGCAPI-FEATURES");
                                 writer.writeAttribute("version", "1.0.0");
                                 writer.writeStartElement("Title");
                                 writer.writeCharacters("");
                                 writer.writeEndElement();
                                 writer.writeStartElement("Description");
                                 writer.writeCharacters("");
                                 writer.writeEndElement();
                                 for (ResultFormatter formatter : ResultFormatter.resultMap.values()) {
                                         writer.writeStartElement("http://www.w3.org/2005/Atom", "link");
                                         if (formatter.exposedType.contains("json")) {
                                                 writer.writeAttribute("rel", "self");
                                         } else {
                                                 writer.writeAttribute("rel", "alternate");
                                         }
                                         writer.writeAttribute("title", workingobj.getString("name"));
                                         writer.writeAttribute("type", formatter.exposedType);
                                         writer.writeAttribute("href", wfsconf.getString("baseurl") + "/collections/"
                                                         + workingobj.getString("name") + "/items/+" + featureid + "?f=" + formatter.exposedType);
                                         writer.writeEndElement();
                                 }
                                 strwriter.append(res);
                                 writer.writeEndElement();
                                 writer.writeEndDocument();
                                 writer.flush();
                                 return Response.ok(strwriter.toString()).type(MediaType.APPLICATION_XML).build();
                         } catch (XMLStreamException e) {
                                 e.printStackTrace();
                                 return this.createExceptionResponse(e, "");
                         }
                 } else if (format == null || format.contains("html")) {
                         StringBuilder builder = new StringBuilder();
                         builder.append(htmlHead);
                         builder.append("<body><header id=\"header\"><h1 align=\"center\">");
                         builder.append(featureid);
                         builder.append("</h1></header>");
                         builder.append("<div class=\"sticky row crumbs\"><div class=\"col-sm-12 col-md-10 col-md-offset-1\">");
                         builder.append("<a href=\""+wfsconf.getString("baseurl")+"\">Landingpage</a> / <a href=\""+wfsconf.getString("baseurl")+"/collections/\">Collections</a> / <a href=\""+wfsconf.getString("baseurl")+"/collections/"+collectionid+"\">"+workingobj.getString("name")+"</a> / <a href=\""+wfsconf.getString("baseurl")+"/collections/"+collectionid+"/items?f=html\">Items</a> / <a href=\""+wfsconf.getString("baseurl")+"/collections/"+collectionid+"/items/"+featureid+"?f=html\">"+featureid+"</a>");
                     builder.append("</div></div>");
                         builder.append("<div class=\"container-fluid\" role=\"main\"><div class=\"row\">");
                         builder.append(res);
                         builder.append("</div></div></div></div><footer id=\"footer\"><table width=100%><tbody><tr><td><a href=\"" + wfsconf.getString("baseurl") + "/collections/"
                                         + collectionid + "?f=html\">Back to " + collectionid
                                         + " Collection</a></td><td align=right>This page in <a href=\"" + wfsconf.getString("baseurl")
                                         + "/collections/" + workingobj.getString("name") + "/items/" + featureid
                                         + "?f=gml\">[GML]</a> <a href=\"" + wfsconf.getString("baseurl") + "/collections/"
                                         + workingobj.getString("name") + "/items/" + featureid + "?f=json\">[JSON]</a></td></tr></tbody></table>");
                         builder.append("</footer></body></html>");
                         return Response.ok(builder.toString()).type(MediaType.TEXT_HTML).build();
                 } else {
                         return Response.ok(res).type(MediaType.TEXT_PLAIN).build();
                 }
         }
getFeatureByIdHTML()
Response getFeatureByIdHTML (@Parameter(description="The collection id") @PathParam("collectionid") String collectionid, @Parameter(description="The feature id") @PathParam("featureid") String featureid, @Parameter(description="The style to be applied") @DefaultValue("") @QueryParam("mapstyle") String style, @Parameter(description="The format to be returned") @DefaultValue("html") @QueryParam("f") String format)
Returns a feature given its feature id.
Parameters
collectionid The feature type
featureid The feature id to return
style The style in which to style the feature
format The format in which to return the feature
Returns
The feature as String in the given format
{
                 return getFeatureById(collectionid, featureid, style, format);
         }
getFeatureByIdJSON()
Response getFeatureByIdJSON (@Parameter(description="The collection id") @PathParam("collectionid") String collectionid, @Parameter(description="The feature id") @PathParam("featureid") String featureid, @Parameter(description="The style to be applied") @DefaultValue("") @QueryParam("mapstyle") String style, @Parameter(description="The format to be returned") @DefaultValue("json") @QueryParam("f") String format)
Returns a feature given its feature id.
Parameters
collectionid The feature type
featureid The feature id to return
style The style in which to style the feature
format The format in which to return the feature
Returns
The feature as String in the given format
{
                 return getFeatureById(collectionid, featureid, style, format);
         }
getFeatureByIdXML()
Response getFeatureByIdXML (@Parameter(description="The collection id") @PathParam("collectionid") String collectionid, @Parameter(description="The feature id") @PathParam("featureid") String featureid, @Parameter(description="The style to be applied") @DefaultValue("") @QueryParam("mapstyle") String style, @Parameter(description="The format to be returned") @DefaultValue("gml") @QueryParam("f") String format)
Returns a feature given its feature id.
Parameters
collectionid The feature type
featureid The feature id to return
style The style in which to style the feature
format The format in which to return the feature
Returns
The feature as String in the given format
{
                 return getFeatureById(collectionid, featureid, style, format);
         }
getFeatureTypes()
String getFeatureTypes ()
Returns featuretypes known by the SemanticWFS service.
Returns
The feature type document as JSON.
References User.toString().
{
                 return wfsconf.toString(2);
         }
getGeoClassesFromOntology()
Response getGeoClassesFromOntology (@Parameter(description="The SPARQL endpoint to load classes from") @QueryParam("endpoint") String endpoint)
Gets geospatial classes from a SPARQL endpoint.
Parameters
endpoint The SPARQL endpoint
Returns
A JSON document containing class descriptions
References TripleStoreConnector.getClassesFromOntology().
{
                 if(triplestoreconf.getJSONObject("endpoints").has(endpoint)) {
                         Map<String,String> classes=TripleStoreConnector.getClassesFromOntology(triplestoreconf.getJSONObject("endpoints").getJSONObject(endpoint));
                         JSONObject result=new JSONObject();
                         for(String cls:classes.keySet()) {
                                 result.put(cls, classes.get(cls));
                         }
                         return Response.ok(result.toString(2)).type(MediaType.APPLICATION_JSON).build();
                 }else {
                         return Response.ok("{}").type(MediaType.APPLICATION_JSON).build();
                 }
         }
getGmlObject()
Response getGmlObject (@QueryParam("typename") String typename, @QueryParam("GmlObjectId") String gmlobjectid, @DefaultValue("4") @QueryParam("traverseXlinkDepth") String traverseXlinkDepth, @DefaultValue("gml") @QueryParam("outputFormat") String output)
{
                 try {
                         return this.getFeature(typename, output, "1", "0", "", "ASC", "", "2.0.0", gmlobjectid, "", "CQL", "");
                 } catch (JSONException | XMLStreamException e) {
                         // TODO Auto-generated catch block
                         e.printStackTrace();
                         return this.createExceptionResponse(e, "");
                 }
         }
getPropertiesByClass()
Response getPropertiesByClass (@Parameter(description="The SPARQL endpoint to load properties from") @QueryParam("endpoint") String endpoint, @Parameter(description="The class from which properties should be loaded") @QueryParam("class") String classs)
Gets available properties associated with a certain class.
Parameters
endpoint The SPARQL endpoint to query
classs The class to use in the query
Returns
A JSON document containing the queried properties
References TripleStoreConnector.getPropertiesByClass().
{
                 Map<String, String> classes=TripleStoreConnector.getPropertiesByClass(endpoint, classs);
                 JSONObject result=new JSONObject();
                 for(String cls:classes.keySet()) {
                         result.put(cls,classes.get(cls).toString());
                 }
                 return Response.ok(result.toString(2)).type(MediaType.APPLICATION_JSON).build();
         }
getPropertyValue()
Response getPropertyValue (@Parameter(description="Feature type to query") @QueryParam("typename") String typename, @QueryParam("valuereference") String propertyname, @DefaultValue("json") @QueryParam("outputFormat") String output, @DefaultValue("") @QueryParam("resourceids") String resourceids, @DefaultValue("") @QueryParam("filter") String filter, @DefaultValue("0") @QueryParam("count") String count, @DefaultValue("results") @QueryParam("resultType") String resultType)
References TripleStoreConnector.executePropertyValueQuery(), and TripleStoreConnector.getFeatureTypeInformation().
{
                 System.out.println(typename);
                 System.out.println(propertyname);
                 if (typename == null || propertyname == null) {
                         throw new NotFoundException();
                 }
                 JSONObject workingobj = null;
                 for (int i = 0; i < wfsconf.getJSONArray("datasets").length(); i++) {
                         JSONObject curobj = wfsconf.getJSONArray("datasets").getJSONObject(i);
                         if (curobj.getString("name").equalsIgnoreCase(typename)) {
                                 workingobj = curobj;
                                 break;
                         }
                 }
                 if (workingobj == null)
                         throw new NotFoundException();
                 if (!propertyname.startsWith("http")) {
                         if (!featureTypeCache.containsKey(typename.toLowerCase())) {
                                 featureTypeCache.put(typename.toLowerCase(),
                                                 TripleStoreConnector.getFeatureTypeInformation(workingobj.getString("query"),
                                                                 workingobj.getString("triplestore"), workingobj.getString("name"), workingobj));
                         }
                         for (String key : featureTypeCache.get(typename.toLowerCase()).keySet()) {
                                 if (key.contains(propertyname)) {
                                         propertyname = key;
                                         break;
                                 }
                         }
                 }
                 String res = "";
                 try {
                         res = TripleStoreConnector.executePropertyValueQuery(workingobj.getString("triplestore"), output,
                                         propertyname, "gml:featureMember", typename, resourceids, workingobj, filter, count, resultType,
                                         "",null);
                         System.out.println(res);
                 } catch (JSONException | XMLStreamException | IOException e1) {
                         e1.printStackTrace();
                         return this.createExceptionResponse(e1, "");
                 }
                 if (resultType.equalsIgnoreCase("hits")) {
                         return Response.ok(res).type(MediaType.TEXT_PLAIN).build();
                 }
                 if (output != null && output.contains("json")) {
                         return Response.ok(res).type(MediaType.APPLICATION_JSON).build();
                 } else if (output != null && output.contains("gml")) {
                         StringWriter strwriter = new StringWriter();
                         XMLOutputFactory outputf = XMLOutputFactory.newInstance();
                         XMLStreamWriter writer;
                         try {
                                 writer = new IndentingXMLStreamWriter(outputf.createXMLStreamWriter(strwriter));
                                 writer.writeStartDocument();
                                 writer.writeStartElement("ValueCollection");
                                 writer.writeDefaultNamespace("http://www.opengis.net/wfs/2.0");
                                 writer.writeCharacters("");
                                 writer.flush();
                                 strwriter.write(res);
                                 writer.writeEndElement();
                                 writer.writeEndDocument();
                                 writer.flush();
                         } catch (Exception e) {
                                 e.printStackTrace();
                                 return this.createExceptionResponse(e, "");
                         }
                         return Response.ok(strwriter.toString()).type(MediaType.APPLICATION_XML).build();
                 } else if (output != null && output.contains("html")) {
                         StringBuilder builder = new StringBuilder();
                         builder.append("<html><head></head><body><header id=\"header\"><h1 align=center>PropertyRequest: " + typename + "["
                                         + propertyname
                                         + "]</h1></header><div class=\"container-fluid\" role=\"main\"><div class=\"row\"><div class=\"col-sm-12\">");
                         builder.append(res);
                         builder.append("</div></div></div><footer id=\"footer\"><a href=\"" + wfsconf.getString("baseurl")
                                         + "/?f=html\">Back to LandingPage</a></footer></body></html>");
                         return Response.ok(builder.toString()).type(MediaType.TEXT_HTML).build();
                 } else if (output != null) {
                         return Response.ok(res).type(MediaType.TEXT_PLAIN).build();
                 }
                 return Response.ok("").type(MediaType.TEXT_PLAIN).build();
         }
getSchema()
Response getSchema (@Parameter(description="The collection id for which to return the schema") @PathParam("collectionid") String collectionid, @Parameter(description="The format in which the schema should be returned", example="json") @DefaultValue("gml") @QueryParam("f") String format)
Returns a schema of a given collection.
Parameters
collectionid The feature collection id
format The format in which to return the collection
Returns
The returned collection as String
{
                 if (format.contains("json")) {
                         return this.describeFeatureTypeJSON(collectionid, "1.0.0");
                 } else {
                         try {
                                 return this.describeFeatureType(collectionid, "2.0.0");
                         } catch (XMLStreamException e) {
                                 // TODO Auto-generated catch block
                                 e.printStackTrace();
                                 throw new NotFoundException();
                         }
                 }
         }
landingPage()
Response landingPage (@Parameter(description="The format of the landingpage") @DefaultValue("html") @QueryParam("f") String format)
Returns the landing page of the OGC API Features service.
Parameters
format The format in which the page is to be returned
Returns
The landing page as String
References ResultFormatter.resultMap.
{
                 if (format == null || format.contains("json")) {
                         JSONObject result = new JSONObject();
                         JSONArray links = new JSONArray();
                         JSONObject link = new JSONObject();
                         link.put("href", wfsconf.getString("baseurl") + "?f=json");
                         link.put("rel", "self");
                         link.put("type", "application/json");
                         link.put("title", "This document");
                         links.put(link);
                         link = new JSONObject();
                         link.put("href", wfsconf.getString("baseurl") + "?f=xml");
                         link.put("rel", "alternate");
                         link.put("type", "application/xml");
                         link.put("title", "This document as XML");
                         links.put(link);
                         link = new JSONObject();
                         link.put("href", wfsconf.getString("baseurl") + "?f=html");
                         link.put("rel", "alternate");
                         link.put("type", "text/html");
                         link.put("title", "This document as HTML");
                         links.put(link);
                         link = new JSONObject();
                         link.put("href", wfsconf.getString("baseurl") + "/openapi3");
                         link.put("rel", "service-desc");
                         link.put("type", "application/vnd.oai.openapi+json;version=3.0");
                         link.put("title", "The API definition (JSON)");
                         links.put(link);
                         link = new JSONObject();
                         link.put("href", wfsconf.getString("baseurl") + "/openapi3y");
                         link.put("rel", "service-desc");
                         link.put("type", "application/vnd.oai.openapi+yaml;version=3.0");
                         link.put("title", "The API definition (YAML)");
                         links.put(link);
                         link = new JSONObject();
                         link.put("href", wfsconf.getString("baseurl") + "/api/");
                         link.put("rel", "service-doc");
                         link.put("type", "text/html");
                         link.put("title", "The API definition (HTML)");
                         links.put(link);
                         link = new JSONObject();
                         link.put("href", wfsconf.getString("baseurl") + "/conformance?f=html");
                         link.put("rel", "conformance");
                         link.put("type", "text/html");
                         link.put("title", "Conformance Declaration as HTML");
                         links.put(link);
                         link = new JSONObject();
                         link.put("href", wfsconf.getString("baseurl") + "/conformance?f=xml");
                         link.put("rel", "conformance");
                         link.put("type", "application/xml");
                         link.put("title", "Conformance Declaration as XML");
                         links.put(link);
                         link = new JSONObject();
                         link.put("href", wfsconf.getString("baseurl") + "/conformance?f=json");
                         link.put("rel", "conformance");
                         link.put("type", "application/json");
                         link.put("title", "Conformance Declaration as JSON");
                         links.put(link);
                         link = new JSONObject();
                         link.put("href", wfsconf.getString("baseurl") + "/collections?f=json");
                         link.put("rel", "data");
                         link.put("type", "application/json");
                         link.put("title", "Collections Metadata as JSON");
                         links.put(link);
                         link = new JSONObject();
                         link.put("href", wfsconf.getString("baseurl") + "/collections?f=xml");
                         link.put("rel", "data");
                         link.put("type", "application/xml");
                         link.put("title", "Collections Metadata as XML");
                         links.put(link);
                         link = new JSONObject();
                         link.put("href", wfsconf.getString("baseurl") + "/collections?f=html");
                         link.put("rel", "data");
                         link.put("type", "text/html");
                         link.put("title", "Collections Metadata as HTML");
                         links.put(link);
                         result.put("title", wfsconf.getString("servicetitle"));
                         result.put("description", wfsconf.getString("servicedescription"));
                         result.put("links", links);
                         JSONArray collections=new JSONArray();
                         result.put("collections", collections);
                         for (int i = 0; i < wfsconf.getJSONArray("datasets").length(); i++) {
                                 JSONObject coll = new JSONObject();
                                 JSONObject curobj = wfsconf.getJSONArray("datasets").getJSONObject(i);
                                 coll.put("id", curobj.getString("name"));
                                 coll.put("name", curobj.getString("name"));
                                 coll.put("title", curobj.getString("name"));
                                 if(curobj.has("description"))
                                         coll.put("description", curobj.getString("description"));
                                 /*JSONObject extent = new JSONObject();
                                 JSONArray spatial = new JSONArray();
                                 JSONArray temporal=new JSONArray();
                                 temporal.put("1970-01-01T00:00:00Z");
                                 temporal.put("2020-08-22T22:10:44Z");*/
                                 JSONArray crs = new JSONArray();
                                 crs.put("http://www.opengis.net/def/crs/EPSG/0/"+curobj.getString("targetCRS").substring(curobj.getString("targetCRS").indexOf(":")+1));
                                 coll.put("storageCRS", "http://www.opengis.net/def/crs/EPSG/0/"+curobj.getString("targetCRS").substring(curobj.getString("targetCRS").indexOf(":")+1));
                                 coll.put("crs", crs);
                                 //JSONArray crs = new JSONArray();
                                 //crs.put("http://www.opengis.net/def/crs/OGC/1.3/CRS84");
                                 //coll.put("crs", crs);
                                 /*coll.put("extent", extent);
                                 extent.put("spatial", spatial);
                                 extent.put("temporal", temporal);*/
                                 JSONArray colinks = new JSONArray();
                                 for (ResultFormatter formatter : ResultFormatter.resultMap.values()) {
                                         link = new JSONObject();
                                         link.put("rel", "item");
                                         link.put("href", wfsconf.getString("baseurl") + "/collections/" + curobj.getString("name")
                                                         + "/items" + "?f=" + formatter.urlformat);
                                         link.put("type", formatter.exposedType);
                                         link.put("title", curobj.getString("name"));
                                         colinks.put(link);
                                 }
                                 link.put("rel", "self");
                                 link.put("title", "This document");
                                 link.put("type", "application/json");
                                 link.put("href", wfsconf.get("baseurl") + "/collections/"+curobj.getString("name")+"?f=json");
                                 colinks.put(link);
                                 link = new JSONObject();
                                 link.put("rel", "alternate");
                                 link.put("title", "This document as XML");
                                 link.put("type", "application/xml");
                                 link.put("href", wfsconf.get("baseurl") + "/collections/"+curobj.getString("name")+"?f=gml");
                                 colinks.put(link);
                                 link = new JSONObject();
                                 link.put("rel", "alternate");
                                 link.put("title", "This document as HTML");
                                 link.put("type", "text/html");
                                 link.put("href", wfsconf.get("baseurl") + "/collections/"+curobj.getString("name")+"?f=html");
                                 colinks.put(link);
                                 link = new JSONObject();
                                 link.put("rel", "describedBy");
                                 link.put("title", "XML Schema for this dataset");
                                 link.put("type", "application/xml");
                                 link.put("href", "http://www.acme.com/3.0/wfs/collections/"+curobj.getString("name")+"/schema");
                                 colinks.put(link);
                                 coll.put("links", colinks);
                                 collections.put(coll);
                         }
                         return Response.ok(result.toString(2)).type(MediaType.APPLICATION_JSON).build();
                 } else if (format.contains("xml")) {
                         StringWriter strwriter = new StringWriter();
                         XMLOutputFactory output = XMLOutputFactory.newInstance();
                         XMLStreamWriter writer;
                         try {
                                 writer = new IndentingXMLStreamWriter(output.createXMLStreamWriter(strwriter));
                                 writer.writeStartDocument();
                                 writer.setDefaultNamespace("http://www.opengis.net/ogcapi-features-1/1.0");
                                 writer.writeStartElement("LandingPage");
                                 writer.setPrefix("atom", "http://www.w3.org/2005/Atom");
                                 writer.writeAttribute("xmlns:atom", "http://www.w3.org/2005/Atom");
                                 writer.writeAttribute("xmlns:xsi", "http://www.w3.org/2001/XMLSchema-instance");
                                 writer.writeAttribute("xmlns:sf", "http://www.opengis.net/ogcapi-features-1/1.0/sf");
                                 writer.writeAttribute("xmlns:gml", "http://www.opengis.net/gml/3.2");
                                 writer.writeAttribute("service", "OGCAPI-FEATURES");
                                 writer.writeAttribute("version", "1.0.0");
                                 writer.writeStartElement("Title");
                                 writer.writeCharacters(wfsconf.getString("servicetitle"));
                                 writer.writeEndElement();
                                 writer.writeStartElement("Description");
                                 writer.writeCharacters(wfsconf.getString("servicedescription"));
                                 writer.writeEndElement();
                                 writer.writeStartElement("http://www.w3.org/2005/Atom", "link");
                                 writer.writeAttribute("rel", "self");
                                 writer.writeAttribute("title", "This document");
                                 writer.writeAttribute("type", "application/xml");
                                 writer.writeAttribute("href", wfsconf.getString("baseurl") + "/?f=gml");
                                 writer.writeEndElement();
                                 writer.writeStartElement("http://www.w3.org/2005/Atom", "link");
                                 writer.writeAttribute("rel", "alternate");
                                 writer.writeAttribute("title", "This document as JSON");
                                 writer.writeAttribute("type", "application/json");
                                 writer.writeAttribute("href", wfsconf.getString("baseurl") + "/?f=json");
                                 writer.writeEndElement();
                                 writer.writeStartElement("http://www.w3.org/2005/Atom", "link");
                                 writer.writeAttribute("rel", "alternate");
                                 writer.writeAttribute("title", "This document as HTML");
                                 writer.writeAttribute("type", "text/html");
                                 writer.writeAttribute("href", wfsconf.getString("baseurl") + "/?f=html");
                                 writer.writeEndElement();
                                 writer.writeStartElement("http://www.w3.org/2005/Atom", "link");
                                 writer.writeAttribute("rel", "service-doc");
                                 writer.writeAttribute("title", "The API definition (HTML)");
                                 writer.writeAttribute("type", "text/html");
                                 writer.writeAttribute("href",  wfsconf.getString("baseurl") + "/api/");
                                 writer.writeEndElement();
                                 writer.writeStartElement("http://www.w3.org/2005/Atom", "link");
                                 writer.writeAttribute("rel", "service-desc");
                                 writer.writeAttribute("title", "The API definition (YAML)");
                                 writer.writeAttribute("type", "application/vnd.oai.openapi+yaml;version=3.0");
                                 writer.writeAttribute("href",  wfsconf.getString("baseurl") + "/openapi3y");
                                 writer.writeEndElement();
                                 writer.writeStartElement("http://www.w3.org/2005/Atom", "link");
                                 writer.writeAttribute("rel", "service-desc");
                                 writer.writeAttribute("title", "The API defnition (JSON)");
                                 writer.writeAttribute("type", "application/vnd.oai.openapi+json;version=3.0");
                                 writer.writeAttribute("href",  wfsconf.getString("baseurl") + "/openapi3");
                                 writer.writeEndElement();
                                 writer.writeStartElement("http://www.w3.org/2005/Atom", "link");
                                 writer.writeAttribute("rel", "conformance");
                                 writer.writeAttribute("title", "Conformance Declaration as JSON");
                                 writer.writeAttribute("type", "application/json");
                                 writer.writeAttribute("href", wfsconf.getString("baseurl") + "/conformance?f=json");
                                 writer.writeEndElement();
                                 writer.writeStartElement("http://www.w3.org/2005/Atom", "link");
                                 writer.writeAttribute("rel", "conformance");
                                 writer.writeAttribute("title", "Conformance Declaration as XML");
                                 writer.writeAttribute("type", "application/xml");
                                 writer.writeAttribute("href", wfsconf.getString("baseurl") + "/conformance?f=gml");
                                 writer.writeEndElement();
                                 writer.writeStartElement("http://www.w3.org/2005/Atom", "link");
                                 writer.writeAttribute("rel", "conformance");
                                 writer.writeAttribute("title", "Conformance Declaration as HTML");
                                 writer.writeAttribute("type", "text/html");
                                 writer.writeAttribute("href", wfsconf.getString("baseurl") + "/conformance?f=html");
                                 writer.writeEndElement();
                                 writer.writeStartElement("http://www.w3.org/2005/Atom", "link");
                                 writer.writeAttribute("rel", "data");
                                 writer.writeAttribute("title", "Collections Metadata as JSON");
                                 writer.writeAttribute("type", "application/json");
                                 writer.writeAttribute("href", wfsconf.getString("baseurl") + "/collections?f=json");
                                 writer.writeEndElement();
                                 writer.writeStartElement("http://www.w3.org/2005/Atom", "link");
                                 writer.writeAttribute("rel", "data");
                                 writer.writeAttribute("title", "Collections Metadata as XML");
                                 writer.writeAttribute("type", "application/xml");
                                 writer.writeAttribute("href", wfsconf.getString("baseurl") + "/collections?f=gml");
                                 writer.writeEndElement();
                                 writer.writeStartElement("http://www.w3.org/2005/Atom", "link");
                                 writer.writeAttribute("rel", "data");
                                 writer.writeAttribute("title", "Collections Metadata as HTML");
                                 writer.writeAttribute("type", "text/html");
                                 writer.writeAttribute("href", wfsconf.getString("baseurl") + "/collections?f=html");
                                 writer.writeEndElement();
                                 writer.writeEndElement();
                                 writer.writeEndDocument();
                                 writer.flush();
                                 return Response.ok(strwriter.toString()).type(MediaType.APPLICATION_XML).build();
                         } catch (XMLStreamException e) {
                                 // TODO Auto-generated catch block
                                 return this.createExceptionResponse(e, "");
                         }
                 } else if (format.contains("html")) {
                         StringBuilder builder = new StringBuilder();
                         builder.append(htmlHead);
                         builder.append("<body><header id=\"header\"><h1 align=\"center\">LandingPage: " + wfsconf.getString("servicetitle"));
                         builder.append("</h1></header>");
                         builder.append("<div class=\"sticky row crumbs\"><div class=\"col-sm-12 col-md-10 col-md-offset-1\">");
                         builder.append("<a href=\""+wfsconf.getString("baseurl")+"\">Landingpage</a>");
                     builder.append("</div></div>");
                         builder.append("<div class=\"container-fluid\" role=\"main\"><div class=\"row\"><div class=\"col-sm-12\"><p>"
                                                         + wfsconf.getString("servicedescription") + "</p><ul>");
                         builder.append("<li>API Documentation in <a href=\"" + wfsconf.getString("baseurl")
                                         + "/api/\">[HTML]</a>");
                         builder.append(" <a href=\"" + wfsconf.getString("baseurl") + "/openapi.yaml\">[YAML]</a>");
                         builder.append(" <a href=\"" + wfsconf.getString("baseurl") + "/openapi.json\">[JSON]</a></li>");
                         builder.append("<li>Conformance Declaration in <a href=\"" + wfsconf.getString("baseurl")
                                         + "/conformance?f=html\">[HTML]</a>");
                         builder.append(" <a href=\"" + wfsconf.getString("baseurl") + "/conformance?f=gml\">[XML]</a>");
                         builder.append(" <a href=\"" + wfsconf.getString("baseurl") + "/conformance?f=json\">[JSON]</a></li>");
                         builder.append("<li>Collections Metadata in <a href=\"" + wfsconf.getString("baseurl")
                                         + "/collections?f=html\">[HTML]</a>");
                         builder.append(" <a href=\"" + wfsconf.getString("baseurl") + "/collections?f=gml\">[XML]</a>");
                         builder.append(" <a href=\"" + wfsconf.getString("baseurl") + "/collections?f=json\">[JSON]</a></li></ul>");
                         builder.append("This homepage also exposes a WFS 1.0.0, 1.1.0, 2.0.0 compatible Webservice:<ul>");
                         builder.append("<li>GetCapabilities WFS 1.0.0 ");
                         builder.append("<a href=\"" + wfsconf.getString("baseurl")
                                         + "/wfs?REQUEST=getCapabilities&VERSION=1.0.0\">[XML]</a><br/>");
                         builder.append("</li><li>GetCapabilities WFS 1.1.0 ");
                         builder.append("<a href=\"" + wfsconf.getString("baseurl")
                                         + "/wfs?REQUEST=getCapabilities&VERSION=1.1.0\">[XML]</a>");
                         builder.append("</li><li>GetCapabilities WFS 2.0.0 ");
                         builder.append("<a href=\"" + wfsconf.getString("baseurl")
                                         + "/wfs?REQUEST=getCapabilities&VERSION=2.0.0\">[XML]</a>");
                         builder.append(
                                         "</li></ul>Local Options:<ul><li><a href=\""+ wfsconf.getString("baseurl")+"/config/geotreeview.html\">Ontology Browser</a></li>"
                                                         + "<li><a href=\""+wfsconf.getString("baseurl")+"/config/queryinterface.html\">SPARQL Query Interface</a></li>"
                                                         + "<li><a href=\""+ wfsconf.getString("baseurl")
                                                         + "/config/configuration.html\">Semantic WFS Configuration</a></li><li><a href=\"../importer/\">Semantic Uplift Tools</a></li></ul></div></div></div><footer id=\"footer\"><table width=100%><tbody><tr><td><a href=\"" + wfsconf.getString("baseurl")
                                         + "/?f=html\">Back to LandingPage</a></td><td align=right>This page in <a href=\""
                                         + wfsconf.getString("baseurl") + "/?f=xml\">[XML]</a> <a href=\""
                                         + wfsconf.getString("baseurl")
                                         + "/?f=json\">[JSON]</a></td></tr></table></footer></body></html>");
                         return Response.ok(builder.toString()).type(MediaType.TEXT_HTML).build();
                 } else {
                         throw new NotFoundException();
                 }
         }
landingPageHTML()
Response landingPageHTML (@Parameter(description="The format of the landingpage") @DefaultValue("html") @QueryParam("f") String format)
{
                 return landingPage(format);
         }
landingPageJSON()
Response landingPageJSON (@Parameter(description="The format of the landingpage") @DefaultValue("json") @QueryParam("f") String format)
{
                 return landingPage(format);
         }
landingPageXML()
Response landingPageXML (@Parameter(description="The format of the landingpage") @DefaultValue("xml") @QueryParam("f") String format)
{
                 return landingPage(format);
         }
lockFeature()
String lockFeature ()
Lock Feature method of the WFS specification.
Returns
{
                 return null;
         }
login()
Response login (@Parameter(description="Username for authorization") @QueryParam("username") String username, @Parameter(description="Password for authorization") @QueryParam("password") String password)
Performs a login returning an authtoken if successful.
Parameters
username The username
password The password
Returns
An authtoken if successful, an emptry String if not
References User.authToken, UserManagementConnection.getInstance(), and UserManagementConnection.login().
{
                 final String dir = System.getProperty("user.dir");
         System.out.println("current dir = " + dir);
         User user=UserManagementConnection.getInstance().login(username, password);
         if(user!=null) {
                 return Response.ok(user.authToken).type(MediaType.TEXT_PLAIN).build();
         }
         return Response.ok("").type(MediaType.TEXT_PLAIN).build();
         }
openapiJSON()
Response openapiJSON ()
References OpenAPIMediaType.OA3_TYPE.
{
                 System.out.println("OpenAPI JSON");
                 CloseableHttpClient httpClient = HttpClients.createDefault();
                 HttpGet request = new HttpGet(wfsconf.get("baseurl")+"/openapi.json");
                 CloseableHttpResponse response;
                 try {
                         response = httpClient.execute(request);
                         HttpEntity entity = response.getEntity();
                         String result = EntityUtils.toString(entity);
                         System.out.println(result);
                         response.close();
                         httpClient.close();
                         Response res=Response.status(Response.Status.OK).entity(result).type(OpenAPIMediaType.OA3_TYPE).build();
                         return res;
                 } catch (IOException e) {
                         // TODO Auto-generated catch block
                         e.printStackTrace();
                         return Response.ok("",OpenAPIMediaType.OA3_TYPE).build();
                 }
         }
openapiYAML()
Response openapiYAML ()
{
                 System.out.println("OpenAPI JSON");
                 CloseableHttpClient httpClient = HttpClients.createDefault();
                 HttpGet request = new HttpGet(wfsconf.get("baseurl")+"/openapi.yaml");
                 CloseableHttpResponse response;
                 try {
                         response = httpClient.execute(request);
                         HttpEntity entity = response.getEntity();
                         String result = EntityUtils.toString(entity);
                         System.out.println(result);
                         response.close();
                         httpClient.close();
                         Response res=Response.status(Response.Status.OK).entity(result).type("application/vnd.oai.openapi+yaml;version=3.0").build();
                         return res;
                 } catch (IOException e) {
                         // TODO Auto-generated catch block
                         e.printStackTrace();
                         return Response.ok("","application/vnd.oai.openapi+yaml;version=3.0").build();
                 }
         }
prefixes()
String prefixes ()
Returns prefixes known by the SemanticWFS service.
Returns
The prefix document as JSON.
References TripleStoreConnector.prefixCollection.
{
                 return TripleStoreConnector.prefixCollection;
         }
queryables()
Response queryables (@Parameter(description="The id of the collection to be considered") @PathParam("collectionid") String collectionid, @Parameter(description="The format in which the collection should be returned", example="geojson") @DefaultValue("html") @QueryParam("f") String format)
Returns information about the queryables of ths given feature type.
Parameters
collectionid The feature type to retrieve information about
format The format in which to retrieve the information
Returns
The queryables as String
References TripleStoreConnector.getFeatureTypeInformation(), ResultFormatter.getFormatter(), and TripleStoreConnector.getStyleNames().
{
                 if (collectionid == null) {
                         throw new NotFoundException();
                 }
                 JSONObject workingobj = null;
                 for (int i = 0; i < wfsconf.getJSONArray("datasets").length(); i++) {
                         JSONObject curobj = wfsconf.getJSONArray("datasets").getJSONObject(i);
                         if (curobj.getString("name").equalsIgnoreCase(collectionid)) {
                                 workingobj = curobj;
                                 break;
                         }
                 }
                 if (workingobj == null) {
                         throw new NotFoundException();
                 }
                 if (!featureTypeCache.containsKey(collectionid.toLowerCase())) {
                         featureTypeCache.put(collectionid.toLowerCase(),
                                         TripleStoreConnector.getFeatureTypeInformation(workingobj.getString("query"),
                                                         workingobj.getString("triplestore"), workingobj.getString("name"), workingobj));
                 }
                 Map<String, String> mapping = featureTypeCache.get(collectionid.toLowerCase());
                 StringBuilder builder = new StringBuilder();
                 StringBuilder builder2 = new StringBuilder();
                 JSONObject geojson = new JSONObject();
                 JSONObject geometry = new JSONObject();
                 JSONObject properties = new JSONObject();
                 geojson.put("type", "Feature");
                 geojson.put("id", collectionid);
                 geojson.put("geometry", geometry);
                 geojson.put("properties", properties);
                 builder.append(htmlHead);
                 builder.append("<body><header id=\"header\"><h1 align=\"center\">");
                 builder.append(collectionid+" Queryables");
                 builder.append("</h1></header>");
                 builder.append("<div class=\"sticky row crumbs\"><div class=\"col-sm-12 col-md-10 col-md-offset-1\">");
                 builder.append("<a href=\""+wfsconf.getString("baseurl")+"\">Landingpage</a> / <a href=\""+wfsconf.getString("baseurl")+"/collections/\">Collections</a> / <a href=\""+wfsconf.getString("baseurl")+"/collections/"+collectionid+"\">"+workingobj.getString("name")+"</a> / <a href=\""+wfsconf.getString("baseurl")+"/collections/"+collectionid+"/queryables?f=html\">Queryables</a>");
             builder.append("</div></div>");
                 builder.append("<div class=\"container-fluid\" role=\"main\"><div class=\"row\">");
                 builder.append("<table width=100%><tr><td width=\"100%\" rowspan=2>");
                 builder.append("<script>var overlayMaps={}; var overlayControl; var typeColumn=\""
                                 + (workingobj.has("typeColumn") ? workingobj.getString("typeColumn") : "")
                                 + "\"; var markercollection=[]; var epsg=\""
                                 + (workingobj.has("targetCRS") ? workingobj.getString("targetCRS") : "") + "\";");
                 builder2.append(((HTMLFormatter) ResultFormatter.getFormatter("html")).htmlHeader2);
                 builder2.append("</td><td>Contents:<table class=\"description\" border=\"1\"><tr><th>Value</th><th>Type</th>");
                 String lon = null, lat = null;
                 if (mapping != null) {
                         for (String elem : mapping.keySet()) {
                                 if (!elem.equals("http://www.opengis.net/ont/geosparql#hasGeometry")
                                                 && !elem.equals("http://www.w3.org/1999/02/22-rdf-syntax-ns#type")) {
                                         if (elem.contains("http")) {
                                                 if (elem.contains("#")) {
                                                         builder2.append("<tr><td align=center><a href=\"" + elem + "\">"
                                                                         + elem.substring(elem.lastIndexOf('#') + 1) + "</a> ");
                                                 } else {
                                                         builder2.append("<tr><td align=center><a href=\"" + elem + "\">"
                                                                         + elem.substring(elem.lastIndexOf('/') + 1) + "</a> ");
                                                 }
                                         } else {
                                                 builder2.append("<tr><td align=center>" + elem);
                                         }
                                         if (mapping.get(elem).contains("^^")) {
                                                 String type = mapping.get(elem).substring(mapping.get(elem).lastIndexOf("^^") + 2);
                                                 builder2.append("</td><td align=center><a href=\"" + type + "\">"
                                                                 + type.substring(type.lastIndexOf('#') + 1) + "</a></td></tr>");
                                         } else {
                                                 if ((mapping.get(elem).contains("http") || mapping.get(elem).contains("file:/"))
                                                                 && mapping.get(elem).contains("#")) {
                                                         builder2.append("</td><td align=center><a href=\"" + mapping.get(elem) + "\">"
                                                                         + mapping.get(elem).substring(mapping.get(elem).lastIndexOf('#') + 1)
                                                                         + "</a></td></tr>");
                                                 } else if ((mapping.get(elem).contains("http") || mapping.get(elem).contains("file:/"))
                                                                 && mapping.get(elem).contains("/")) {
                                                         builder2.append("</td><td align=center><a href=\"" + mapping.get(elem) + "\">"
                                                                         + mapping.get(elem).substring(mapping.get(elem).lastIndexOf('/') + 1)
                                                                         + "</a></td></tr>");
                                                 } else {
                                                         builder2.append("</td><td align=center><a href=\"" + mapping.get(elem) + "\">"
                                                                         + mapping.get(elem) + "</a></td></tr>");
                                                 }
                                         }
                                         if (elem.contains("http://www.opengis.net/ont/geosparql#asWKT")) {
                                                 geometry.put("type", mapping.get(elem).substring(0, mapping.get(elem).indexOf('(')));
                                                 String coords = mapping.get(elem).substring(mapping.get(elem).indexOf('(') + 1,
                                                                 mapping.get(elem).indexOf(')'));
                                                 JSONArray arr = new JSONArray();
                                                 geometry.put("coordinates", arr);
                                                 if(!coords.contains(",")) {
                                                         String[] commasplit = coords.split(" ");
                                                         arr.put(Double.valueOf(commasplit[0]));
                                                         arr.put(Double.valueOf(commasplit[1]));
                                                 }else {
                                                 for (String coord : coords.split(" ")) {
                                                         if (coord.contains(",")) {
                                                                 String[] commasplit = coord.split(",");
                                                                 arr.put(Double.valueOf(commasplit[0]));
                                                                 arr.put(Double.valueOf(commasplit[1]));
                                                         }
                                                 }
                                                 }
                                         }
                                         if (elem.contains("lat")) {
                                                 lat = mapping.get(elem);
                                         }
                                         if (elem.contains("lon")) {
                                                 lon = mapping.get(elem);
                                         }
                                         if (lat != null && lon != null) {
                                                 geometry.put("type", "Point");
                                                 JSONArray arr = new JSONArray();
                                                 geometry.put("coordinates", arr);
                                                 arr.put(lon);
                                                 arr.put(lat);
                                         }
                                         properties.put(elem, mapping.get(elem));
                                 }
                         }
                 }
                 builder2.append("</table><br/>Styles:"
                                 + TripleStoreConnector.getStyleNames(wfsconf.getString("baseurl"), workingobj, format));
                 builder.append("var geojson=" + geojson.toString() + "</script>");
                 builder.append(builder2.toString());
                 builder.append("</td></tr></table>");
                 builder.append("</div></div><footer id=\"footer\"><table width=100%><tbody><tr><td><a href=\"" + wfsconf.getString("baseurl")
                 + "/collections/"+workingobj.getString("name")+"?f=html\">Back to Collections</a></td><td align=right>This page in <a href=\""
                 + wfsconf.getString("baseurl") + "/collections/" + workingobj.getString("name")
                 + "/queryables?f=gml\">[GML]</a> <a href=\"" + wfsconf.getString("baseurl") + "/collections/"
                 + workingobj.getString("name") + "/queryables?f=geojson\">[JSON]</a></td></tr></tbody></table></footer></body></html>");
                 return Response.ok(builder.toString()).type(MediaType.TEXT_HTML).build();
         }
queryConfigs()
Response queryConfigs ()
Returns the query configuration document.
Returns
The query configuration document as JSON.
{
                 JSONObject res = new JSONObject();
                 for (int i = 0; i < wfsconf.getJSONArray("datasets").length(); i++) {
                         JSONObject curjson = wfsconf.getJSONArray("datasets").getJSONObject(i);
                         JSONObject instance = new JSONObject();
                         if (!res.has(curjson.getString("triplestore"))) {
                                 res.put(curjson.getString("triplestore"), new JSONArray());
                         }
                         res.getJSONArray(curjson.getString("triplestore")).put(instance);
                         instance.put("triplestore", curjson.getString("triplestore"));
                         instance.put("query", curjson.getString("query"));
                         instance.put("name", curjson.getString("name"));
                         instance.put("class", curjson.getString("class"));
                 }
                 return Response.ok(res.toString(2)).type(MediaType.APPLICATION_JSON).build();
         }
queryService() [1/2]
String queryService (@Parameter(description="SPARQL query to be resolved") @QueryParam("query") String query, @Parameter(description="SPARQL endpoint to query") @QueryParam("endpoint") String endpoint)
Exposes a query service which returns a SPARQL query result as REST.
Parameters
query The query to send
endpoint The endpoint to query
Returns
The query result
References TripleStoreConnector.executeQuery().
{
                 final String dir = System.getProperty("user.dir");
                 System.out.println("current dir = " + dir);
                 return TripleStoreConnector.executeQuery(query, endpoint, false);
         }
queryService() [2/2]
String queryService (@Parameter(description="SPARQL query to be resolved") @QueryParam("query") String query, @Parameter(description="SPARQL endpoint to be queried") @QueryParam("endpoint") String endpoint, @Parameter(description="Indicates whether geojson should be returned to be shown in a map view") @QueryParam("geojson") String geojson)
Exposes a query service which returns a SPARQL query result as REST.
Parameters
query The query to send
endpoint The endpoint to query
geojson indicates whether to return an additional representation as GeoJSON for a map view
Returns
The query result
References TripleStoreConnector.executeQuery().
{
                 final String dir = System.getProperty("user.dir");
                 System.out.println("current dir = " + dir);
                 return TripleStoreConnector.executeQuery(query, endpoint, true);
         }
saveFeatureTypes()
Boolean saveFeatureTypes (@Parameter(description="JSON object containing feature types to be saved") @QueryParam("featjson") String featureTypesJSON, @Parameter(description="Authtoken for authorization") @DefaultValue("") @QueryParam("authtoken") String authtoken)
Saves feature types in the SemanticWFS Service.
Parameters
featureTypesJSON The featuretype JSON to save
authtoken The authtoken authorizing the save operation
Returns
True if successful, false otherwise
References UserType.Administrator, UserType.Configurer, UserManagementConnection.getInstance(), User.getUserlevel(), and UserManagementConnection.loginAuthToken().
{
                 User user=UserManagementConnection.getInstance().loginAuthToken(authtoken);
                 if(user!=null && (user.getUserlevel()==UserType.Configurer || user.getUserlevel()==UserType.Administrator)) {
                         JSONArray datasets = wfsconf.getJSONArray("featjson");
                         wfsconf.put("datasets", datasets);
                         return true;
                 }
                 return false;
         }
style()
Response style (@Parameter(description="The service type which is addressed") @DefaultValue("WFS") @QueryParam("SERVICE") String service, @Parameter(description="Request type of this query") @DefaultValue("GetStyle") @QueryParam("REQUEST") String request, @Parameter(description="Feature type names") @DefaultValue("") @QueryParam("TYPENAME") String typename, @Parameter(description="Feature type names") @DefaultValue("") @QueryParam("TYPENAMES") String typenames, @Parameter(description="Outputformat of the style which is returned") @DefaultValue("gml") @QueryParam("OUTPUTFORMAT") String output)
Returns a style information in a given format for a given featuretype and styleid.
Parameters
service The service descriptor
request The requset parameter
typename
typenames
output
Returns
{
                 if (output.contains("gml")) {
                         StringWriter strwriter = new StringWriter();
                         XMLOutputFactory outputt = XMLOutputFactory.newInstance();
                         XMLStreamWriter writer;
                         try {
                                 writer = new IndentingXMLStreamWriter(outputt.createXMLStreamWriter(strwriter));
                                 writer.writeStartDocument();
                                 writer.writeAttribute("xmlns", "http://www.opengis.net/ogcapi-features-1/1.0");
                                 writer.writeAttribute("xmlns:sld", "http://www.opengis.net/sld");
                                 writer.writeAttribute("xmlns:ogc", "http://www.opengis.net/ogc");
                                 writer.writeAttribute("xmlns:xlink", "http://www.w3.org/1999/xlink");
                                 writer.writeAttribute("xmlns:gml", "http://www.opengis.net/gml");
                                 writer.writeAttribute("xmlns:xsi", "http://www.w3.org/1999/xlink");
                                 writer.writeAttribute("version", "1.0.0");
                                 writer.writeStartElement("sld:NamedLayer");
                                 writer.writeStartElement("sld:Name");
                                 writer.writeCharacters(typename);
                                 writer.writeEndElement();
                                 writer.writeStartElement("sld:StyledLayerDescriptor");
                         } catch (XMLStreamException e) {
                                 // TODO Auto-generated catch block
                                 e.printStackTrace();
                         }
                 }
                 return null;
         }
transaction()
String transaction ()
Transaction method of the WFS specification.
Returns
{
                 return null;
         }
vectorTiles()
Response vectorTiles (@DefaultValue("CSW") @QueryParam("SERVICE") String service, @DefaultValue("GetCapabilities") @QueryParam("REQUEST") String request, @DefaultValue("2.0.2") @QueryParam("VERSION") String version, @DefaultValue("") @QueryParam("TYPENAME") String typename, @DefaultValue("") @QueryParam("TYPENAMES") String typenames, @DefaultValue("gml") @QueryParam("OUTPUTFORMAT") String output)
Returns a vector tile representation of a given feature type.
Parameters
service
request
version
typename
typenames
output
Returns
{
                 return null;
         }
Member Data Documentation
bboxCache
Map<String, Double[]> bboxCache = new TreeMap<>() static
featureTypeCache
Map<String, Map<String, String> > featureTypeCache = new TreeMap<>() static
Referenced by TripleStoreConnector.getPropertyFromMapping().
hitCache
Map<String, Tuple<Date, String> > hitCache = new TreeMap<>() static
htmlHead
String htmlHead package
milliesInDays
long milliesInDays = 24 * 60 * 60 * 1000 static
nameSpaceCache
Map<String, Map<String, String> > nameSpaceCache = new TreeMap<>() static
Referenced by GMLFormatter.addTagsFromJSONObject(), WebService.collectionItems(), MapMLFormatter.formatter(), OSMFormatter.formatter(), GMLFormatter.formatter(), and TripleStoreConnector.getFeatureTypeInformation().
openapijson
final MediaType openapijson =new MediaType("application", "vnd.oai.openapi+json;version=3.0") static
SERVERURL
String SERVERURL = "http://localhost:8080/WFSGeoSPARQL/rest/wfs?"
SERVICETYPEVERSION
String SERVICETYPEVERSION = "2.0.0"
styleCache
Map<String, Map<String, StyleObject> > styleCache = new TreeMap<>() static
Referenced by TripleStoreConnector.getStyle().
triplestoreconf
JSONObject triplestoreconf = null static
Referenced by WebService.docCollectionJSON(), and TripleStoreConnector.executeQuery().
wfsconf
JSONObject wfsconf = null static
Referenced by MapMLFormatter.formatter(), and HTMLFormatter.formatter().
xmlwriter
XMLStreamWriter xmlwriter