semanticwfs: WKBRasterWriter Class Reference
WKBRasterWriter Class Reference
WKB Raster Writer, used in postGIS 2 but can be used elsewhere.
Public Member Functions
WKBRasterWriter ()
void reset ()
Reset values before new write call.
byte [] write (final GridCoverage coverage) throws IOException, FactoryException
Encode given coverage in Postgis WKB.
void write (final GridCoverage coverage, final OutputStream stream) throws IOException, FactoryException
Encode given coverage in Postgis WKB.
void write (final GridCoverage coverage, final OutputStream stream, final boolean littleEndian) throws IOException, FactoryException
Encode given coverage in Postgis WKB.
byte [] write (final RenderedImage image, final AffineTransform gridToCRS, final int srid) throws IOException
Encode given image in Postgis WKB.
byte [] write (final Raster image, final AffineTransform gridToCRS, final int srid) throws IOException
Encode given image in Postgis WKB.
void write (final RenderedImage image, AffineTransform gridToCRS, final int srid, final OutputStream stream) throws IOException
Encode given image in Postgis WKB.
void write (final Raster image, AffineTransform gridToCRS, final int srid, final OutputStream stream) throws IOException
Encode given image in Postgis WKB.
void write (final Raster image, AffineTransform gridToCRS, final int srid, OutputStream stream, final boolean littleEndian) throws IOException
Encode given image in Postgis WKB.
Detailed Description
WKB Raster Writer, used in postGIS 2 but can be used elsewhere.
Author
Johann Sorel (Geomatys)
Constructor & Destructor Documentation
WKBRasterWriter()
WKBRasterWriter ()
{
     }
Member Function Documentation
reset()
void reset ()
Reset values before new write call.
{
     }
write() [1/8]
byte [] write (final GridCoverage coverage) throws IOException, FactoryException
Encode given coverage in Postgis WKB.
Parameters
coverage : grid coverage 2d , not null
Returns
byte[] encoded image
Exceptions
IOException
Referenced by WKBRasterWriter.write().
{
         final ByteArrayOutputStream out = new ByteArrayOutputStream();
         write(coverage, out);
         return out.toByteArray();
     }
write() [2/8]
void write (final GridCoverage coverage, final OutputStream stream) throws IOException, FactoryException
Encode given coverage in Postgis WKB.
Parameters
coverage : grid coverage 2d , not null
stream : output stream to write in
Exceptions
IOException
References WKBRasterWriter.write().
{
         write(coverage, stream, true);
     }
write() [3/8]
void write (final GridCoverage coverage, final OutputStream stream, final boolean littleEndian) throws IOException, FactoryException
Encode given coverage in Postgis WKB.
Parameters
coverage : grid coverage 2d , not null
stream : output stream to write in
littleEndian : wanted value encoding
Exceptions
IOException
References WKBRasterWriter.write().
{
         final GridGeometry gridGeometry = coverage.getGridGeometry();
         final CoordinateReferenceSystem crs = gridGeometry.getCoordinateReferenceSystem();
         final Integer srid = IdentifiedObjects.lookupEPSG(crs);
         if (srid == null) {
             throw new IOException("CoordinateReferenceSystem does not have an EPSG code.");
         }
         final MathTransform gridToCRS = coverage.getGridGeometry().getGridToCRS(PixelInCell.CELL_CENTER);
         if (!(gridToCRS instanceof AffineTransform)) {
             throw new IOException("Coverage GridToCRS transform is not affine.");
         }
         final RenderedImage image = coverage.render(null);
         write(image, (AffineTransform)gridToCRS, srid, stream);
     }
write() [4/8]
byte [] write (final RenderedImage image, final AffineTransform gridToCRS, final int srid) throws IOException
Encode given image in Postgis WKB.
Parameters
image : image , not null
gridToCRS : image grid to crs, can be null
srid : image srid
Returns
byte[] encoded image
Exceptions
IOException
References WKBRasterWriter.write().
{
         final ByteArrayOutputStream out = new ByteArrayOutputStream();
         write(image, gridToCRS, srid, out);
         return out.toByteArray();
     }
write() [5/8]
byte [] write (final Raster image, final AffineTransform gridToCRS, final int srid) throws IOException
Encode given image in Postgis WKB.
Parameters
image : image , not null
gridToCRS : image grid to crs, can be null
srid : image srid
Returns
byte[] encoded image
Exceptions
IOException
References WKBRasterWriter.write().
{
         final ByteArrayOutputStream out = new ByteArrayOutputStream();
         write(image, gridToCRS, srid, out);
         return out.toByteArray();
     }
write() [6/8]
void write (final RenderedImage image, AffineTransform gridToCRS, final int srid, final OutputStream stream) throws IOException
Encode given image in Postgis WKB.
Parameters
image : image , not null
gridToCRS : image grid to crs, can be null
srid : image srid
stream : output stream to write in
Exceptions
IOException
References WKBRasterWriter.write().
{
         write(image.getData(), gridToCRS, srid, stream, true);
     }
write() [7/8]
void write (final Raster image, AffineTransform gridToCRS, final int srid, final OutputStream stream) throws IOException
Encode given image in Postgis WKB.
Parameters
image : image , not null
gridToCRS : image grid to crs, can be null
srid : image srid
stream : output stream to write in
Exceptions
IOException
References WKBRasterWriter.write().
{
         write(image, gridToCRS, srid, stream, true);
     }
write() [8/8]
void write (final Raster image, AffineTransform gridToCRS, final int srid, OutputStream stream, final boolean littleEndian) throws IOException
Encode given image in Postgis WKB.
Parameters
image : image , not null
gridToCRS : image grid to crs, can be null
srid : image srid
stream : output stream to write in
littleEndian : wanted value encoding
Exceptions
IOException
References WKBRasterConstants.getNbBytePerPixel(), and WKBRasterConstants.getPixelType().
{
         if(gridToCRS == null){
             gridToCRS = new AffineTransform();
         }
         if (!(stream instanceof BufferedOutputStream)) {
             stream = new BufferedOutputStream(stream);
         }
         final DataOutput ds;
         if(littleEndian){
             ds = new LEDataOutputStream(stream);
         }else{
             ds = new DataOutputStream(stream);
         }
         final SampleModel sm = image.getSampleModel();
         final Raster raster = image;
         final int nbBand = sm.getNumBands();
         final int width = image.getWidth();
         final int height = image.getHeight();
         int databufferType = sm.getDataType();
         if(databufferType == DataBuffer.TYPE_INT){
             //special case, most image compression bands on single int when it would be byte
             if(sm.getSampleSize()[0] <= 8){
                 databufferType = DataBuffer.TYPE_BYTE;
             }
         }
         final int pixelType = WKBRasterConstants.getPixelType(databufferType);
         final int bytePerpixel = WKBRasterConstants.getNbBytePerPixel(pixelType);
         //endianess
         ds.write( littleEndian ? 1 : 0 );
         //version, 0 for now
         ds.writeShort(0);
         //number of bands
         ds.writeShort(nbBand);
         //grid to crs
         ds.writeDouble(gridToCRS.getScaleX());
         ds.writeDouble(gridToCRS.getScaleY());
         ds.writeDouble(gridToCRS.getTranslateX());
         ds.writeDouble(gridToCRS.getTranslateY());
         ds.writeDouble(gridToCRS.getShearX());
         ds.writeDouble(gridToCRS.getShearY());
         //write srid
         ds.writeInt(srid);
         //width and height
         ds.writeShort(width);
         ds.writeShort(height);
         //write each band
         for(int b=0;b<nbBand;b++){
             // band description
             final byte flags = (byte) pixelType;
             // OffDatabase = false
             // TODO HasNodata : we don't have informations for no data
             //      this would requiere a SampleDimension object
             // IsNodata = false
             // Reserved = false
             ds.write(flags);
             // TODO no data value
             ds.write(new byte[bytePerpixel]);
             //write values
             for(int y=raster.getMinY(),maxy=raster.getMinY()+height;y<maxy;y++){
                 for(int x=raster.getMinX(),maxx=raster.getMinX()+width;x<maxx;x++){
                     switch(databufferType){
                         case DataBuffer.TYPE_BYTE :     ds.writeByte( (byte)raster.getSample(x, y, b)); break;
                         case DataBuffer.TYPE_SHORT :    ds.writeShort( (short)raster.getSample(x, y, b)); break;
                         case DataBuffer.TYPE_USHORT :   ds.writeShort( (short)raster.getSample(x, y, b)); break;
                         case DataBuffer.TYPE_INT :      ds.writeInt( raster.getSample(x, y, b)); break;
                         case DataBuffer.TYPE_FLOAT :    ds.writeFloat( raster.getSampleFloat(x, y, b)); break;
                         case DataBuffer.TYPE_DOUBLE :   ds.writeDouble( raster.getSampleDouble(x, y, b)); break;
                     }
                 }
             }
         }
         stream.flush();
     }