semanticwfs: TWKBReader.ByteBufferInputStream Class Reference
TWKBReader.ByteBufferInputStream Class Reference
Public Member Functions
ByteBufferInputStream (final ByteBuffer byteBuffer)
int read () throws IOException
int read (final byte[] bytes, final int offset, final int length) throws IOException
int available () throws IOException
Private Attributes
final ByteBuffer byteBuffer
Constructor & Destructor Documentation
ByteBufferInputStream()
ByteBufferInputStream (final ByteBuffer byteBuffer)
References TWKBReader.ByteBufferInputStream.byteBuffer.
Referenced by TWKBReader.read().
{
      this.byteBuffer = byteBuffer;
    }
Member Function Documentation
available()
int available () throws IOException
{
      return byteBuffer.remaining();
    }
read() [1/2]
int read () throws IOException
Referenced by TWKBReader.read(), and TWKBReader.readGeometryCollection().
{
      if (!byteBuffer.hasRemaining()) {
        return -1;
      }
      return byteBuffer.get() & 0xFF;
    }
read() [2/2]
int read (final byte [] bytes, final int offset, final int length) throws IOException
{
      if (length == 0) {
        return 0;
      }
      final int count = Math.min(byteBuffer.remaining(), length);
      if (count == 0) {
        return -1;
      }
      byteBuffer.get(bytes, offset, count);
      return count;
    }
Member Data Documentation
byteBuffer
final ByteBuffer byteBuffer private
Referenced by TWKBReader.ByteBufferInputStream.ByteBufferInputStream().