semanticwfs: TWKBReader Class Reference
TWKBReader Class Reference
Classes
class ByteBufferInputStream
class ExtendedPrecisionReader
class PrecisionReader
Public Member Functions
TWKBReader ()
Geometry read (final ByteBuffer bytes) throws ParseException
Geometry read (final byte[] bytes) throws ParseException
Geometry read (final DataInput input) throws IOException
Private Member Functions
Point readPoint (final PrecisionReader precision, final byte metadata, final DataInput input) throws IOException
LineString readLineString (final PrecisionReader precision, final byte metadata, final DataInput input) throws IOException
Polygon readPolygon (final PrecisionReader precision, final byte metadata, final DataInput input) throws IOException
MultiPoint readMultiPoint (final PrecisionReader precision, final byte metadata, final DataInput input) throws IOException
MultiLineString readMultiLineString (final PrecisionReader precision, final byte metadata, final DataInput input) throws IOException
MultiPolygon readMultiPolygon (final PrecisionReader precision, final byte metadata, final DataInput input) throws IOException
GeometryCollection readGeometryCollection (final DataInput input, final byte metadata) throws IOException
Static Private Attributes
static final GeometryFactory fac =new GeometryFactory()
Constructor & Destructor Documentation
TWKBReader()
TWKBReader ()
 {}
Member Function Documentation
read() [1/3]
Geometry read (final ByteBuffer bytes) throws ParseException
References TWKBReader.ByteBufferInputStream.ByteBufferInputStream(), and TWKBReader.ByteBufferInputStream.read().
{
    try (ByteBufferInputStream in = new ByteBufferInputStream(bytes)) {
      try (DataInputStream input = new DataInputStream(in)) {
        return read(input);
      }
    } catch (final IOException e) {
      throw new ParseException("Error reading TWKB geometry.", e);
    }
  }
read() [2/3]
Geometry read (final byte [] bytes) throws ParseException
References TWKBReader.ByteBufferInputStream.read().
{
    try (ByteArrayInputStream in = new ByteArrayInputStream(bytes)) {
      try (DataInputStream input = new DataInputStream(in)) {
        return read(input);
      }
    } catch (final IOException e) {
      throw new ParseException("Error reading TWKB geometry.", e);
    }
  }
read() [3/3]
Geometry read (final DataInput input) throws IOException
References TWKBUtils.EXTENDED_DIMENSIONS, TWKBUtils.GEOMETRYCOLLECTION_TYPE, TWKBUtils.LINESTRING_TYPE, TWKBUtils.MULTILINESTRING_TYPE, TWKBUtils.MULTIPOINT_TYPE, TWKBUtils.MULTIPOLYGON_TYPE, TWKBUtils.POINT_TYPE, TWKBUtils.POLYGON_TYPE, TWKBReader.readGeometryCollection(), TWKBReader.readLineString(), TWKBReader.readMultiLineString(), TWKBReader.readMultiPoint(), TWKBReader.readMultiPolygon(), TWKBReader.readPoint(), TWKBReader.readPolygon(), and TWKBUtils.zigZagDecode().
{
    final byte typeAndPrecision = input.readByte();
    final byte type = (byte) (typeAndPrecision & 0x0F);
    final int basePrecision = TWKBUtils.zigZagDecode((typeAndPrecision & 0xF0) >> 4);
    final byte metadata = input.readByte();
    PrecisionReader precision;
    if ((metadata & TWKBUtils.EXTENDED_DIMENSIONS) != 0) {
      final byte extendedDimensions = input.readByte();
      precision = new ExtendedPrecisionReader(basePrecision, extendedDimensions);
    } else {
      precision = new PrecisionReader(basePrecision);
    }
    switch (type) {
      case TWKBUtils.POINT_TYPE:
        return readPoint(precision, metadata, input);
      case TWKBUtils.LINESTRING_TYPE:
        return readLineString(precision, metadata, input);
      case TWKBUtils.POLYGON_TYPE:
        return readPolygon(precision, metadata, input);
      case TWKBUtils.MULTIPOINT_TYPE:
        return readMultiPoint(precision, metadata, input);
      case TWKBUtils.MULTILINESTRING_TYPE:
        return readMultiLineString(precision, metadata, input);
      case TWKBUtils.MULTIPOLYGON_TYPE:
        return readMultiPolygon(precision, metadata, input);
      case TWKBUtils.GEOMETRYCOLLECTION_TYPE:
        return readGeometryCollection(input, metadata);
    }
    return null;
  }
readGeometryCollection()
GeometryCollection readGeometryCollection (final DataInput input, final byte metadata) throws IOException private
References TWKBUtils.EMPTY_GEOMETRY, and TWKBReader.ByteBufferInputStream.read().
Referenced by TWKBReader.read().
{
    if ((metadata & TWKBUtils.EMPTY_GEOMETRY) != 0) {
      return fac.createGeometryCollection();
    }
    final int numGeometries = Varint.readUnsignedVarInt(input);
    final Geometry[] geometries = new Geometry[numGeometries];
    for (int i = 0; i < numGeometries; i++) {
      geometries[i] = read(input);
    }
    return fac.createGeometryCollection(geometries);
  }
readLineString()
LineString readLineString (final PrecisionReader precision, final byte metadata, final DataInput input) throws IOException private
References TWKBUtils.EMPTY_GEOMETRY.
Referenced by TWKBReader.read().
{
    if ((metadata & TWKBUtils.EMPTY_GEOMETRY) != 0) {
      return fac.createLineString();
    }
    final Coordinate[] coordinates = precision.readPointArray(input);
    return fac.createLineString(coordinates);
  }
readMultiLineString()
MultiLineString readMultiLineString (final PrecisionReader precision, final byte metadata, final DataInput input) throws IOException private
References TWKBUtils.EMPTY_GEOMETRY.
Referenced by TWKBReader.read().
{
    if ((metadata & TWKBUtils.EMPTY_GEOMETRY) != 0) {
      return fac.createMultiLineString();
    }
    final int numLines = Varint.readUnsignedVarInt(input);
    final LineString[] lines = new LineString[numLines];
    for (int i = 0; i < numLines; i++) {
      lines[i] = fac.createLineString(precision.readPointArray(input));
    }
    return fac.createMultiLineString(lines);
  }
readMultiPoint()
MultiPoint readMultiPoint (final PrecisionReader precision, final byte metadata, final DataInput input) throws IOException private
References TWKBUtils.EMPTY_GEOMETRY.
Referenced by TWKBReader.read().
{
    if ((metadata & TWKBUtils.EMPTY_GEOMETRY) != 0) {
      return fac.createMultiPoint();
    }
    final Coordinate[] points = precision.readPointArray(input);
    return fac.createMultiPointFromCoords(points);
  }
readMultiPolygon()
MultiPolygon readMultiPolygon (final PrecisionReader precision, final byte metadata, final DataInput input) throws IOException private
References TWKBUtils.EMPTY_GEOMETRY.
Referenced by TWKBReader.read().
{
    if ((metadata & TWKBUtils.EMPTY_GEOMETRY) != 0) {
      return fac.createMultiPolygon();
    }
    final int numPolygons = Varint.readUnsignedVarInt(input);
    final Polygon[] polygons = new Polygon[numPolygons];
    int numRings;
    for (int i = 0; i < numPolygons; i++) {
      numRings = Varint.readUnsignedVarInt(input);
      if (numRings == 0) {
        polygons[i] = fac.createPolygon();
        continue;
      }
      final LinearRing exteriorRing =
          fac.createLinearRing(precision.readPointArray(input));
      final LinearRing[] interiorRings = new LinearRing[numRings - 1];
      for (int j = 0; j < (numRings - 1); j++) {
        interiorRings[j] =
            fac.createLinearRing(precision.readPointArray(input));
      }
      polygons[i] = fac.createPolygon(exteriorRing, interiorRings);
    }
    return fac.createMultiPolygon(polygons);
  }
readPoint()
Point readPoint (final PrecisionReader precision, final byte metadata, final DataInput input) throws IOException private
References TWKBUtils.EMPTY_GEOMETRY.
Referenced by TWKBReader.read().
{
    if ((metadata & TWKBUtils.EMPTY_GEOMETRY) != 0) {
      return fac.createPoint();
    }
    final Coordinate coordinate = precision.readPoint(input);
    return fac.createPoint(coordinate);
  }
readPolygon()
Polygon readPolygon (final PrecisionReader precision, final byte metadata, final DataInput input) throws IOException private
References TWKBUtils.EMPTY_GEOMETRY.
Referenced by TWKBReader.read().
{
    if ((metadata & TWKBUtils.EMPTY_GEOMETRY) != 0) {
      return fac.createPolygon();
    }
    final int numRings = Varint.readUnsignedVarInt(input);
    final LinearRing exteriorRing =
        fac.createLinearRing(precision.readPointArray(input));
    final LinearRing[] interiorRings = new LinearRing[numRings - 1];
    for (int i = 0; i < (numRings - 1); i++) {
      interiorRings[i] =
          fac.createLinearRing(precision.readPointArray(input));
    }
    return fac.createPolygon(exteriorRing, interiorRings);
  }
Member Data Documentation
fac
final GeometryFactory fac =new GeometryFactory() static private