semanticwfs: LEDataOutputStream Class Reference
LEDataOutputStream Class Reference
Little endian Data output stream.
Public Member Functions
LEDataOutputStream (OutputStream out)
long getPosition ()
Get current stream position from the first written byte.
void write (int b) throws IOException
void write (byte[] data, int offset, int length) throws IOException
void writeBoolean (boolean b) throws IOException
void writeByte (int b) throws IOException
void writeShort (int s) throws IOException
final void writeShorts (short[] values) throws IOException
Write multiple values in one call.
void writeUnsignedShort (int s) throws IOException
final void writeUnsignedShorts (int[] values) throws IOException
Write multiple values in one call.
void writeChar (int c) throws IOException
void writeInt (int i) throws IOException
final void writeInts (int[] values) throws IOException
Write multiple values in one call.
void writeLong (long l) throws IOException
final void writeLongs (long[] values) throws IOException
Write multiple values in one call.
final void writeFloat (float f) throws IOException
final void writeFloats (float[] values) throws IOException
Write multiple values in one call.
final void writeDouble (double d) throws IOException
final void writeDoubles (double[] values) throws IOException
Write multiple values in one call.
void writeBytes (String s) throws IOException
void writeChars (String s) throws IOException
void writeUTF (String s) throws IOException
void realign (int padding) throws IOException
Align byte stream to a padding value, 0 bytes will be added until padding value is reached.
Private Attributes
long position = 0
Detailed Description
Little endian Data output stream.
Author
Johann Sorel (Geomatys)
Constructor & Destructor Documentation
LEDataOutputStream()
LEDataOutputStream (OutputStream out)
{
         super(out);
     }
Member Function Documentation
getPosition()
long getPosition ()
Get current stream position from the first written byte.
Returns
stream position
References LEDataOutputStream.position.
{
         return position;
     }
realign()
void realign (int padding) throws IOException
Align byte stream to a padding value, 0 bytes will be added until padding value is reached.
Padding values are usually very small, 2, 4 or 8 bytes to ensure primitive types such as Short, Integer, Float are aligned in memory.
Parameters
padding value to realign.
Exceptions
IOException
References LEDataOutputStream.write().
{
         while ((position%padding) != 0) {
             write(0);
         }
     }
write() [1/2]
void write (int b) throws IOException
Referenced by LEDataOutputStream.realign(), and LEDataOutputStream.writeBoolean().
{
         out.write(b);
         position++;
     }
write() [2/2]
void write (byte [] data, int offset, int length) throws IOException
{
         out.write(data, offset, length);
         position+=length;
     }
writeBoolean()
void writeBoolean (boolean b) throws IOException
References LEDataOutputStream.write().
{
         this.write( b ? 1 : 0 );
     }
writeByte()
void writeByte (int b) throws IOException
{
         out.write(b);
         position++;
     }
writeBytes()
void writeBytes (String s) throws IOException
{
         for (int i=0,n=s.length(); i<n; i++) {
             out.write((byte) s.charAt(i));
         }
         position+=s.length();
     }
writeChar()
void writeChar (int c) throws IOException
{
         out.write((c      ) & 0xFF);
         out.write((c >>> 8) & 0xFF);
         position+=2;
     }
writeChars()
void writeChars (String s) throws IOException
{
         for (int i=0,n=s.length(); i<n; i++) {
             final char c = s.charAt(i);
             out.write((c      ) & 0xFF);
             out.write((c >>> 8) & 0xFF);
         }
         position+=s.length()*2;
     }
writeDouble()
final void writeDouble (double d) throws IOException
References LEDataOutputStream.writeLong().
Referenced by LEDataOutputStream.writeDoubles().
{
         this.writeLong(Double.doubleToLongBits(d));
     }
writeDoubles()
final void writeDoubles (double [] values) throws IOException
Write multiple values in one call.
Parameters
values values to write
Exceptions
IOException
References LEDataOutputStream.writeDouble().
{
         for (double value : values) {
             writeDouble(value);
         }
     }
writeFloat()
final void writeFloat (float f) throws IOException
References LEDataOutputStream.writeInt().
Referenced by LEDataOutputStream.writeFloats().
{
         this.writeInt(Float.floatToIntBits(f));
     }
writeFloats()
final void writeFloats (float [] values) throws IOException
Write multiple values in one call.
Parameters
values values to write
Exceptions
IOException
References LEDataOutputStream.writeFloat().
{
         for (float value : values) {
             writeFloat(value);
         }
     }
writeInt()
void writeInt (int i) throws IOException
Referenced by LEDataOutputStream.writeFloat(), and LEDataOutputStream.writeInts().
{
         out.write((i       ) & 0xFF);
         out.write((i >>>  8) & 0xFF);
         out.write((i >>> 16) & 0xFF);
         out.write((i >>> 24) & 0xFF);
         position+=4;
     }
writeInts()
final void writeInts (int [] values) throws IOException
Write multiple values in one call.
Parameters
values values to write
Exceptions
IOException
References LEDataOutputStream.writeInt().
{
         for (int value : values) {
             writeInt(value);
         }
     }
writeLong()
void writeLong (long l) throws IOException
Referenced by LEDataOutputStream.writeDouble(), and LEDataOutputStream.writeLongs().
{
         out.write((int) (l       ) & 0xFF);
         out.write((int) (l >>> 8 ) & 0xFF);
         out.write((int) (l >>> 16) & 0xFF);
         out.write((int) (l >>> 24) & 0xFF);
         out.write((int) (l >>> 32) & 0xFF);
         out.write((int) (l >>> 40) & 0xFF);
         out.write((int) (l >>> 48) & 0xFF);
         out.write((int) (l >>> 56) & 0xFF);
         position+=8;
     }
writeLongs()
final void writeLongs (long [] values) throws IOException
Write multiple values in one call.
Parameters
values values to write
Exceptions
IOException
References LEDataOutputStream.writeLong().
{
         for (long value : values) {
             writeLong(value);
         }
     }
writeShort()
void writeShort (int s) throws IOException
Referenced by LEDataOutputStream.writeShorts(), and LEDataOutputStream.writeUnsignedShort().
{
         out.write((s      ) & 0xFF);
         out.write((s >>> 8) & 0xFF);
         position+=2;
     }
writeShorts()
final void writeShorts (short [] values) throws IOException
Write multiple values in one call.
Parameters
values values to write
Exceptions
IOException
References LEDataOutputStream.writeShort().
{
         for (short value : values) {
             writeShort(value);
         }
     }
writeUnsignedShort()
void writeUnsignedShort (int s) throws IOException
References LEDataOutputStream.writeShort().
Referenced by LEDataOutputStream.writeUnsignedShorts().
{
         writeShort(s);
     }
writeUnsignedShorts()
final void writeUnsignedShorts (int [] values) throws IOException
Write multiple values in one call.
Parameters
values values to write
Exceptions
IOException
References LEDataOutputStream.writeUnsignedShort().
{
         for (int value : values) {
             writeUnsignedShort(value);
         }
     }
writeUTF()
void writeUTF (String s) throws IOException
{
         throw new IOException("Not supported");
     }
Member Data Documentation
position
long position = 0 private
Referenced by LEDataOutputStream.getPosition().