semanticwfs: SampleDimensionType Class Reference
SampleDimensionType Class Reference
Specifies the various dimension types for coverage values.
Public Member Functions
SampleDimensionType[] family ()
Returns the list of codes of the same kind than this code list element.
Static Public Attributes
static final SampleDimensionType UNSIGNED_1BIT = new SampleDimensionType("UNSIGNED_1BIT")
Unsigned 1 bit integers.
static final SampleDimensionType UNSIGNED_2BITS = new SampleDimensionType("UNSIGNED_2BITS")
Unsigned 2 bits integers.
static final SampleDimensionType UNSIGNED_4BITS = new SampleDimensionType("UNSIGNED_4BITS")
Unsigned 4 bits integers.
static final SampleDimensionType UNSIGNED_8BITS = new SampleDimensionType("UNSIGNED_8BITS")
Unsigned 8 bits integers.
static final SampleDimensionType SIGNED_8BITS = new SampleDimensionType("SIGNED_8BITS")
Signed 8 bits integers.
static final SampleDimensionType UNSIGNED_16BITS = new SampleDimensionType("UNSIGNED_16BITS")
Unsigned 16 bits integers.
static final SampleDimensionType SIGNED_16BITS = new SampleDimensionType("SIGNED_16BITS")
Signed 16 bits integers.
static final SampleDimensionType UNSIGNED_32BITS = new SampleDimensionType("UNSIGNED_32BITS")
Unsigned 32 bits integers.
static final SampleDimensionType SIGNED_32BITS = new SampleDimensionType("SIGNED_32BITS")
Signed 32 bits integers.
static final SampleDimensionType REAL_32BITS = new SampleDimensionType("REAL_32BITS")
Simple precision floating point numbers.
static final SampleDimensionType REAL_64BITS = new SampleDimensionType("REAL_64BITS")
Double precision floating point numbers.
Private Member Functions
SampleDimensionType (final String name)
Constructs an element of the given name.
Static Private Attributes
static final List< SampleDimensionType > VALUES = new ArrayList<SampleDimensionType>(11)
List of all enumerations of this type.
Detailed Description
Specifies the various dimension types for coverage values.
For grid coverages, these correspond to band types.
Deprecated:
This is a legacy type from OGC Grid Coverages Implementation specification 1.0.
Author
Martin Desruisseaux (IRD)
Constructor & Destructor Documentation
SampleDimensionType()
SampleDimensionType (final String name) private
Constructs an element of the given name.
The new element is automatically added to the list returned by values().
Parameters
name the name of the new element.
{
         super(name, VALUES);
     }
References SampleDimensionType.VALUES.
Member Function Documentation
family()
SampleDimensionType [] family ()
Returns the list of codes of the same kind than this code list element.
Invoking this method is equivalent to invoking values(), except that this method can be invoked on an instance of the parent
CodeList
class.
Returns
all code {@linkplain #values() values} for this code list.
{
         synchronized (VALUES) {
             return VALUES.toArray(new SampleDimensionType[VALUES.size()]);
         }
     }
References SampleDimensionType.VALUES.
Member Data Documentation
REAL_32BITS
final SampleDimensionType REAL_32BITS = new SampleDimensionType("REAL_32BITS") static
Simple precision floating point numbers.
See also
REAL_64BITS
DataBuffer::TYPE_FLOAT
Referenced by WKBRasterConstants.getDimensionType(), and WKBRasterConstants.getPixelType().
REAL_64BITS
final SampleDimensionType REAL_64BITS = new SampleDimensionType("REAL_64BITS") static
Double precision floating point numbers.
See also
REAL_32BITS
DataBuffer::TYPE_DOUBLE
Referenced by WKBRasterConstants.getDimensionType(), and WKBRasterConstants.getPixelType().
SIGNED_16BITS
final SampleDimensionType SIGNED_16BITS = new SampleDimensionType("SIGNED_16BITS") static
Signed 16 bits integers.
See also
UNSIGNED_16BITS
DataBuffer::TYPE_SHORT
Referenced by WKBRasterConstants.getDimensionType(), and WKBRasterConstants.getPixelType().
SIGNED_32BITS
final SampleDimensionType SIGNED_32BITS = new SampleDimensionType("SIGNED_32BITS") static
Signed 32 bits integers.
See also
UNSIGNED_32BITS
DataBuffer::TYPE_INT
Referenced by WKBRasterConstants.getDimensionType(), and WKBRasterConstants.getPixelType().
SIGNED_8BITS
final SampleDimensionType SIGNED_8BITS = new SampleDimensionType("SIGNED_8BITS") static
Signed 8 bits integers.
See also
UNSIGNED_8BITS
Referenced by WKBRasterConstants.getDimensionType(), and WKBRasterConstants.getPixelType().
UNSIGNED_16BITS
final SampleDimensionType UNSIGNED_16BITS = new SampleDimensionType("UNSIGNED_16BITS") static
Unsigned 16 bits integers.
See also
SIGNED_16BITS
DataBuffer::TYPE_USHORT
Referenced by WKBRasterConstants.getDimensionType(), and WKBRasterConstants.getPixelType().
UNSIGNED_1BIT
final SampleDimensionType UNSIGNED_1BIT = new SampleDimensionType("UNSIGNED_1BIT") static
Unsigned 1 bit integers.
Referenced by WKBRasterConstants.getDimensionType(), and WKBRasterConstants.getPixelType().
UNSIGNED_2BITS
final SampleDimensionType UNSIGNED_2BITS = new SampleDimensionType("UNSIGNED_2BITS") static
Unsigned 2 bits integers.
Referenced by WKBRasterConstants.getDimensionType(), and WKBRasterConstants.getPixelType().
UNSIGNED_32BITS
final SampleDimensionType UNSIGNED_32BITS = new SampleDimensionType("UNSIGNED_32BITS") static
Unsigned 32 bits integers.
See also
SIGNED_32BITS
Referenced by WKBRasterConstants.getDimensionType(), and WKBRasterConstants.getPixelType().
UNSIGNED_4BITS
final SampleDimensionType UNSIGNED_4BITS = new SampleDimensionType("UNSIGNED_4BITS") static
Unsigned 4 bits integers.
Referenced by WKBRasterConstants.getDimensionType(), and WKBRasterConstants.getPixelType().
UNSIGNED_8BITS
final SampleDimensionType UNSIGNED_8BITS = new SampleDimensionType("UNSIGNED_8BITS") static
Unsigned 8 bits integers.
See also
SIGNED_8BITS
DataBuffer::TYPE_BYTE
Referenced by WKBRasterConstants.getDimensionType(), and WKBRasterConstants.getPixelType().
VALUES
final List<SampleDimensionType> VALUES = new ArrayList<SampleDimensionType>(11) static private
List of all enumerations of this type.
Must be declared before any enum declaration.
Referenced by SampleDimensionType.family(), and SampleDimensionType.SampleDimensionType().